### ISSUE TITLE
[REQ] javgiga.com

### ISSUE THREAD

**Issue by inablock** [bebasid/bebasid#100]

**Comment by nxzlem** [comment]
situs [javgiga.com] dah aku tambahin sama ipnya. skrg, jgn lupa re-install bebasid y. nih khusus untuk windows tutorialnya:

1. Buka program "bebasid.bat". (kalau gk ada bebasid.bat, download dlu dari "bebasid.github.io")
2. Pilih default host "ketik (W) terus enter" (Tunggu sampai Installnya selesai).
3. Buka program "bebasid.bat" lagi.
4. Pilih Installin bebasid "ketik (Y) terus enter" (Tunggu sampai installnya selesai).

kalau mau re-install khusus untuk macos bisa cek link di sini:
https://www.vtravel.info/how-to-restore-the-original-default-etchosts-file-in-mac-os-x

terima kasih untuk mengrequestkan situs anda.
-NXzLEM
