### ISSUE TITLE
[REQ] pahe.ph

### ISSUE THREAD

**Issue by Amidst-eng** [bebasid/bebasid#102]
pahe domain baru

**Comment by nxzlem** [comment]
situs [pahe.ph] dah aku tambahin sama ipnya. skrg, jgn lupa re-install bebasid y. nih khusus untuk windows tutorialnya:

Buka program "bebasid.bat".
Pilih default host "ketik (W) terus enter" (Tunggu sampai Installnya selesai).
Buka program "bebasid.bat" lagi.
Pilih Installin bebasid "ketik (Y) terus enter" (Tunggu sampai installnya selesai).

kalau mau re-install khusus untuk macos bisa cek link di sini:
https://www.vtravel.info/how-to-restore-the-original-default-etchosts-file-in-mac-os-x

terima kasih untuk mengrequestkan situs anda.
-NXzLEM
