### ISSUE TITLE
[REQ] leetcode.com

### ISSUE THREAD

**Issue by mfauzanf** [bebasid/bebasid#103]
Leetcode akhir2 ini sering lama bgt ke-loadnya

**Comment by andraantariksa** [comment]
LeetCode nggak diblokir. Itu emang LeetCodenya aja yang lambat.

Coba buka diskusi disini
https://leetcode.com/discuss/general-discussion?currentPage=1&orderBy=most_relevant&query=slow

**Comment by nxzlem** [comment]
situs [leetcode.com] dah aku tambahin sama ipnya. skrg, jgn lupa re-install bebasid y. nih tutorialnya:
1. Buka program "bebasid.bat".
2. Pilih default host "ketik (W) terus enter" (Tunggu sampai Installnya selesai).
3. Buka program "bebasid.bat" lagi.
4. Pilih Installin bebasid "ketik (Y) terus enter" (Tunggu sampai installnya selesai).
terima kasih untuk mengrequestkan situs anda.
-NXzLEM
