### ISSUE TITLE
[REQ] lookmovie.ag

### ISSUE THREAD

**Issue by Zzombiee2361** [bebasid/bebasid#110]

**Comment by nxzlem** [comment]
halo, Zzombiee2361.
situs [lookmovie.ag] sudah tambahkan situs dan ipnya. skrg, kalau re-install bebasid.  
khusus untuk windows ada disini tutorialnya:

1. Buka program "bebasid.bat". (kalau gk ada bebasid.bat, download dlu dari "bebasid.github.io")
2. Pilih default host "ketik (W) terus enter" (Tunggu sampai Installnya selesai).
3. Buka program "bebasid.bat" lagi.
4. Pilih Installin bebasid "ketik (Y) terus enter" (Tunggu sampai installnya selesai).
5. kalau ada namanya installasi bebasid selesai, hit/pencet "enter" di keyboardmu. selesai dah.

kalau mau re-install khusus untuk macos tutorialnya ada disini:

1. uninstall bebasid dlu dari cek link di sini :
https://www.vtravel.info/how-to-restore-the-original-default-etchosts-file-in-mac-os-xcc
2. buka terminal dan copy scriptnya (ctrl+c) :
"sudo curl https://raw.githubusercontent.com/bebasid/bebasid/master/releases/hosts -o /etc/hosts"
3. situ pastekan link kamu copy di terminal (ctrl+v) trus hit/pencet "enter" di keyboardmu.
selesai dah.
terima kasih untuk mengrequestkan situs anda.
-NXzLEM
