### ISSUE TITLE
[REQ] investing.com

### ISSUE THREAD

**Issue by skymunn** [bebasid/bebasid#111]

**Comment by gvoze32** [comment]
Subdomain:
id.investing.com
mail.investing.com
m.investing.com
tools.investing.com
a.investing.com
widgets.investing.com
mobile.investing.com
indrates.investing.com
m.id.investing.com

Masih banyak lagi sih, cek di https://dnsdumpster.com/
https://spyse.com/search/subdomain
https://subdomainfinder.c99.nl/
https://hackertarget.com/find-dns-host-records/
https://www.nmmapper.com/sys/tools/subdomainfinder/
widgets.investing.com |  
-- | --



widgets.investing.com |  
-- | --

**Comment by nxzlem** [comment]
halo, skymunn.
situs [investing.com] sudah tambahkan situs dan ipnya. skrg, kalau re-install bebasid.
khusus untuk windows ada disini tutorialnya:

1. Buka program "bebasid.bat". (kalau gk ada bebasid.bat, download dlu dari "bebasid.github.io")
2. Pilih default host "ketik (W) terus enter" (Tunggu sampai Installnya selesai).
3. Buka program "bebasid.bat" lagi.
4. Pilih Installin bebasid "ketik (Y) terus enter" (Tunggu sampai installnya selesai).
5. kalau ada namanya installasi bebasid selesai, hit/pencet "enter" di keyboardmu. 
    selesai dah.

kalau mau re-install khusus untuk macos tutorialnya ada disini:

1. uninstall bebasid dlu dari cek link di sini :
https://www.vtravel.info/how-to-restore-the-original-default-etchosts-file-in-mac-os-x
2. buka terminal dan copy scriptnya (ctrl+c) :
"sudo curl https://raw.githubusercontent.com/bebasid/bebasid/master/releases/hosts -o /etc/hosts"
3. itu pastekan link kamu copy di terminal (ctrl+v) trus hit/pencet "enter" di keyboardmu.
    selesai dah.

terima kasih untuk mengrequestkan situs anda.
-NXzLEM
