### ISSUE TITLE
[BUG] fapforfun.net

### ISSUE THREAD

**Issue by NoiseBox20** [bebasid/bebasid#113]
fapforfun.net terkadang dapat diakses namun setelah beberapa hari terblokir kembali, dan harus memasang ulang bebasid.

 - OS: Windows 10
 - Browser: Brave

**Comment by nxzlem** [comment]
halo, NoiseBox20.
situs [fapforfun.net] sudah di gantikan ip lama ke ip baru, oh iya saya lupa sudah di tambahkan subdomain dari situs [fapforfun.net] ya. 
skrg, kalau mau re-install bebasid, ini khusus untuk windows ya ada disini tutorialnya:

1. Buka program "bebasid.bat". (kalau gk ada bebasid.bat, download dlu dari "bebasid.github.io")
2. Pilih default host "ketik (W) terus enter" (Tunggu sampai Installnya selesai).
3. Buka program "bebasid.bat" lagi.
4. Pilih Installin bebasid "ketik (Y) terus enter" (Tunggu sampai installnya selesai).
5. kalau ada namanya installasi bebasid selesai, hit/pencet "enter" di keyboardmu. 
    selesai dah.

kalau kamu di operasi macos dan mau re-instal bebasid ini khusus untuk macos ya ada disini tutorialnya:

1. uninstall bebasid dlu dari cek link di sini :
https://www.vtravel.info/how-to-restore-the-original-default-etchosts-file-in-mac-os-x
2. buka terminal dan copy scriptnya (ctrl+c) :
"sudo curl https://raw.githubusercontent.com/bebasid/bebasid/master/releases/hosts -o /etc/hosts"
3. itu pastekan link kamu copy di terminal (ctrl+v) trus hit/pencet "enter" di keyboardmu.
    selesai dah.

terima kasih untuk melaporkan bug situs anda.
-NXzLEM
