### ISSUE TITLE
redgifs.com

### ISSUE THREAD

**Issue by lukman210** [bebasid/bebasid#114]
Belum bisa akses untuk ke website redgifs.com

**Comment by nxzlem** [comment]
halo, lukman210.
situs [redgifs.com] sudah ditambahkan situs dan ipnya. 
skrg, kalau mau re-install bebasid, ini khusus untuk windows ya ada disini tutorialnya:

1. Buka program "bebasid.bat". (kalau gk ada bebasid.bat, download dlu dari "bebasid.github.io")
2. Pilih default host "ketik (W) terus enter" (Tunggu sampai Installnya selesai).
3. Buka program "bebasid.bat" lagi.
4. Pilih Installin bebasid "ketik (Y) terus enter" (Tunggu sampai installnya selesai).
5. kalau ada namanya installasi bebasid selesai, hit/pencet "enter" di keyboardmu. 
    selesai dah.

kalau kamu di operasi macos dan mau re-instal bebasid ini khusus untuk macos ya ada disini tutorialnya:

1. uninstall bebasid dlu dari cek link di sini :
https://www.vtravel.info/how-to-restore-the-original-default-etchosts-file-in-mac-os-x
(jangan lupa di translatekan bahasa inggris ke bahasa indonesia dari atas kanan top bar)
![hW4qlx1ZBy](https://user-images.githubusercontent.com/30078972/82074561-29321480-9705-11ea-8f0e-792c3a608382.png)
2. buka terminal dan copy scriptnya (ctrl+c) :
"sudo curl https://raw.githubusercontent.com/bebasid/bebasid/master/releases/hosts -o /etc/hosts"
3. itu pastekan link kamu copy di terminal (ctrl+v) trus hit/pencet "enter" di keyboardmu.
    selesai dah.

Sabar ya untuk cara re-install bebasid di android & ios.
terima kasih untuk mengrequestkan situs anda.
-NXzLEM
