### ISSUE TITLE
penasaran ada ngk buat IPAD

### ISSUE THREAD

**Issue by farouk-dot** [bebasid/bebasid#118]
**Deskripsi mengenai bug**
Pengen coba di ipad apa work

**Comment by PKinfairs** [comment]
Kalau aku lihat, sekarang belum support iOS (iPhone & iPad).

**Comment by iCesenberk** [comment]
kalo mau ganti via edit host tapi syaratnya idevicenya harus di jaibreak dulu

**Comment by icaksh** [comment]
Untuk iPad tidak dapat dilakukan kecuali dijailbreak terlebih dahulu

Apple secara resmi melarang aplikasi yang berguna untuk mengalihkan, memfilter, atau memblokir DNS (untuk iklan)

Referensi
https://apple.stackexchange.com/questions/17077/add-a-hosts-file-entry-without-jailbreaking
https://stackoverflow.com/questions/4783923/can-i-edit-an-ipads-host-file/22935301
