### ISSUE TITLE
[REQ] https://1337x.to/

### ISSUE THREAD

**Issue by g4r15** [bebasid/bebasid#12]
**Deskripsi mengenai bug**
This site can’t be reached1337x.to took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT

**Screenshot**
-

**Device**
 - OS: [cth. Windows 10]
 - Browser [cth. Chrome & Firefox]
- isp myrepublic jakarta

**Comment by wijaksanapanji** [comment]
Try access it from [duckduckgo.com](https://duckduckgo.com)
open [duckduckgo.com](https://duckduckgo.com) then search 1337x.to then open it.
after that you can open it normaly.

if it still doesn't work, you can try other alternative domain [1337x.gd](https://1337x.gd)
