### ISSUE TITLE
[REQ] investing.com

### ISSUE THREAD

**Issue by rizkireynaldi** [bebasid/bebasid#122]
Request tolong buka investing.com

Terima kasih.

**Comment by nxzlem** [comment]
halo, kak
situs investing.com sudah ditambahkan dari minggu lalu.
![chrome_SUvSeAPntl](https://user-images.githubusercontent.com/30078972/82514217-5afd0e00-9b3f-11ea-93c0-6a5de2f448ac.png)
berarti kakak belum re-install bebasid gara2 belum di update hostsnya. coba re-install lagi ya kakak.
terima kasih.
