### ISSUE TITLE
[BUG] gelbooru.com

### ISSUE THREAD

**Issue by arjuna17jax** [bebasid/bebasid#129]
**Deskripsi mengenai bug**
Loading gambar lama dan sering gagal dan download gambar sering error.

**Screenshot**
![image](https://user-images.githubusercontent.com/48570369/82724394-0654c100-9d00-11ea-9e90-e64209e14e85.png)

**Device**
 - OS: Windows 10
 - Browser: Firefox

**Comment by arjuna17jax** [comment]
Masih sama. Apakah perlu edit file host secara manual?
![Screenshot_2020-05-26  Gelbooru - Free Anime and Hentai Gallery](https://user-images.githubusercontent.com/48570369/82861980-9c7b2800-9f48-11ea-99db-b5d2deceeed0.png)

**Comment by nxzlem** [comment]
kak, sudah re-install bebasid belum atau update di bebasin?

**Comment by nxzlem** [comment]
kak kayanya sudah di tambahkan subdomain oleh author lain
![chrome_r7RvXdoBlt](https://user-images.githubusercontent.com/30078972/82975481-cb57d380-a006-11ea-9165-fd62ae455474.png)
