### ISSUE TITLE
[BUG] hanime.tv

### ISSUE THREAD

**Issue by arjuna17jax** [bebasid/bebasid#130]
**Deskripsi mengenai bug**
Loading konten website lama

**Device**
 - OS:  10
 - Browser: Firefox

**Comment by nxzlem** [comment]
halo, hanime.tv.
situs [fapforfun.net] sudah digantikan subdomain ip yg lama ke baru ya kak.
skrg, kalau mau re-install bebasid, ini khusus untuk windows ya ada disini tutorialnya:

1. Buka program "bebasid.bat". (kalau gk ada bebasid.bat, download dlu dari "bebasid.github.io")
2. Pilih default host "ketik (W) terus enter" (Tunggu sampai Installnya selesai).
3. Buka program "bebasid.bat" lagi.
4. Pilih Installin bebasid "ketik (Y) terus enter" (Tunggu sampai installnya selesai).
kalau ada namanya installasi bebasid selesai, hit/pencet "enter" di keyboardmu.
selesai dah.

kalau anda memakai bebasin ini tutorialnya:
1. Bukakan bebasin.exe dengan Administrasi.
![yPC500Bu4j](https://user-images.githubusercontent.com/30078972/82976369-1672e600-a009-11ea-9b2e-dd9b182713ec.png)
2. Pilih "Update" (Tombol Bawah Arrow di dekat keypad keyboardmu, Trus Tombol "Enter").
![bebasin_8uanksAOjD](https://user-images.githubusercontent.com/30078972/82976498-736e9c00-a009-11ea-80fd-36add033d451.png)
3. Kalau ada update pilih "Yes" (Tombolkan Kanan Arrow di Keyboardmu dan Tombol "Enter").
![bebasin_fOkB52AmpZ](https://user-images.githubusercontent.com/30078972/82976563-9d27c300-a009-11ea-817f-a33fc0509b02.png)
4. Anda Tombol "Enter" dan Selesai dah!
![bebasin_KVHuBDZxBs](https://user-images.githubusercontent.com/30078972/82976606-bb8dbe80-a009-11ea-96a6-0ef8241af9aa.png)
Sekarang coba buka situs lagi, kalau bisa atau tidak.
terima kasih untuk melaporkan bug situs anda.
-NXzLEM
