### ISSUE TITLE
[REQ] rockstargames.com

### ISSUE THREAD

**Issue by narrundo** [bebasid/bebasid#131]
socialclub.rockstargames.com
rockstargames.com
gamedownloads.rockstargames.com
gamedownloads-rockstargames-com.akamaized.net
a.rsg.sc

**Comment by gvoze32** [comment]
@nxzlem 
@narrundo 

rockstargames diblok apa gmn gan?

**Comment by dikiaap** [comment]
Kenapa ditambahkan ke daftar? `socialclub.rockstargames.com` dan
`rockstargames.com` masih bisa saya akses. CDN-nya juga.

**Comment by dikiaap** [comment]
Saya baru liat komitnya dan banyak juga yang ditambahin. Kebanyakan masih bisa diakses. Saya nslookup dan IP-nya juga sama.

**Comment by gvoze32** [comment]
Coba dilist aja nanti saya bantu revert

**Comment by narrundo** [comment]
> @nxzlem
> @narrundo
> 
> rockstargames diblok apa gmn gan?

mohon maaf sebelumnya gan kalau situsnya masih bisa diakses sama yang lain.
saya udah seminggu ga bisa akses rockstargames dan kesulitan login dari launcher.
saya coba test pakai vpn baru bisa normal jadi saya pikir mungkin keblok, sudah saya coba berulang-ulang sebelum buat request.

**Comment by nxzlem** [comment]
berarti ada yg masalah dengan proksi/koneksinya

**Comment by nxzlem** [comment]
> > @nxzlem
> > @narrundo
> > rockstargames diblok apa gmn gan?
> 
> mohon maaf sebelumnya gan kalau situsnya masih bisa diakses sama yang lain.
> saya udah seminggu ga bisa akses rockstargames dan kesulitan login dari launcher.
> saya coba test pakai vpn baru bisa normal jadi saya pikir mungkin keblok, sudah saya coba berulang-ulang sebelum buat request.

ydh kak coba re-install bebasid ya atau update di bebasin

**Comment by dikiaap** [comment]
Kayaknya harus dibuat peraturan jika layanan masih bisa diakses oleh member bebasid (lewat ISP Indonesia), maka perequest harus menyertakan output log seperti di nslookup, ping, dig, atau yang lainnya. Entah yang tidak bisa diakses itu kalau hanya kendala jaringan dan dibatasi oleh pemilik Wi-Fi.

**Comment by nxzlem** [comment]
Iya, anda maap izin close issue ya. terima kasih

**Comment by icaksh** [comment]
@narrundo apakah di laptop dahulu terpasang goodbyedpi ?

**Comment by gvoze32** [comment]
mungkin service remove goodbyedpi bisa membantu
