### ISSUE TITLE
[BUG] gelbooru.com

### ISSUE THREAD

**Issue by NoiseBox20** [bebasid/bebasid#132]
Gelbooru.com tembus aman, cuman gabisa load gambar sama sekali, sempet bisa tapi cuman satu gambar di refresh lagi gini lagi. Di Windows mah aman, hanya di linux begini. utak-atik network manager cuman untuk DNS. Nah, tapi oper ke vpn bisa load gambar.

![Screenshot_20200524_125142](https://user-images.githubusercontent.com/65381461/82747952-294aa800-9dc8-11ea-9b62-1e802de10ea0.png)
![Screenshot_20200524_141057](https://user-images.githubusercontent.com/65381461/82747980-6dd64380-9dc8-11ea-8689-51a8bebf542b.png)

**Device**
 - OS: Manjaro Linux
 - Browser: Brave dan Firefox

**Comment by nauj42** [comment]
hostnya udah diupdate lagi yah, kalo masih gak bisa komen aja lagi

**Comment by NoiseBox20** [comment]
@nauj42 sudah bisa, terimakasih.
