### ISSUE TITLE
[Ask] Host file url resources utk AdAway android

### ISSUE THREAD

**Issue by Miellenials** [bebasid/bebasid#134]
Halo bebasid dev,
Sebelumnya terimakasih sdh develop bebasid, sangat memuaskan di pc / windows..
Sekarang sy mau coba di android, tetapi karna sy pake adaway plugin, yg selalu mengupdate hosts scr otomatis jd sy gabisa manual edit hosts filenya..

Tp di adaway engine ada fitur utk adding sources hosts file (bentuknya url), kira2 bebasid bisa share hosts url repo ny? Biar sy coba apakah works dgn adaway engine..

Terimakasih sebelumnya

**Comment by nxzlem** [comment]
Anda sudah diroot hpnya?

**Comment by Miellenials** [comment]
Hp sy sdh di root

**Comment by Miellenials** [comment]
Apakah bebasid mempunyai url repo dmn developer mengupload hosts.txtnya? Utk scr otomatis ke update di bebasin.exe yg di pc?
Btw, setau sy yg di pc hosts filenya autoupdate kan? Cmiiw

**Comment by icaksh** [comment]
udah coba https://raw.githubusercontent.com/bebasid/bebasid/master/releases/hosts ?

**Comment by nxzlem** [comment]
apakah sudah ni komennya?

**Comment by nauj42** [comment]
langsung aja copy url raw hostnya. sama aja kok

**Comment by Miellenials** [comment]
Sorry gan late reply,
Sudah sy coba, dan berhasil add url raw hostsnya, dan terdetect last update
![IMG-20200530-WA0000](https://user-images.githubusercontent.com/65380422/83305129-611f7880-a22a-11ea-875a-e53e1356df3a.jpg)

Tapi tetap gagal utk buka, contoh dsini reddit
`
![IMG-20200530-WA0001](https://user-images.githubusercontent.com/65380422/83305116-5c5ac480-a22a-11ea-9985-bfce455c52b8.jpg)
`

**Comment by Miellenials** [comment]
Sy coba matikan srmuaa sources selain bebasid, dan ternyata hostsnya ga ketarik..
![IMG-20200530-WA0002](https://user-images.githubusercontent.com/65380422/83307233-74ccde00-a22e-11ea-821c-c286b7104f57.jpg)

**Comment by gvoze32** [comment]
mungkin harus ngikutin formatnya adawaynya dulu ya

**Comment by icaksh** [comment]
@Miellenials adaway bisa respons ke script php gak? kebetulan saya ada script untuk fix hosts bebasid cuma karena bisanya satu domain satu line jadinya terbengkalai

**Comment by gvoze32** [comment]
iya nih, manual capek kalo ngikutin formatnya satu domain satu line, hmm

**Comment by icaksh** [comment]
@Miellenials coba pakai ini
https://bebasid.herokuapp.com/hosts

Sudah sesuai format 1 domain 1 line
Update setiap jam 12 malam..

Thanks

**Comment by gvoze32** [comment]
kok not found yah

**Comment by icaksh** [comment]
@gvoze32 kayaknya herokuapp ga support wkwkwk alias langsung ngehapus filenya

https://bebasid.herokuapp.com/bebasid-adaway.php nanti baru dapet hostsnya

Sourcenya juga udah ada di github

**Comment by Nuginity** [comment]
itu formatnya harus txt

**Comment by Nuginity** [comment]
@Miellenials coba ini:

https://raw.githubusercontent.com/Nuginity/bebasid/master/host.txt

**Comment by strkdv** [comment]
Coba ini gan pasang di addaway: https://strkdv.github.io/bebasidadaway/hosts.txt

**Comment by Mystery77** [comment]
oke gan thanks semua respondnya, saya coba 1 1 dari @Nuginity @strkdv @icaksh , nanti sy laporan lagi yg works mana..

sorry late reply jarang buka github

**Comment by Mystery77** [comment]
https://forum.xda-developers.com/showthread.php?t=2190753

btw ini link adawaynya yg official dr xda

**Comment by Nuginity** [comment]
https://raw.githubusercontent.com/Nuginity/bebasid/master/bebasid-adaway

coba deh pake yang itu, ane buat dari source code bebasid sama adaway

**Comment by gembulzzzz** [comment]
https://github.com/AdAway/AdAway/wiki/HostsSources
Someone raised issue on adaway that his local host provider, cant br added to host sources, please kindly tell and help him so host sources follow as link above

Ps: is it the correct thread? Bcs i cant speak bahasa

**Comment by nxzlem** [comment]
@Miellenials tolong kak jangan lama nugguin respon ini akan di tutup komennya

**Comment by Miellenials** [comment]
@nxzlem close aja dah gan, sy coba semua yg disarankan jg gabisa.. udh sy raise issue di dev app nya jg merekanya gabisa bantu, katanya gasesuai format.. thanks semua yg udh coba bntu

**Comment by nxzlem** [comment]
Oke, terima kasih infonya. Akan tutup komennya.
