### ISSUE TITLE
[REQ] https://wallpaperhub.app

### ISSUE THREAD

**Issue by Amidst-eng** [bebasid/bebasid#135]
tolong tambahkan https://wallpaperhub.app. terima kasih

**Comment by PKinfairs** [comment]
bisa kebuka kok

![image](https://user-images.githubusercontent.com/18479920/83244337-64364c80-a1c9-11ea-8356-99ed45c654e7.png)
![image](https://user-images.githubusercontent.com/18479920/83244307-5bde1180-a1c9-11ea-9c71-ff3ae824831c.png)

**Comment by gvoze32** [comment]
Jaringan tri bisa terbuka
