### ISSUE TITLE
[REQ] isekaiscan.com

### ISSUE THREAD

**Issue by danzhuroid** [bebasid/bebasid#137]
REQ isekaiscan gak bisa kebuka terus

**Comment by nxzlem** [comment]
iya kak, ga ada cuma block positif, itu forbidden gara2 gak bisa akses buat smua.
![chrome_jwphaeTLeQ](https://user-images.githubusercontent.com/30078972/83343463-bdff5980-a324-11ea-8620-42570ef40041.png)
![chrome_8xx72vVrXh](https://user-images.githubusercontent.com/30078972/83343468-d2dbed00-a324-11ea-917a-de2e6cd975fd.png)

**Comment by Nuginity** [comment]
websitenya mati ngga bisa di akses, problem sama owner servernya
