### ISSUE TITLE
[BUG] Reddit Upvote dan Thread Comments

### ISSUE THREAD

**Issue by FRDS** [bebasid/bebasid#138]
**Deskripsi mengenai bug**
Tidak bisa _upvote_ dan akses komentar di _thread_ Reddit. Ketika tombol _upvote_ diklik, dia akan kembali seperti semula jadi _upvote_ tidak dihitung. Lalu, bagian komentar selalu gagal diakses, dengan munculnya tombol _retry_ setiap membuka _thread._ 

**Screenshot**
![image](https://user-images.githubusercontent.com/17400640/83349217-50235400-a35d-11ea-8088-61b936edaad3.png)

**Device**
 - OS: Microsoft Windows 10
 - Browser: Google Chrome

**Comment by Nuginity** [comment]
no issue buat reddit
kernel : 4.15.0-51-generic
OS : Linux Mint 19.1

**Comment by nxzlem** [comment]
coba anda refresh situs reddit lagi

**Comment by FRDS** [comment]
> coba anda refresh situs reddit lagi

Sudah. Masih terjadi. Sebelum ini, saya akses Reddit pakai VPN dan normal. Hanya ketika mulai pakai hosts bebasin mulai begini.

**Comment by nxzlem** [comment]
apakah sudah di defaultkan hosts, situ di installin bebasid lagi?

**Comment by nxzlem** [comment]
tolong respon kak kalau ga ini di tutup issuenya

**Comment by FRDS** [comment]
> apakah sudah di defaultkan hosts situ installin bebasid lagi?

Sudah diupdate, sudah direstart. Masih terjadi.

**Comment by Nuginity** [comment]
Tambahin ini coba ke file hosts kamu

[#upvote & comment reddit]
151.101.65.140 oauth.reddit.com

**Comment by FRDS** [comment]
> Tambahin ini coba ke file hosts kamu
> 
> #[upvote & comment reddit]
> 151.101.65.140 oauth.reddit.com
> 
> `pastiin sesudah di pasang restart browser kamu`

_Upvote_ sudah bisa tapi komentar masih harus _reload_ link thread biar muncul. Tidak muncul ketika membuka thread dari _front page_. Tapi ini sudah lumayan cukup.

**Comment by Nuginity** [comment]
dicoba lagi ini :

#[reddit.com comment section]
151.101.65.140 www.redditstatic.com redditstatic.com
151.101.65.140 styles.reddit.com
151.101.65.140 gateway.reddit.com

**Comment by FRDS** [comment]
Maaf lama balasnya. Sepertinya sekarang sudah bisa semua. 🤗
