### ISSUE TITLE
Uninstall Power Tunnel & Green Tunnel

### ISSUE THREAD

**Issue by yosefyudha** [bebasid/bebasid#143]
**Deskripsi mengenai bug**
Saya tidak menemukan instruksi untuk menghapus/uninstall aplikasi Power Tunnel dan Green Tunnel yang diinstall melalui terminal.
command: `bebasid app uninstall` sepertinya untuk menghapus aplikasi bebasid. Padahal saya hendak menghapus aplikasi green tunnel dan power tunnel

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.

**Device**
 - OS: macOS 10.15.5
 - Browser chrome & safari

**Comment by icaksh** [comment]
saat ini sedang dalam pengembangan untuk versi selanjutnya
