### ISSUE TITLE
[BUG] Shopeepaylater di App Shopee Android

### ISSUE THREAD

**Issue by arjuna17jax** [bebasid/bebasid#144]
**Deskripsi mengenai bug**
Laman untuk shopeepaylater pada aplikasi shopee android tidak bisa diakses. Fitur-fitur lain pada aplikasi masih berfungsi normal. Sudah saya hubungi customer service shopee, setelah 5 hari belum bisa menangani. Jadi saya minta tolong cek apakah kendalanya karena pakai host bebasid.

**Screenshot**
![Screenshot_2020-06-01-02-03-50](https://user-images.githubusercontent.com/48570369/83566658-912c8b80-a54a-11ea-89a3-fc18cb644f75.png)

**Device**
 - OS: Android Lollipop
 - Browser Aplikasi shopee

**Comment by Nuginity** [comment]
di bebasid ngga nyentuh apapun dengan domain shopee

**Comment by nxzlem** [comment]
1. anda sudah di root?
2. anda sudah di cek restart hp dan matiin data seluler/wifi trus di nyalain lg?
3. apa yg masalah dengan shopeepaylater?

**Comment by arjuna17jax** [comment]
1. sudah root
2. Sudah
3. Sudah
4. Baru kali ini ada masalah begini

**Comment by nxzlem** [comment]
berarti kuota nya ada yg masalah dengan shopee, coba pakai wifi.

**Comment by andraantariksa** [comment]
Hosts Bebasid nggak nyentuh domain/IP Shopee sama sekali. Coba pakai VPN/DNS lain.

**Comment by nxzlem** [comment]
@arjuna17jax masi bisa gak? ini mau close komennya gara2 bebasid tidak nyetuh domain ip shopee

**Comment by icaksh** [comment]
ShopeePayLater tidak diblokir sehingga bebasid tidak mempointing domain dari shopee
