### ISSUE TITLE
[BUG] https://redgifs.com

### ISSUE THREAD

**Issue by trusta77** [bebasid/bebasid#146]
Gifs masih belum bisa di load/play. Media lain kaya thumbnail/gambar etc. masih ga bisa di load. 
![image](https://user-images.githubusercontent.com/40566453/83720165-c3311100-a662-11ea-80ca-a1276c92eaaa.png)
![image](https://user-images.githubusercontent.com/40566453/83720153-b90f1280-a662-11ea-86e3-b1ffac9907d0.png)

**Comment by Nuginity** [comment]
dicoba ini ya :

#  [redgifs.com]
107.23.151.94 redgifs.com
198.134.29.39 thcf1.redgifs.com
198.134.29.37 thcf2.redgifs.com
198.134.29.42 thcf3.redgifs.com
198.134.29.41 thcf4.redgifs.com
198.134.29.36 thcf5.redgfis.com
198.134.29.45  thcf6.redgifs.com
198.134.29.46 thcf7.redgifs.com
198.134.29.47 thcf8.redgifs.com
198.134.29.48 thcf9.redgifs.com

**Comment by Nuginity** [comment]
coba gan:
#  [redgifs.com]
52.6.45.99 redgifs.com
13.224.13.40 thcf1.redgifs.com
198.134.29.37 thcf2.redgifs.com
198.134.29.42 thcf3.redgifs.com
198.134.29.41 thcf4.redgifs.com
198.134.29.36 thcf5.redgfis.com
198.134.29.45  thcf6.redgifs.com
198.134.29.46 thcf7.redgifs.com
198.134.29.47 thcf8.redgifs.com
198.134.29.48 thcf9.redgifs.com
3.91.164.2 napi.redgifs.com

**Comment by nxzlem** [comment]
emg kakak pake operasi sistem apa?

**Comment by trusta77** [comment]
Windows 10

**Comment by nxzlem** [comment]
berarti kakak pake bebasid atau bebasin?

**Comment by trusta77** [comment]
Bebasin. Barusan bisa di update dan di install tapi malah "redirected you too many times." 
![image](https://user-images.githubusercontent.com/40566453/83891429-56f40180-a777-11ea-8dac-22b41a5ae86c.png)

**Comment by nxzlem** [comment]
coba kakak update bebasin dulu trus buka situs lagi

**Comment by trusta77** [comment]
![image](https://user-images.githubusercontent.com/40566453/83891694-c7028780-a777-11ea-8323-767743680d4c.png)

Udah diupdate min, tapi masih gitu, sebelumnya malah masih bisa dibuka
![image](https://user-images.githubusercontent.com/40566453/83892165-74759b00-a778-11ea-86ae-d79fdfed75e7.png)

**Comment by hozzaq** [comment]
buka subdomain nya bisa tapi kalo link nya redgifs aja redirect loop

**Comment by nxzlem** [comment]
![chrome_BrtK1POeWl](https://user-images.githubusercontent.com/30078972/83945499-40ac7b00-a835-11ea-9d25-07002f90ca45.png)
saya gak ada masalah loh yang redgifs.com sama subdomainnya.

**Comment by nxzlem** [comment]
kakak tolong respon, apakah sudah bisa nih?

**Comment by trusta77** [comment]
Masih redirect min, udah ane update barusan, tapi masih sama aja. 

****
![image](https://user-images.githubusercontent.com/40566453/83987873-ccc0be80-a96b-11ea-8151-301c95fe39aa.png)

**Comment by andraantariksa** [comment]
Silahkan buka file di `C:\Windows\System32\drivers\etc\hosts` dengan notepad, copy dan kirimkan disini

**Comment by nxzlem** [comment]
coba pake browser lain, maksudnya brave browser, chrome atau firefox

**Comment by sekti92** [comment]
ane pake ini jalan 
```
# [redgifs.com]
99.86.230.34 www.redgifs.com
52.54.99.135 thumbs.redgifs.com
54.210.249.247 api.redgifs.com
52.55.75.178 fat.redgifs.com
52.6.45.99 redgifs.com
13.224.13.40 thcf1.redgifs.com
198.134.29.37 thcf2.redgifs.com
198.134.29.42 thcf3.redgifs.com
198.134.29.41 thcf4.redgifs.com
198.134.29.36 thcf5.redgfis.com
198.134.29.45 thcf6.redgifs.com
198.134.29.46 thcf7.redgifs.com
198.134.29.47 thcf8.redgifs.com
198.134.29.48 thcf9.redgifs.com
3.91.164.2 napi.redgifs.com
```

**Comment by hozzaq** [comment]
> ane pake ini jalan
> 
> ```
> # [redgifs.com]
> 99.86.230.34 www.redgifs.com
> 52.54.99.135 thumbs.redgifs.com
> 54.210.249.247 api.redgifs.com
> 52.55.75.178 fat.redgifs.com
> 52.6.45.99 redgifs.com
> 13.224.13.40 thcf1.redgifs.com
> 198.134.29.37 thcf2.redgifs.com
> 198.134.29.42 thcf3.redgifs.com
> 198.134.29.41 thcf4.redgifs.com
> 198.134.29.36 thcf5.redgfis.com
> 198.134.29.45 thcf6.redgifs.com
> 198.134.29.46 thcf7.redgifs.com
> 198.134.29.47 thcf8.redgifs.com
> 198.134.29.48 thcf9.redgifs.com
> 3.91.164.2 napi.redgifs.com
> ```
> 
> tapi beberapa video masih ada yang ngga jalan

ini yg lama kan, pake ini malah ke block telkomsel

**Comment by trusta77** [comment]
> Silahkan buka file di `C:\Windows\System32\drivers\etc\hosts` dengan notepad, copy dan kirimkan disini

gini gan? 
198.134.29.46 thcf7.redgifs.com
198.134.29.45 thcf6.redgifs.com
52.55.75.178 fat.redgifs.com
198.134.29.37 thcf2.redgifs.com
198.134.29.48 thcf9.redgifs.com
54.210.249.247 api.redgifs.com
198.134.29.42 thcf3.redgifs.com
52.6.45.99 redgifs.com www.redgifs.com
52.54.99.135 thumbs.redgifs.com
3.91.164.2 napi.redgifs.com
198.134.29.41 thcf4.redgifs.com
13.224.13.40 thcf1.redgifs.com
198.134.29.47 thcf8.redgifs.com

**Comment by sekti92** [comment]
> > ane pake ini jalan
> > ```
> > # [redgifs.com]
> > 99.86.230.34 www.redgifs.com
> > 52.54.99.135 thumbs.redgifs.com
> > 54.210.249.247 api.redgifs.com
> > 52.55.75.178 fat.redgifs.com
> > 52.6.45.99 redgifs.com
> > 13.224.13.40 thcf1.redgifs.com
> > 198.134.29.37 thcf2.redgifs.com
> > 198.134.29.42 thcf3.redgifs.com
> > 198.134.29.41 thcf4.redgifs.com
> > 198.134.29.36 thcf5.redgfis.com
> > 198.134.29.45 thcf6.redgifs.com
> > 198.134.29.46 thcf7.redgifs.com
> > 198.134.29.47 thcf8.redgifs.com
> > 198.134.29.48 thcf9.redgifs.com
> > 3.91.164.2 napi.redgifs.com
> > ```
> > 
> > 
> > tapi beberapa video masih ada yang ngga jalan
> 
> ini yg lama kan, pake ini malah ke block telkomsel

ane pake itu 2 bulanan, klo telkomsel kaga tau dah ane gan, ane pake di PC itu

**Comment by andraantariksa** [comment]
> > Silahkan buka file di `C:\Windows\System32\drivers\etc\hosts` dengan notepad, copy dan kirimkan disini
> 
> gini gan?
> 
> > 
> 
> 198.134.29.46 thcf7.redgifs.com
> 198.134.29.45 thcf6.redgifs.com
> 52.55.75.178 fat.redgifs.com
> 198.134.29.37 thcf2.redgifs.com
> 198.134.29.48 thcf9.redgifs.com
> 54.210.249.247 api.redgifs.com
> 198.134.29.42 thcf3.redgifs.com
> 52.6.45.99 redgifs.com [www.redgifs.com](http://www.redgifs.com)
> 52.54.99.135 thumbs.redgifs.com
> 3.91.164.2 napi.redgifs.com
> 198.134.29.41 thcf4.redgifs.com
> 13.224.13.40 thcf1.redgifs.com
> 198.134.29.47 thcf8.redgifs.com

Domain thcf5.redgifs.com sama api.redgifs.com kok nggak ada?

**Comment by trusta77** [comment]
api.redgifs.com nya ada gan, thfcf5 nya emang ga ada,
ga tau gan kok ada yang kurang, ane install nya lewat bebasin ga pernah nambahin/ngurangin manual.

**Comment by trusta77** [comment]
Ahh, masalahnya di `52.6.45.99 redgifs.com www.redgifs.com` 
kalo diubah jadi `52.6.45.99 redgifs.com` bisa jalan

**Comment by nxzlem** [comment]
sudah kak coba replace lagi
# [redgifs.com]
52.6.45.99 redgifs.com
13.249.44.82 www.redgifs.com
52.54.99.135 thumbs.redgifs.com
54.210.249.247 api.redgifs.com napi.redgifs.com
52.55.75.178 fat.redgifs.com
198.134.29.39 thcf1.redgifs.com
198.134.29.37 thcf2.redgifs.com
198.134.29.42 thcf3.redgifs.com
198.134.29.41 thcf4.redgifs.com
198.134.29.36 thcf5.redgifs.com
198.134.29.45 thcf6.redgifs.com
198.134.29.46 thcf7.redgifs.com
198.134.29.47 thcf8.redgifs.com
198.134.29.48 thcf9.redgifs.com

**Comment by hozzaq** [comment]
> sudah kak coba replace lagi
> 
> # [redgifs.com]
> 52.6.45.99 redgifs.com
> 13.249.44.82 [www.redgifs.com](http://www.redgifs.com)
> 52.54.99.135 thumbs.redgifs.com
> 54.210.249.247 api.redgifs.com napi.redgifs.com
> 52.55.75.178 fat.redgifs.com
> 198.134.29.39 thcf1.redgifs.com
> 198.134.29.37 thcf2.redgifs.com
> 198.134.29.42 thcf3.redgifs.com
> 198.134.29.41 thcf4.redgifs.com
> 198.134.29.36 thcf5.redgifs.com
> 198.134.29.45 thcf6.redgifs.com
> 198.134.29.46 thcf7.redgifs.com
> 198.134.29.47 thcf8.redgifs.com
> 198.134.29.48 thcf9.redgifs.com

nah ini bisa mantap

**Comment by nxzlem** [comment]
@trusta77 tolong jangan lupa direplacekan redgifs.com ya

**Comment by trusta77** [comment]
@nxzlem Ok makasih banyak min, so far ga ada masalah. 
Saya close ya.
