### ISSUE TITLE
[BUG] Gak work di Windows 10 versi 2004 (Mei Update)

### ISSUE THREAD

**Issue by tamacroft** [bebasid/bebasid#147]
Bro, gak work nih di windows 10 versi 2004, buat nonton netflix g bisa, sebelumnya bisa sih di windows versi 1909

**Comment by nxzlem** [comment]
halo kak/tamacroft, 
programnya pake bebasid (CLI) atau bebasin (TUI)?
kalau kakak di bebasin buka program dan tombol update
                    di bebasid mengdefaultkan hosts dlu, buka bebasid dan install hosts lagi.

**Comment by tamacroft** [comment]
ini ga bisa buat netflix, bebasid maupun bebasin sama aja
[https://photos.app.goo.gl/jqSUTRGiyWvePoEPA](url)

**Comment by nxzlem** [comment]
kakak coba re-install goodbyedpi atau bebasit (powertunnel method)

**Comment by nxzlem** [comment]
@tamacroft tolong respon ya jangan lama, terima kasih.

**Comment by icaksh** [comment]
dalam ss tidak ditemukan adanya aplikasi penembus dpi yang jalan (goodbyedpi, powertunnel), silakan menuju [Tutorial menembus Netflix](https://github.com/bebasid/bebasid/blob/master/dev/readme/NETFLIX.md)
