### ISSUE TITLE
[REQ] exoticaz.to

### ISSUE THREAD

**Issue by iCesenberk** [bebasid/bebasid#150]
exoticaz.to

**Comment by nxzlem** [comment]
Gak ada masalah dengan situs [exotiacs.to] kak. Situsnya tidak ada diblockir oleh trustpositif/kominfo.
![chrome_mK2cj8VBe6](https://user-images.githubusercontent.com/30078972/84099965-0ad5e500-aa35-11ea-9134-e0b97322ec3a.png)
![chrome_VO8piwaVdq](https://user-images.githubusercontent.com/30078972/84099978-12958980-aa35-11ea-8d54-9e2a348d78d4.png)
