### ISSUE TITLE
[BUG] sukebei.nyaa.si

### ISSUE THREAD

**Issue by frank77777** [bebasid/bebasid#152]
**Deskripsi mengenai bug**
Firefox can’t establish a connection to the server at sukebei.nyaa.si. (indihome)

**Device**
 - OS: Windows 10
 - Browser Firefox

**Comment by nxzlem** [comment]
halo kak,
situs sukebei.nyaa.si sudah di tambahkan, tapi saya di gantikan ip yg ke baru.
apakah kakak sudah di re-install bebasid/update bebasin? (karena kakak belum pernah re-install bebasid/update bebasin)

**Comment by frank77777** [comment]
> 
> 
> halo kak,
> situs sukebei.nyaa.si sudah di tambahkan, tapi saya di gantikan ip yg ke baru.
> apakah kakak sudah di re-install bebasid/update bebasin? (karena kakak belum pernah re-install bebasid/update bebasin)
> gambar yg sudah bisa :
> ![chrome_ILmRtqNEDU](https://user-images.githubusercontent.com/30078972/84140227-79d62c80-aa7b-11ea-91c5-e930c47ddcd8.png)

oke sudah bisa sekarang, thx
