### ISSUE TITLE
[REQ] fapservice.com

### ISSUE THREAD

**Issue by arjuna17jax** [bebasid/bebasid#155]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts

**Comment by nxzlem** [comment]
Sudah cek [fapservice.com], tapi ada situs forbidden kak, error 403. Terus Kominfonya sudah di block. Saya sudah cek pake VPN tapi masih forbidden.
Screenshots:
![chrome_WGHGZgUiSO](https://user-images.githubusercontent.com/30078972/84803836-ad412a00-b02c-11ea-8ea6-62c511ee9d71.png)
![chrome_fK6IPoiYs1](https://user-images.githubusercontent.com/30078972/84804325-d661ba80-b02c-11ea-95b1-32504807de8c.png)
![chrome_2mete6UjER](https://user-images.githubusercontent.com/30078972/84804372-dfeb2280-b02c-11ea-9159-c6e18deff7dc.png)
