### ISSUE TITLE
[REQ] Buat versi android/termux dong gan

### ISSUE THREAD

**Issue by KANG-NEWBIE** [bebasid/bebasid#158]
Buat versi untuk android atau paling tidak bisa jalan di terminal android macem termux gitu gan hehe...

**Comment by andraantariksa** [comment]
Kalau di Android harus diroot dulu. Kalu nggak ya harus dinyalain kaya VPN gitu.

Ditampung dulu sarannya, nanti saya coba bikin

**Comment by Ruaawr** [comment]
Cobain pake Hosts Go gan
Tinggal import file hosts nya ke Hosts Go terus nyalain VPN nya

**Comment by nxzlem** [comment]
Komen anda inaktif maka harus di tutup komen, maaf atas andanya terima kasih atas infonya.

**Comment by icaksh** [comment]
Termux bisa memakai versi Linux dengan syarat Android harus dalam kondisi rooted

Jika ingin menggunakan Hosts Go, bisa menggunakan url https://raw.githubusercontent.com/bebasid/bebasid/master/dev/resources/hosts.android

Thanks

**Comment by andraantariksa** [comment]
Bebasin sebenernya bisa jalan di termux, tinggal diport aja

**Comment by nxzlem** [comment]
kakak coba nih kalo mau edit hosts tanpa pake apk (butuh root)
1. nonton video ini dulu https://www.youtube.com/watch?v=NM4C-Qfgmwg - How to change file permission in android
2. habis sudah dinontonkan kakak ke lokasi folder /system/etc/hosts dlu
3. kakak buka hosts file dengan edit program atau third party edit program
4. salin bebasid hosts dan tempelkan ke edit hosts file
5. terus langsung save dan jangan lupa restart hpnya
kalo kakak mau apk dengan root silahkan baca di sini ya
https://github.com/bebasid/bebasid/blob/master/dev/readme/USAGE.md
terima kasih
