### ISSUE TITLE
[REQ] Hosts sebaiknya tidak ditimpa tapi di tambahkan

### ISSUE THREAD

**Issue by xdn27** [bebasid/bebasid#16]
**Deskripsi mengenai bug**
Hosts tertimpa saat install / update, sebaiknya host ditambahkan baik secara baris baru atau file external (saya kurang tau bisa apa enggak).
Ini efek ke saya yang pake hosts untuk development sih, agak kaget ternyata hostnya ditimpa

**Device**
 - OS: Ubuntu 19.10

**Comment by icaksh** [comment]
Request tersebut akan kami tambahkan secepatnya

Untuk masalah hosts asli yang mungkin telah disimpan untuk proses development yang dikatakan telah tertimpa, masih tersimpan di file hosts.bak-bebasid (/etc/hosts.bak-bebasid)

Terima kasih

**Comment by gvoze32** [comment]
Oke, ditampung untuk versi windows

**Comment by icaksh** [comment]
> **Deskripsi mengenai bug**
> Hosts tertimpa saat install / update, sebaiknya host ditambahkan baik secara baris baru atau file external (saya kurang tau bisa apa enggak).
> Ini efek ke saya yang pake hosts untuk development sih, agak kaget ternyata hostnya ditimpa
> 
> **Device**
> 
> * OS: Ubuntu 19.10

untuk Linux sudah diupdate
silahkan uninstall bebasid anda terlebih dahulu lalu renew aplikasi bebasid

> 

`bebasid uninstall`
`bebasid renew`

untuk menginstall hosts bebasid kembali, gunakan

`bebasid install`

Thanks

**Comment by xdn27** [comment]
Ada error kayaknya, setelah melakukan update, hostsnya gak terpasang

`
bebasid uninstall
bebasid renew
bebasid install
`

Setelah di install ulang juga masih gak kepasang hostsnya

**Comment by icaksh** [comment]
> Ada error kayaknya, setelah melakukan update, hostsnya gak terpasang
> 
> `bebasid uninstall`
> `bebasid renew`
> `bebasid install`
> 
> Setelah di install ulang juga masih gak kepasang hostsnya

Karena ada restruktur, maka link awalnya menjadi 404 Not Found

Remove Aplikasi BEBASID terlebih dahulu

`bebasid remove`

Lalu pasang kembali

`sudo wget https://raw.githubusercontent.com/bebasid/bebasid/master/releases/bebasid.sh -O /usr/local/bin/bebasid`

Lalu tinggal install hostsnya

`bebasid install`
