### ISSUE TITLE
[BUG] bug xvid***

### ISSUE THREAD

**Issue by HayleyHigh** [bebasid/bebasid#160]
**Deskripsi mengenai bug**
xvid*** mengalami bug loop loading dan gambar tidak muncul.

**Device**
 - OS: [Windows 10]
 - Browser [Chrome]

**Comment by nxzlem** [comment]
terima kasih kak, sudah di gantikan ip baru sama ditambahin banyak ip subdomain baru. jangan lupa di update hosts ya. terima kasih!
