### ISSUE TITLE
[REQ] isekaiscan.com dan allporncomic.com

### ISSUE THREAD

**Issue by Miellenials** [bebasid/bebasid#161]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts
Saya adding manual di android berdasarkan sources ini,

https://raw.githubusercontent.com/bebasid/bebasid/master/releases/hosts

https://raw.githubusercontent.com/Nuginity/bebasid/master/bebasid-adaway

**Comment by nxzlem** [comment]
terima kasih kak, sudah ditambahin situs kak. jangan lupa update hosts ya. terima kasih.
