### ISSUE TITLE
[REQ] SITUS BARU

### ISSUE THREAD

**Issue by harumembiru** [bebasid/bebasid#162]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts

https://javhdporn.net/
https://www.thisav.com
https://vs18.thisav.com
https://javpedia.org/
https://www.bitporno.com/
https://javpool.com/
https://warungjav.cc/
http://javxxxvideos.com/
https://javtiful.com/
https://www.javmec.com/
https://javsun.net/
https://tubeqd.tv/
https://watchjav.info/
https://javhay.net/
https://javbulk.com/
https://javhdmovies.com/
http://cowmm.com/
https://japanhdv.com/
https://www.javqt.com/
http://javx.cc/
https://javladies.com/
https://javpornhd.xyz/
https://javxspot.com/
https://hotmovs.com/
https://www.pussyspace.com/
https://avwend.com/
https://gotjav.com/
https://javengsub.com/
https://www.javbangers.com/
https://javdoe.tv/
https://javqd.me/
https://www.javmost.com/
https://popjav.tv/
https://91porn.com
https://bestjavporn.com/
https://javsin.tv/
https://javout.net/
https://javfun.me/
https://www.javjack.com/
https://sextop.net/
https://pornbraze.com/
http://xcam.asia/
https://fbjav.com/
https://javbulk.com/
https://www1.javbraze.com/
https://javfree.biz/
https://javrave.club/
https://kaplog.com/
https://www.liboggirls.net/

**Comment by nxzlem** [comment]
Situsnya banyak kak, cari yang masi ada link di hosts bebasid, situ hapusin yg sudah di tambahkan dari bebasid hosts, nanti di cek brp yg sudah linknya.

**Comment by heywolf15** [comment]
Ini orang ga bisa baca apa males lol

**Comment by nxzlem** [comment]
> Ini orang ga bisa baca apa males lol

Situs banyak kak.

**Comment by gvoze32** [comment]
sudah dicek semuanya kalau belum terdaftar di hosts?

**Comment by nxzlem** [comment]
situs 9 yang tidak diblokirkan oleh trustpositif dan 
![B4ldlYR](https://i.imgur.com/B4IdIYR.png)
situs 40 yang diblokirkan oleh trustpositif
![ya520B9](https://user-images.githubusercontent.com/30078972/85996711-c9809600-ba32-11ea-86e9-e7e368bbad59.png)

**Comment by nxzlem** [comment]
bentar dlu, mw bikin pull request untuk 40 situs yg diblokir dari trustpositif

**Comment by nxzlem** [comment]
sudah ditambahkan dari semua situs kak, tolong re-install bebasid/update bebasin ya. terima kasih :D
