### ISSUE TITLE
[ASK] Domain muncul di auto complete ssh

### ISSUE THREAD

**Issue by nafalabi** [bebasid/bebasid#163]
Bagaimana cara supaya domain name di hosts tidak tampil di auto complete ssh
> type "ssh " then press "tab"

**Comment by nxzlem** [comment]
Bagaimana maksudnya kak?

**Comment by andraantariksa** [comment]
https://unix.stackexchange.com/questions/66636/remove-a-host-from-the-completion-list-for-ssh-in-zsh
https://destinmoulton.com/blog/2018/how-to-disable-zsh-ssh-hosts-completion/

Shell yang dipakai apa?

**Comment by nafalabi** [comment]
saya pake bash

**Comment by nxzlem** [comment]
@nafalabi apakah sudah bisa kak? tolong respon ya. terima kasih :)

**Comment by andraantariksa** [comment]
Silahkan baca https://unix.stackexchange.com/questions/370980/where-does-ssh-pull-autocompletion-from. Sepertinya harus edit file `/usr/share/bash-completion/completions/ssh` atau `/usr/share/bash-completion/bash_completion` buat exclude file hosts.

**Comment by nafalabi** [comment]
Terima kasih @andraantariksa 
Sudah bisa resolve, saya tambahkan line berikut di .bashrc saya
`export COMP_KNOWN_HOSTS_WITH_HOSTFILE="" #don't use /etc/hosts for ssh autocomplete`
