### ISSUE TITLE
[REQ] Pisahin website R18 sama yg bukan

### ISSUE THREAD

**Issue by realicejoanne** [bebasid/bebasid#164]
**Permintaan fitur**
Sebenernya lebih ke feature request sih ya. Jujur saya cukup ngerti sih bebasid nanti bakal masukin IP website yang diblokir Kominfo ke file *hosts*. Nah yang saya pengen request fitur supaya di menu CLI bebasidnya ditanya dulu mau **include situs R18 atau engga**. Soalnya jujur risih aja liat file *hosts* tapi kebanyakan listnya panjang gara2 website gituan padahal yang saya butuh paling kayak netflix, tumblr, reddit, dll. Ujung-ujungnya saya hapus manual di file *hosts*nya sendiri. Malu aja hey, ada yg namanya VPN kenapa ribet coba harus ngewhitelist situs macam gitu pake bebasid. Toh tujuan utama proyek bebasid ini adalah untuk belajar, tapi malah yang saya lihat kebanyakan situs yang dimasukin malah yang tidak mendidik.

Terima kasih atas kerja keras dari *developers* bebasid! Semoga sukses!

**Comment by dikiaap** [comment]
Dulu memang pernah ada untuk pilihan antara NSFW dan yang bukan, tetapi bung @gvoze32 [menghapusnya](https://github.com/bebasid/bebasid/commit/d412832d306311f2b2324f5a1fd11db3ae70b913) bersamaan dengan  [host.android](https://github.com/bebasid/bebasid/commit/fa99e8ae376a61c13faff2e2ac2ccc7aa29d37b9). Mungkin bung @gvoze32 bisa memberi komentar tentang usulan ini lagi.

**Comment by heywolf15** [comment]
Kalo malu itumah balik lagi ke diri sendiri masing2, gak ada bacaan tujuan proyek ini untuk belajar.

Tapi request untuk dipisahkan itu bagus.

**Comment by realicejoanne** [comment]
Wah sayang banget kalo pernah ada pilihannya tapi dihapus. Atau mungkin agak sulit ya dibuat utk Android? Saya sih nyobanya pake CLI di Windows makanya rada ngerti sama kodingannya.

**Comment by gvoze32** [comment]
Dulu pernah ada, tapi tidak tersentuh sama maintainer lain, jadi nggk terurus lagi, akhirnya saya hapus. Kalau mau ditambahin lagi bisa, tapi harus kasih tau maintainer yang lain kalau semisal ada update website dengan kategori safe for work bisa diupdate juga list yang safe for worknya

**Comment by gvoze32** [comment]
Kalau untuk android sebenernya agak susah kalau manual, bakalan makan waktu, soalnya sistemnya satu ip satu domain, kecuali kalo pake script. Dulu kayaknya @icaksh pernah bilang buat scriptnya deh.

**Comment by icaksh** [comment]
Untuk request hosts SFW (selanjutnya disebut safe) sudah disediakan [disini](https://github.com/bebasid/bebasid/commit/db0ab0551c2b735a682dded1ba3966569bd5d1b2)
Note:
1. Hosts safe hanya tercantum domain yang memang memiliki traffic akses yang tinggi (misalnya Netflix, Reddit, dsb) dikarenakan sistem penulisan masih manual (untuk fix hosts saja masih manual, apalagi memisahkan antara safe dan non-safe)
2. Untuk versi Linux dan Mac sudah secara default menggunakan hosts SFW (baca changelog bash linux [disini](https://github.com/bebasid/bebasid/blob/master/releases/bebasid.sh)), untuk Windows bisa bersabar terlebih dahulu.
3. Untuk versi Android (non-root) mengingat bahwa Host-Go (atau apalah itu) menggunakan sistem ODOL (One Domain One Line), sudah ada [scriptnya](https://github.com/bebasid/bebasid/blob/master/dev/scripts/fix.php) dan sudah ditambahkan di [dev](https://github.com/bebasid/bebasid/blob/master/dev/resources/hosts.android)
4. Maintenance untuk versi safe dan Android tidak akan se-up to date- versi non-safe

Thanks
