### ISSUE TITLE
[BUG] pahe.in internet positif

### ISSUE THREAD

**Issue by ahmad-shiddiq** [bebasid/bebasid#165]
**Deskripsi mengenai bug**
pahe.in tidak bisa dibuka, dan beralih ke internet positif.
sudah dicoba unduh file hosts yang terbaru, tetapi hasil masih sama.

**Screenshot**
![image](https://user-images.githubusercontent.com/53107961/85949675-59b2d280-b982-11ea-86aa-a5343d94efdf.png)

**Device**
 - OS: [Manjaro]
 - Browser [Brave]

**Comment by icaksh** [comment]
Gunakan perintah

bebasid hosts change


Ada pengubahan hosts NSFW menjadi SFW

**Comment by gvoze32** [comment]
@icaksh Engga lebih baik dicampur aja ya yang sfw dan nsfw untuk default hostsnya?

**Comment by nxzlem** [comment]
@ahmad-shiddiq apakah sudah di update hosts bebasid?

**Comment by ahmad-shiddiq** [comment]
Masih gabisa om, baru cek di windows tapi tetep gak bisa, udah dicoba install pake bebasin atau bebasid tetep gak work

**Comment by ahmad-shiddiq** [comment]
![image](https://user-images.githubusercontent.com/53107961/86025468-6c97d680-ba58-11ea-9729-dabe7262327a.png)
padahal udah dicoba hapus internet positif nya. tetep gak bisa dibuka

**Comment by icaksh** [comment]
> Masih gabisa om, baru cek di windows tapi tetep gak bisa, udah dicoba install pake bebasin atau bebasid tetep gak work

pahe.in ternyata move ke pahe.ph

Nunggu hostsnya update ya

**Comment by icaksh** [comment]
> @icaksh Engga lebih baik dicampur aja ya yang sfw dan nsfw untuk default hostsnya?

:v gak wkwkwk

**Comment by ahmad-shiddiq** [comment]
> > Masih gabisa om, baru cek di windows tapi tetep gak bisa, udah dicoba install pake bebasin atau bebasid tetep gak work
> 
> pahe.in ternyata move ke pahe.ph
> 
> Nunggu hostsnya update ya

siap om, tapi waktu installasi ataupun update kok gak ada pilihan install sfw atau nsfw

**Comment by nxzlem** [comment]
@ahmad-shiddiq bagaimana dengan hostsnya? anda sudah bisa atau tidak?

**Comment by ahmad-shiddiq** [comment]
bisa om, terimakasih
