### ISSUE TITLE
[BUG] muchohentai.com

### ISSUE THREAD

**Issue by monixL** [bebasid/bebasid#172]

**Comment by nxzlem** [comment]
![E33e6nj](https://i.imgur.com/E33e6nj.png)
Kayanya situsnya ada Forbidden (Terlarang) kak, gak bisa masuk. Sudah memakai VPN.

**Comment by nxzlem** [comment]
Maaf kak td kayanya udh di tambahkan situs [muchohentai.com] tapi masih forbidden. Maka harus di hapuskan situs [muchohentai.com] nya.
