### ISSUE TITLE
[BUG] xvideos.com

### ISSUE THREAD

**Issue by DarkKnightHD1000** [bebasid/bebasid#180]
Sepertinya semua IP dari XVideos telah berubah 
tolong segera di perbaiki

![image](https://user-images.githubusercontent.com/53641048/86944452-00ad2080-c172-11ea-88e8-54753a65701e.png)

[Window 10 pro]
 [Chrome, Chrome Beta, Firefox]

**Comment by nxzlem** [comment]
gans, sudah di updatekan hosts bebasid g?

**Comment by DarkKnightHD1000** [comment]
> gans, sudah di updatekan hosts bebasid g?

sudah gan

**Comment by nxzlem** [comment]
> > gans, sudah di updatekan hosts bebasid g?
> 
> sudah gan

apakah masih bisa gak kak?

**Comment by wijaksanapanji** [comment]
should be fixed with this [commit](https://github.com/bebasid/bebasid/commit/00205efaa21061d0780ab7e94b27b0892262491d).

**Comment by nxzlem** [comment]
Permisi kak, tolong diupdatekan hosts bebasid ya, bukakan dengan bebasid.bat atau bebasin.exe.
Terimakasih!
