### ISSUE TITLE
[BUG] Tidak Bisa Bypass Web 

### ISSUE THREAD

**Issue by swtlbyz** [bebasid/bebasid#182]
Saya menginstall script dari bebasid.github.io untuk Linux Ubuntu 20 , tetapi webnya masih belom bisa tembus/bypass padahal list webnya sudah masuk ke /etc/host . Saat ini saya mengambil contoh web 1337x, dia terkena safesurf oleh ISP yang saya pakai (Biznet), padahal script untuk Windows berjalan dengan normal di browser Chrome dan Firefox

Screenshoot: https://imgur.com/3tCbYCK

# Test
OS: Ubuntu 20.04 LTS
Browser: Chromium & Firefox

**Comment by icaksh** [comment]
1. Apa cuma 1337x.to saja?
2. Pemakaian bebasid pertama kali atau udah pemakaian lama?
3. Kalau pemakaian baru, apakah network manager sukses direstart?

1337x.to alamatnya belum redirect jadi g bakal error seperti itu..

alternatif 1337x.gd

**Comment by swtlbyz** [comment]
Barusan saya cek kembali setelah reinstall dan update lagi hosts bebasidnya dan sudah work untuk site yang dites itu 1337x dan pornhub. Untuk pemakaian bebasid untuk Linux ini baru pertama kali, dan network manager sudah di restart dan di on off kan manual. Thanks

Prove: https://imgur.com/ypD9WiP
