### ISSUE TITLE
[BUG] Script Install Host NSFW Tidak Tertambah

### ISSUE THREAD

**Issue by swtlbyz** [bebasid/bebasid#183]
Saya menggunakan script dari bebasid.github.io, saat menginstall paket bebasid pada menu muncul pilihan install host SFW & NSFW saya pilih host NSFW tetapi yang terinstall hanya host SFW. Mohon perbaikannya

Screenshoot: https://imgur.com/D5r0xOs

# Test
OS: Ubuntu 20.04 LTS

**Comment by icaksh** [comment]
iya itu, kemaren setelah update baru tau kalo yg bagian itu ngebug (kodenya cuma kopas atasnya), tapi karena untuk mengurangi "keseringan update" makanya dibiarin wkwkwk..

pakai command `bebasid hosts change` untuk ubah SFW ke NSFW

Thanks
