### ISSUE TITLE
[BUG] netflix.com

### ISSUE THREAD

**Issue by kgkevinwg** [bebasid/bebasid#185]
**Deskripsi mengenai bug**
Netflix tidak bisa diakses via browser, hanya loadint tidak selesai. Setelah map ip pada file host untuk address netflix di hapus, netflix dapat kembali diakses. sepertinya mappingnya sudah berubah.

**Device**
 - OS: Ubuntu 20.04, Windows 10 2004
 - Browser: Firefox

**Comment by gvoze32** [comment]
Hosts yang terbaru sudah menghapus Netflix dari rule, kemungkinan Anda menggunakan hosts lama
