### ISSUE TITLE
[BUG] pornbay.org

### ISSUE THREAD

**Issue by bhaskoro-muthohar** [bebasid/bebasid#187]
**Deskripsi mengenai bug**
Tidak bisa melakukan akses jika menggunakan bebasid, namun lancar tanpa bebasid

**Device**
 - OS: Macos Catalina
 - Browser: Safari

**Comment by nxzlem** [comment]
okeh kak sudah di gantikan ip baru dan ditambahkan situs subdomain untuk [piratebay.org]
sekarang tolong diupdatekan hosts bebasid ya
terima kasih :D
