### ISSUE TITLE
easyload.io

### ISSUE THREAD

**Issue by valdev-fs** [bebasid/bebasid#189]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts
Tolong di unblock, soal nya pas click download g ada response dari web nya

Terima kasih

**Comment by valdev-fs** [comment]
sample : https://easyload.io/f/mWXn6ry2XO/4_mp4

**Comment by nxzlem** [comment]
Saya sudah cek kak, tidak ada situs terblokir dari situs [easyload.io].
Screenshots :
![dWSrsGa](https://i.imgur.com/dWSrsGa.png)
