### ISSUE TITLE
[REQ] https://mangadex.org/

### ISSUE THREAD

**Issue by masato052** [bebasid/bebasid#190]

**Comment by wijaksanapanji** [comment]
Added on this [commit](https://github.com/bebasid/bebasid/commit/f3cf8d12ece0ddac22fd5ae4111ebe0bea2dc99e).

please check if it's working, also close the issues if it's work.

**Comment by nxzlem** [comment]
maaf kak, ini tidak ada terblokiran dari situs [mangadex.org] oleh trustpositif.
![tl80D00](https://i.imgur.com/tI8oD00.png)
