### ISSUE TITLE
[BUG] onlyfans.com

### ISSUE THREAD

**Issue by bhaskoro-muthohar** [bebasid/bebasid#192]
**Deskripsi mengenai bug**
Mohon di update IP nya sudah tidak tembus inet positif lagi

**Device**
 - OS: MacOS Catalina
 - Browser: Safari

**Comment by nxzlem** [comment]
Permisi kak, tolong diupdatekan hosts bebasid ya, bukakan dengan bebasid.bat atau bebasin.exe.
Terimakasih!
