### ISSUE TITLE
[REQ] bebasid untuk AdAway Android

### ISSUE THREAD

**Issue by calvinize** [bebasid/bebasid#193]
Sebelumnya, terima kasih untuk para contributor di bebasid ini. Saya sudah pake cukup lama di PC saya tidak pernah ada masalah.

Mau ngungkit aja di issue sebelumnya #134 ada yg pernah tanya soal import hosts file di AdAway untuk Android. Kalo dari yg saya baca akhirnya issue-nya masih unresolved ya?

Saya juga pengguna AdAway di Android, sepertinya problem-nya kenapa hosts file bebasid nggak compatible karena format yg bisa diproses oleh AdAway harus satu domain satu baris. Mungkin harus dibuat program-nya untuk convert dari versi original jadi per baris?

Kalo ada cara alternatif juga boleh di-share dong. Soalnya untuk sekarang saya masih input manual hanya untuk beberapa situs yg saya sering kunjungi. Thank you.

**Comment by wijaksanapanji** [comment]
Halo, apakah kamu sudah pernah mencoba [1.1.1.1](https://play.google.com/store/apps/details?id=com.cloudflare.onedotonedotonedotone&hl=en_US)
saya biasa pakai untuk akses reddit, dll, saya lebih prefer menggunakan 1.1.1.1 untuk di hp karena lebih mudah dan bebasid untuk di PC

**Comment by calvinize** [comment]
Halo, iya saya udah pake, tapi sayangnya untuk beberapa situs juga masih nggak bisa diakses. Makanya alternatifnya saya pake AdAway.

**Comment by icaksh** [comment]
bebasid one domain one line sudah ada disini

https://github.com/bebasid/bebasid/blob/master/dev/resources/hosts.android
