### ISSUE TITLE
[REQ] 3xplanet.com

### ISSUE THREAD

**Issue by inablock** [bebasid/bebasid#194]
https://3xplanet.com

**Comment by wijaksanapanji** [comment]
Should be fixed with this [commit](https://github.com/bebasid/bebasid/commit/47fa8ac6201e188817440b2775f432e2d9d98bad).

Please update your `hosts` and check if it's working, also **close** the issue if there is no problem.

**Comment by nxzlem** [comment]
Permisi kak, tolong diupdatekan hosts bebasid ya, bukakan dengan bebasid.bat atau bebasin.exe.
Terimakasih!
