### ISSUE TITLE
[BUG] jav.sh

### ISSUE THREAD

**Issue by inablock** [bebasid/bebasid#195]
**Deskripsi mengenai bug**
Video nggak jalan, cover video nggak muncul

**Screenshot**
-

**Device**
 - OS: Windows 10
 - Browser: Edge

**Comment by wijaksanapanji** [comment]
Should be fixed with this [commit](https://github.com/bebasid/bebasid/commit/47fa8ac6201e188817440b2775f432e2d9d98bad).

Please update your `hosts` and check if it's working, also **close** the issue if there is no problem.

**Comment by nxzlem** [comment]
INDONESIA:
Jangan lupa pembaruin hosts bebasid ya
Terimakasih!
