### ISSUE TITLE
[BUG] www.crazyshit.com

### ISSUE THREAD

**Issue by berbahagia3** [bebasid/bebasid#197]
situs www.crazyshit.com tidak dapat ditembus

![Untitled](https://user-images.githubusercontent.com/61977895/88281892-ac2da780-cd12-11ea-8d3f-4d7ba9b01ec1.png)

 - OS: Windows 10
 - Browser Chrome dan Firefox

**Comment by nxzlem** [comment]
Apakah sudah di updatekan hosts bebasidnya?

**Comment by nxzlem** [comment]
Permisi kak, tolong diupdatekan hosts bebasid ya, bukakan dengan bebasid.bat atau bebasin.exe.
Terimakasih!
