### ISSUE TITLE
[BUG] 1337X.TO

### ISSUE THREAD

**Issue by fjr619** [bebasid/bebasid#2]
Tidak bisa di buka untuk site 1337X.TO, klo pake vpn bisa

**Device**
 - OS:  windows 10
 - Browser: chrome

**Comment by icaksh** [comment]
Domain to IP
(http://two-ply-mixtures.000webhostapp.com/?domain=1337x.to)

IP di BEBASID: 104.31.17.3
IP terbaru: 104.31.88.65

Note: IP tersebut masuk dalam range IP CloudFlare atau CF (https://www.cloudflare.com/ips-v4) alias pemilik domain 1337x.to menggunakan layanan CF sehingga IP sering berubah-ubah.

Anda dapat mengunduh file terbaru atau mengedit secara manual file hosts.
