### ISSUE TITLE
Hapus/Non-aktifkan BEBAS ID

### ISSUE THREAD

**Issue by ezr101** [bebasid/bebasid#202]
Halo, mau tanya bagaimana caranya untuk menghapus host BebasID dan aplikasi bypass dpi di iOS? Apakah harus via terminal seperti saat menginstall? mohon bantuannya ya.

**Comment by icaksh** [comment]
iOS atau MacOS?

**Comment by sayyidamn** [comment]
Kalau di windows ?

**Comment by nxzlem** [comment]
> iOS atau MacOS?

iOS bilangnya.

**Comment by gvoze32** [comment]
> 
> 
> Kalau di windows ?

Kalau di windows tinggal ubah ke default melalui cli

**Comment by ezr101** [comment]
Maaf misslead informasi. Maksud saya menghapus host BebasID di MacOS. Mohon pencerahannya yaa

**Comment by icaksh** [comment]
`bebasid --help`

disitu sudah ada perintah untuk menghapus bebasid
