### ISSUE TITLE
[BUG] yande.re

### ISSUE THREAD

**Issue by Theiamilis** [bebasid/bebasid#215]
[**Deskripsi]([url](url)) mengenai bug**
webnya gk bisa di buka

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.

**Device**
 - OS: Windows 10
 - Browser Chrome
![Screenshot (505)](https://user-images.githubusercontent.com/54315757/92357620-5b331080-f112-11ea-8f1d-5f08fd5a7a08.png)

**Comment by nxzlem** [comment]
saya tidak ada masalah kak, yg ada maintenance itu server nya lagi diperbaiki/lain2nya.

**Comment by nxzlem** [comment]
coba ulang lagi kak

**Comment by nxzlem** [comment]
ok saya sudah fixed site nya jan lupa update hosts bebasid y dan coba lagi buka situsnya, thank you
