### ISSUE TITLE
[BUG] nhentai.net

### ISSUE THREAD

**Issue by MikaAndroid** [bebasid/bebasid#224]
**Deskripsi mengenai bug**
Gambar tidak ter-load

**Device**
 - OS: Windows 10, Android 9
 - Browser: Google Chrome

**Comment by skymunn** [comment]
![image](https://user-images.githubusercontent.com/32958839/94972657-5bb99e00-053c-11eb-8349-c5f34a08a2fa.png)

TKP di Makassar pakai XL Axiata pun sama.
