### ISSUE TITLE
[BUG] i.nhentai.net

### ISSUE THREAD

**Issue by MikaAndroid** [bebasid/bebasid#231]
**Deskripsi mengenai bug**
Sebelumnya, saya minta maaf karena laporan sebelumnya salah sasaran. Masalahnya ada pada i.nhentai.net. error yang tertera di chrome ERR_ADDRESS_UNREACHABLE
**Screenshot**
![Screenshot_20201006-214907_Chrome](https://user-images.githubusercontent.com/72053306/95218058-16d48680-081e-11eb-8266-8492966c4d5c.png)
![Screenshot_20201006-214951_Chrome](https://user-images.githubusercontent.com/72053306/95218064-189e4a00-081e-11eb-8951-ff50892e72c7.png)

**Device**
 - OS: [Android 9]
 - Browser [Chrome]

**Comment by gvoze32** [comment]
ada dua ip, yang satu 198.255.82.50 dan yang satu 185.177.127.77, bisa dicoba keduanya yang bisa yang mana

**Comment by MikaAndroid** [comment]
Setelah saya coba, IP yang pertama bisa. Terimakasih

**Comment by gvoze32** [comment]
sudah difix https://github.com/bebasid/bebasid/commit/4d55d25fa8bed038f58db4838a2ad4a9e542e129
