### ISSUE TITLE
[REQ] jkforum.net

### ISSUE THREAD

**Issue by vjbenn** [bebasid/bebasid#234]

**Comment by nxzlem** [comment]
masalahnya situs jkforum.net tidak ada ipnya kak.

**Comment by vjbenn** [comment]
Oof. Thanks

**Comment by nxzlem** [comment]
kami sudah cek situs jkforum.net tidak ada keblokir oleh trustpositif. kakak coba buka situsnya

**Comment by vjbenn** [comment]
sorry gan kurang jelas, saya akses dari telkomsel (by.u) dan masih di block internetbaik

**Comment by nxzlem** [comment]
> sorry gan kurang jelas, saya akses dari telkomsel (by.u) dan masih di block internetbaik

Oh its okay kak, sorry ya...

**Comment by nxzlem** [comment]
Kalo saya sih tidak keblokir karena provider saya pake indihome dan dari kemendikibud

**Comment by skymunn** [comment]
Kebetulan saya pake indihome di sini, jadi saya bisa trace dari sini

**Comment by nxzlem** [comment]
> Kebetulan saya pake indihome di sini, jadi saya bisa trace dari sini

okeh, sudah di merge kak.

**Comment by vjbenn** [comment]
Awesome, thanks bebasid team

**Comment by nxzlem** [comment]
> Awesome, thanks bebasid team

okeh, sama2

**Comment by vjbenn** [comment]
Awesome, terimakasih
