### ISSUE TITLE
[BUG] sankakucomplex.com

### ISSUE THREAD

**Issue by monixL** [bebasid/bebasid#235]
subdomain diblock

**Comment by nxzlem** [comment]
Looks like kakak belum diupdatekan host bebasidnya. coba update hostsnya kak. terimakasih

**Comment by monixL** [comment]
![image](https://user-images.githubusercontent.com/52873193/96404442-90507980-120d-11eb-957a-416d25ffaf70.png)
di chan.sankakucomplex.com gambarnya nggak muncul

**Comment by nxzlem** [comment]
Oh sabar ya kak kita akan menyelidik situs sankakucomplex.com nya dan kita akan diperbarui hostsnya. terimakasih

**Comment by gvoze32** [comment]
invalid report

**Comment by gvoze32** [comment]
reopen issue since someone opened pr related to this issue

https://github.com/bebasid/bebasid/pull/242
