### ISSUE TITLE
[BUG] xvideos.com broke

### ISSUE THREAD

**Issue by vjbenn** [bebasid/bebasid#236]
xvideos tidak terload sempurna

![Screenshot (9)](https://user-images.githubusercontent.com/67304538/95886553-ee620480-0da8-11eb-8ce6-395e145b881b.png)

**Device**
 - OS: win10 pro 1909 build 18363.418
 - Chrome

**Comment by nxzlem** [comment]
kakak udah coba updating host bebasidnya?

**Comment by vjbenn** [comment]
> kakak udah coba updating host bebasidnya?

Udah gan, ini latest

**Comment by nxzlem** [comment]
> > kakak udah coba updating host bebasidnya?
> 
> Udah gan, ini latest

oke bentar ya kak kami akan menyelidiki untuk hostnya.

**Comment by vjbenn** [comment]
Ok thanks

**Comment by gvoze32** [comment]
https://github.com/bebasid/bebasid/commit/fff10752990148784fcfd9a6f9bde5991bd88af8
