### ISSUE TITLE
[BUG] www.pornhub.com

### ISSUE THREAD

**Issue by monixL** [bebasid/bebasid#237]
Tidak bisa download

 - OS: Windows 10 2004
 - Browser: Microsoft Edge

**Comment by nxzlem** [comment]
Coba re-download lagi kak kalo gak bisa coba reload situsnya situ re-download lagi. kalo masih ada masalah coba updatekan host bebasidnya

**Comment by gvoze32** [comment]
bisa sertakan screenshot?

**Comment by nxzlem** [comment]
@monixL

**Comment by nxzlem** [comment]
> bisa sertakan screenshot?

coba renew ip sama kasih subdomain barunya @gvoze32

**Comment by gvoze32** [comment]
keknya blm masuk ip nya

**Comment by nxzlem** [comment]
> keknya blm masuk ip nya

gan tutup gk issue topik nya?

**Comment by gvoze32** [comment]
@nxzlem eh iya saya close aja ya
