### ISSUE TITLE
[BUG] can't use NSFW mode

### ISSUE THREAD

**Issue by Sogep1111** [bebasid/bebasid#239]
pas finalisasi langsung force close

**Comment by gvoze32** [comment]
@bebasid/app

**Comment by icaksh** [comment]
> pas finalisasi langsung force close

memang force close, namun app akan muncul kembali..

Apakah ada masalah lain?

**Comment by Sogep1111** [comment]
problem fixed gan

**Comment by icaksh** [comment]
oke, secara tidak langsung issue ditutup
