### ISSUE TITLE
[BUG] 1337x.to

### ISSUE THREAD

**Issue by poxipox** [bebasid/bebasid#246]
**Deskripsi mengenai bug**
halo kang, saya lagi test pake edge chromium 1337x.to dan clonengannya ga bisa, langsung ke layar menkominfo. udah flushing juga ga bisa. browser laen lancar. apa ada setting2 di browsernya yang ngalangin ya?

**Screenshot**
https://prnt.sc/ved715

**Device**
 - OS: win 10 2004 20H2
 - Browser Edge Chromium

**Comment by wijaksanapanji** [comment]
coba buka [duckduckgo.com](https://duckduckgo.com) kemudian cari 1337x.to, lalu klik dari result duckduckgo, berlaku juga untuk website lain.

**Comment by poxipox** [comment]
still the same gan. cuma bisa sampe sini doang.
klo di klik domain yg lain langsung ke page inet positif. 
btw ini ane temuin cuma di edge chromium apdetan windows 10 terbaru yak, 20h2. di browser, firefox/chrome lancar.


    On Monday, November 9, 2020, 8:45:55 PM GMT+7, sadpanda <notifications@github.com> wrote:  
 
 


coba buka duckduckgo.com kemudian cari 1337x.to, lalu klik dari result duckduckgo, berlaku juga untuk website lain.

**Comment by icaksh** [comment]
Edge terbaru belum test support hosts apa engga (sama kayak MacOS), jika bisa, bantu bebasid meriset dengan cara menambahkan line dibawah ini

2606:4700:3036::681f:5941 1337x.to
2606:4700:3035::ac43:8dbc 1337x.to
2606:4700:3032::681f:5841 1337x.to

Laporan kami tunggu

**Comment by se8870** [comment]
![work](https://user-images.githubusercontent.com/55049217/98775870-8989e080-2420-11eb-857f-23d8f6c29df2.PNG)

Menggunakan IPv4 sepertinya bekerja, namun ipv6 sendiri kurang tau.

**Comment by poxipox** [comment]
report edge chromium : udah coba ditambah line nya, masih ga bisa. klo di klik continue to... dia ke pagenya menkominfo seperti biasa. 

btw, ane isp pake PT Mora Telematika Indonesia/ oxygen biz. IPv 4.  

    On Wednesday, November 11, 2020, 1:20:43 PM GMT+7, Someone <notifications@github.com> wrote:  
 
 




Menggunakan IPv4 sepertinya bekerja, namun ipv6 sendiri kurang tau.

**Comment by se8870** [comment]
Pake indihome aman kok.

**Comment by nxzlem** [comment]
misi kak @poxipox masih bisa gk?

**Comment by poxipox** [comment]
masih belum mas gan. ane cuma penasasaran aja sih kemaren. daily sebenrnya ga pake itu browser. :D 

    On Sunday, November 15, 2020, 10:22:46 PM GMT+7, NXzLEM <notifications@github.com> wrote:  
 
 


misi kak @poxipox masih bisa gk?

**Comment by nxzlem** [comment]
udah gan coba update lagi hosts nya 
kalo masih gk bisa, masukin situs 1337x.to ke windows hosts file dengan pake notepad atau notepad++
104.31.89.65 1337x.to 
104.31.89.65 www.1337x.to 
104.31.89.65 chat.1337x.to
198.134.112.244 ssa.1337x.to
104.31.88.65 cdn.1337x.to

**Comment by poxipox** [comment]
masih belum bisa gan. btw ane selalu apdet via copas langsung ke host system32 kok. cek github berkala :D 
masih kaya gitu klo di edge chromium. udah di flush juga.  
btw sorry nih gan jadi ngerepotin  :)  

    On Friday, November 20, 2020, 2:06:09 PM GMT+7, NXzLEM <notifications@github.com> wrote:  
 
 


udah gan coba update lagi hosts nya
kalo masih gk bisa, masukin situs 1337x.to ke windows hosts file dengan pake notepad atau notepad++
104.31.89.65 1337x.to
104.31.89.65 www.1337x.to
104.31.89.65 chat.1337x.to
198.134.112.244 ssa.1337x.to
104.31.88.65 cdn.1337x.to

**Comment by nxzlem** [comment]
aneh...

**Comment by gvoze32** [comment]
Di build 1904 terpantau lancar aja

**Comment by nxzlem** [comment]
punya saya di versi windows build 20h2 lancar gan,
!(50646848641_c3b157ef2d_o)[https://live.staticflickr.com/65535/50646848641_c3b157ef2d_o.png]

**Comment by icaksh** [comment]
Problemnya di Edge Chromium, dari tim sendiri belum ada yang tes menggunakan Edge Chromium apakah support hosts file atau tidak. Dugaan sementara Edge Chromium sama seperti Safari, harus menggunakan hosts ipv4 dan ipv6

**Comment by gvoze32** [comment]
@icaksh Itu pake Edge Chromium kok

**Comment by icaksh** [comment]
> @icaksh Itu pake Edge Chromium kok

lah..

**Comment by nxzlem** [comment]
> > @icaksh Itu pake Edge Chromium kok
> 
> lah..

kok?

**Comment by Eiikirin** [comment]
> ![work](https://user-images.githubusercontent.com/55049217/98775870-8989e080-2420-11eb-857f-23d8f6c29df2.PNG)
> 
> Menggunakan IPv4 sepertinya bekerja, namun ipv6 tidak bekerja sama sekali.

Ini pake edge chromium, mungkin antara emang udah di block ip nya sama provider ISP kamu.

**Comment by poxipox** [comment]
> 
> 
> > ![work](https://user-images.githubusercontent.com/55049217/98775870-8989e080-2420-11eb-857f-23d8f6c29df2.PNG)
> > Menggunakan IPv4 sepertinya bekerja, namun ipv6 tidak bekerja sama sekali.
> 
> Ini pake edge chromium, mungkin emang udah di block ip nya sama provider ISP kamu.

coba di klik lagi di index nya bisa ga? soalnya di chromium ane cuma sampe situ doang, tapi ga bisa di klik semua menu mau ke index page nya. lagi aneh kali nih koneksi wkwkwkw, di firefox rarbg ga bisa di akses, tapi di chromium lancar malahan. kebalikannya.
