### ISSUE TITLE
[REQ] jvid.com

### ISSUE THREAD

**Issue by vjbenn** [bebasid/bebasid#248]
Terblock oleh Internet Baik Telkomsel

**Comment by nxzlem** [comment]
oke kak, sekarang coba diupdatekan hosts bebasid, terlapor nya akan di tunggu. terimakasih

**Comment by nxzlem** [comment]
Tested on Windows 10 20H2 with Pi-Hole Installed
![chrome_Id5KSQAya6](https://user-images.githubusercontent.com/30078972/98920143-528bfb80-2502-11eb-8a92-65b7d12d331c.png)
(Dicensorkan due to pornographic)

**Comment by vjbenn** [comment]
awesome, thanks bebasid team
