### ISSUE TITLE
[BUG] bebasid.exe gak keluar programnya

### ISSUE THREAD

**Issue by KKJawnoob** [bebasid/bebasid#249]

**Comment by KKJawnoob** [comment]
Deskripsi mengenai bug
Bug mau install tapi bebasid.exe gak keluar programnya. udah klik kanan run as admin juga tetep gabisa. padahal biasanya ganti host sfw ke nsfw gapernah error programnya.

OS: [Windows 10 2004]

**Comment by icaksh** [comment]
hapus file bebasid-hosts.bak di c:\Windows\System32\drivers\etc\

**Comment by nxzlem** [comment]
permisi kak, kalo belum komentar dari 15 hari atau 30 hari topik issue nya akan tutup

**Comment by nxzlem** [comment]
halo kak @KKJawnoob kakak masih jawab gk?
