### ISSUE TITLE
[BUG] Tidak bisa buka netflix. Butuh cara untuk auto update host file netflix

### ISSUE THREAD

**Issue by windoro** [bebasid/bebasid#25]
**Deskripsi mengenai bug**
Netflix tetap tidak bisa dibuka, tapi situs yang lain bisa. Sepertinya address nya sudah ganti

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.

**Device**
- Linux (Ubuntu)

**Comment by nxzlem** [comment]
Karena netflix ganti IP yang baru atau belum tau.
