### ISSUE TITLE
[REQ] webtoon.xyz

### ISSUE THREAD

**Issue by ahmad-shiddiq** [bebasid/bebasid#254]
Website belum tersedia di hosts file

**Comment by nxzlem** [comment]
udah gan cek aja di pull request/commit nya

**Comment by ahmad-shiddiq** [comment]
![image](https://user-images.githubusercontent.com/53107961/100186629-f28d5000-2f18-11eb-8d33-f240e53b9e98.png)
Sebelumnya sudah saya coba tambahkan sendiri, tapi gambar-gambar nya tidak tampil. Kira-kira dimana masalahnya ya?

**Comment by nxzlem** [comment]
dah bisa gan?

**Comment by ahmad-shiddiq** [comment]
Sudah bisa mas, terimakasih.
