### ISSUE TITLE
[REQ] newgrounds.com (user homepages)

### ISSUE THREAD

**Issue by wolvenworks** [bebasid/bebasid#255]
main websitenya sih bisa...tapi kalo mau liat let's say user homepage untuk Zhu (yang buat xiao xiao stickfight), malah jadi gak bisa soalnya linknya jadi zhu.newgrounds.com. so for now newgrounds cuma half-unblocked cuz there's still bits of it that are blocked.

**Comment by nxzlem** [comment]
udah gan cek aja di pull request/commit nya
