### ISSUE TITLE
[BUG] yespornplease dot com

### ISSUE THREAD

**Issue by FraziSilver** [bebasid/bebasid#26]
**Deskripsi mengenai bug**
Situs nya gak bisa di buka ada tulisan banned bla bla bla

**Screenshot**
![image](https://user-images.githubusercontent.com/46099607/77254698-575f1f00-6c95-11ea-96eb-7bffaec7f63b.png)

**Device**
 - OS: Win 7
 - Browser Chrome

**Comment by gvoze32** [comment]
memang gabisa gan berarti, ditutup aksesnya ke web mereka
