### ISSUE TITLE
tokyomotion.net

### ISSUE THREAD

**Issue by akogiman** [bebasid/bebasid#265]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts

Sudah dicek dan memang tidak ada

OS: Windows 10
Browser: Chrome, Microsoft Edge, Brave Browser
ISP: Plat Merah

**Comment by gvoze32** [comment]
https://github.com/bebasid/bebasid/commit/7b2651493d9cc1a888076cc603caacbef6e20b5a
