### ISSUE TITLE
[REQ] Rockstar Social Club

### ISSUE THREAD

**Issue by ModiFlasher** [bebasid/bebasid#267]
Gan bisa request buat Rockstar Social Club soalnya gk bisa di akses tapi kalo nyalain VPN malah bisa di akses ini berakibat gk bisa buka GTA V sama Game Rockstar lain nya
Ntah ini masalah di rockstar nya atau isp nya saya gk tau
Barangkali disini ada yg sama ?

**Comment by gvoze32** [comment]
Masalahnya sudah pernah dibahas di reddit
https://www.reddit.com/r/indonesia/comments/j1p5xg/telkom_blokir_koneksi_ke_social_club_rockstar/

Solusinya adalah melakukan restart modem sampai menemukan IP yang bagus.
