### ISSUE TITLE
Customize site benchmark untuk proxy tunnel

### ISSUE THREAD

**Issue by fijar-lazuardy** [bebasid/bebasid#268]
Berhubung netflix udah ga diblokir sama hampir semua ISP, kalo user bisa set sendiri site buat jadi "benchmark" untuk proxy tunnel-nya (misal yang default-nya netflix, jadi reddit) pasti lebih mantep

**Comment by gvoze32** [comment]
wah ini bisa sih

**Comment by fijar-lazuardy** [comment]
oke, moved to bebasit
