### ISSUE TITLE
[BUG] Bebasid.exe tidak mau update

### ISSUE THREAD

**Issue by NoiseBox20** [bebasid/bebasid#275]
**Deskripsi mengenai bug**
Tidak bisa update host melalui aplikasi Bebasid.exe. aplikasi selalu close sendiri saat ada tulisan berhasil mengambil backup host. sudah run as admin dan masuk dalam exclusion antivirus.

**Screenshot**
![Screenshot (45)](https://user-images.githubusercontent.com/65381461/104838717-587dce80-58ef-11eb-9241-a64b4f4f7a02.png)

**Device**
 - OS: windows 10 20H2

**Comment by NoiseBox20** [comment]
Uninstall, download ulang, dan pasang ulang juga tidak bisa.

**Comment by icaksh** [comment]
Ini kayaknya ada bug dari appnya

BTW mohon maaf untuk bugnya belum bisa tak fix karena ada kendala hardware dengan jangka waktu yg tidak ditentukan

Pakai metode TUI aja ya..
