### ISSUE TITLE
[BUG] App bebasid for Windows (Tidak dapat dipakai)

### ISSUE THREAD

**Issue by arielnations** [bebasid/bebasid#276]
**Deskripsi mengenai bug**
Deskripsi yang jelas dan ringkas tentang apa yang terjadi.tadi nya lancar saja tida tiba pas ingin di buka malah seperti itu awal nya jadi kaya gitu ngefreze dulu

**Screenshot**
Jika ada, tambahkan ss untuk membantu
![image](https://user-images.githubusercontent.com/77686755/105063044-dc7db500-5aad-11eb-85ba-91707c3e033c.png)
 menjelaskan mengenai bug.tidak bisa di buka

**Device**
 - OS: [cth. Windows 7]windows 10
 - Browser [cth. Chrome, Firefox]

**Comment by icaksh** [comment]
Ini kayaknya ada bug dari appnya

BTW mohon maaf untuk bugnya belum bisa tak fix karena ada kendala hardware dengan jangka waktu yg tidak ditentukan

Pakai metode TUI aja ya..

**Comment by arielnations** [comment]
METODE TUI JUGA sama mas os not found atau apalah itu

**Comment by heywolf15** [comment]
Gua selalu update manual

buka folder releases di home page, click hosts, click RAW, terus di copy
copy ke hosts di C:\Windows\System32\drivers\etc, buka hosts pake notepad++,
 save, save as adminstrator

**Comment by wolvenworks** [comment]
> Gua selalu update manual
> 
> buka folder releases di home page, click hosts, click RAW, terus di copy
> copy ke hosts di C:\Windows\System32\drivers\etc, buka hosts pake notepad++,
> save, save as adminstrator

udh ikutin ini tapi malah gak ke unblock semua site (eg: reddit malah ke block lagi)

**Comment by berbahagia** [comment]
atau ya sementara pakai "secure DNS" bawaan dari browser, kaya Cloudflare dan Quad9 misalnya

**Comment by icaksh** [comment]
close dulu

**Comment by gvoze32** [comment]
Sementara bisa pake CLI yang batch ya buat windows

**Comment by nxzlem** [comment]
read on #293
