### ISSUE TITLE
[BUG] Bebasin.exe OS error 2

### ISSUE THREAD

**Issue by TakadaWang** [bebasid/bebasid#278]
**Deskripsi mengenai bug**
- OS Error 2 ketika akan install Bebasin.exe
- Tidak bisa buka Bebasid.exe

**Screenshot**
![os error](https://user-images.githubusercontent.com/47318513/106352215-ac3adf80-6313-11eb-8b1d-d787539994e4.PNG)

**Device**
 - OS: Win 10
 - Browser Firefox

**Comment by nxzlem** [comment]
permisi kak,
anda salah ngirim issue di sini, anda harus pindah issue ke situ https://github.com/bebasid/bebasin/issues

**Comment by nxzlem** [comment]
Oh btw, code error 2 itu tidak ada file hosts nya, tolong anda di tambahkan hosts nya lewat create a new text, terus di gantikan jadi "hosts" saja. Jangan di kasi format apapun, gitu saja.
