### ISSUE TITLE
fanfiction.net

### ISSUE THREAD

**Issue by muzzin-ctrl** [bebasid/bebasid#280]
**Deskripsi mengenai bug**
saya tau di host ada situs fanfiction , tp pakai firstmedia gak bisa dibuka ... malah linknya nyasar ke situs ini http://lostredirect.dnsmadeeasy.com/lostredirect.html

**Screenshot**

![Fanfic](https://user-images.githubusercontent.com/78278322/106384606-5bec7c00-63fe-11eb-959d-46012f638872.png)

**Device**
 - OS: [cth. Windows 10]
 - Browser [cth. Chrome, Firefox]

**Comment by nxzlem** [comment]
silakan update hosts bebasid ya
makasih
kalo mau close issue silakan. kalo gak respon, sudah mengerti, issue nya akan di tutup dalam beberapa waktu.
