### ISSUE TITLE
[REQ] nanime.in

### ISSUE THREAD

**Issue by NeoProx** [bebasid/bebasid#281]
di hosts adanya nanime.yt sedangkan sekarang nanime.in butuh di update, terima kasih

**Comment by nxzlem** [comment]
silakan update hosts bebasid ya
makasih
kalo mau close issue silakan. kalo gak respon, sudah mengerti, issue nya akan di tutup dalam beberapa waktu.

**Comment by NeoProx** [comment]
sekalian dong bang subdomainnya.. naniplay.nanime.in , zippyshare.nanime.in terima kasih @nxzlem

**Comment by nxzlem** [comment]
> sekalian dong bang subdomainnya.. naniplay.nanime.in , zippyshare.nanime.in terima kasih @nxzlem 

Okeh, sebentar y kak.

**Comment by nxzlem** [comment]
Sudah kak. terimakasih

**Comment by NeoProx** [comment]
makasih!!
