### ISSUE TITLE
[REQ] https://c2c.binance.com/

### ISSUE THREAD

**Issue by laitsky** [bebasid/bebasid#282]
Halo, boleh minta tolong untuk menambahkan subdomain https://c2c.binance.com/ ke hosts filenya? Soalnya kelihatannya nggak bisa dibuka. Di hosts file memang sudah ada whitelist untuk binance.com, tetapi belum ada untuk subdomain c2c,binance.com. Thanks!

**Comment by laitsky** [comment]
- ftp.binance.com
- academy.binance.com
- bsc-dataseed.binance.org

Yang di atas ini juga masih blocked (tested di IndiHome), mungkin bisa ditambahin juga?

**Comment by nxzlem** [comment]
Udah di merge ngab.

**Comment by laitsky** [comment]
Thanks!
