### ISSUE TITLE
[BUG] motherless.com

### ISSUE THREAD

**Issue by anaya77** [bebasid/bebasid#288]
Web bisa dibuka tapi gini tampilannya

![Untitled](https://user-images.githubusercontent.com/49011347/107309653-6f15e080-6abd-11eb-8665-9f5c33667a09.png)

Windows 7 , Android
Browser Firefox

**Comment by anaya77** [comment]
udah disable adblock sama aja gak berubah

**Comment by nxzlem** [comment]
silakan update hosts bebasid ya
makasih
kalo mau close issue silakan. kalo gak respon, sudah mengerti, issue nya akan di tutup dalam beberapa waktu.
