### ISSUE TITLE
[BUG] binance.com

### ISSUE THREAD

**Issue by YogaSakti** [bebasid/bebasid#291]
**Deskripsi mengenai bug**
Binance versi desktop tidak dapat terhubung ke sistem sehingga order book, chart, trades tidak berubah/bergerak

**Screenshot**
![image](https://user-images.githubusercontent.com/24309806/107847019-c77d1300-6e1a-11eb-9799-af2a76c2b4c5.png)

**Device**
 - OS: Windows 10 Pro
 - Browser/App: Binance Desktop ([https://www.binance.com/en/download](https://www.binance.com/en/download))

**Other Condition**
- Provider Indie~
- DNS Cloudflare
- Menggunakan Hosts bebasid release terbaru
- Binance versi Website berjalan dengan baik di Edge & Chrome
- Sudah flush Dns + restart Modem + restart network + restart system

**Comment by gvoze32** [comment]
Oke lagi dilakukan pengecekan
