### ISSUE TITLE
[BUG] App force close dan tidak bisa dibuka lagi (.exe) (same as on #276)

### ISSUE THREAD

**Issue by kowingko** [bebasid/bebasid#292]
![image](https://user-images.githubusercontent.com/43992421/107878041-ad1e6480-6f02-11eb-87d6-a007b7302308.png

Jalanin aplikasinya pake yg .exe, pas sampe di proses backup, prosesnya stuck terus appsnya force close dan aplikasinya ngga bisa dibuka lagi, terus aku mau coba edit manual abis liat rawnya eh tapi malah hosts filenya kok hilang ya

**Comment by icaksh** [comment]
untuk gui emang saat ini ad bug yang "entah kenapa muncul tiba tiba"

belum dapat ngefix hingga waktu yang tidak ditentukan

**Comment by nxzlem** [comment]
(same as on #276) read on #293

**Comment by nxzlem** [comment]
Sementara pake CLI Batch dlu, soalnya GUI dalam perbaiki.
