### ISSUE TITLE
[BUG] update host (same as on #276)

### ISSUE THREAD

**Issue by closetsukebei** [bebasid/bebasid#293]
**Deskripsi mengenai bug**
Setelah klik update host, tiba2 stopped working dan tidak bisa dibuka lagi
edit: sudah di restart, masih gini

**Screenshot**
SS stopped working ada (general stopped working), tapi error waktu update hostnya lupa di SS

![ww](https://user-images.githubusercontent.com/79117991/108000237-0b8b3600-701c-11eb-8fb0-0916313d9eb0.jpg)

Description:
  Stopped working

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	bebasid.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	efb63b5d
  Problem Signature 04:	mscorlib
  Problem Signature 05:	2.0.0.0
  Problem Signature 06:	5c9c4d2b
  Problem Signature 07:	34d3
  Problem Signature 08:	e1
  Problem Signature 09:	System.IO.FileNotFoundException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1041

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Device**
 - OS: win 7 64 bit
 - Browser opera

**Comment by icaksh** [comment]
Problem Signature 09: System.IO.FileNotFoundException

Kayaknya gagal ambil file hostnya..

**Comment by closetsukebei** [comment]
host udah ke create kok (setelah klik install, meskipun empty file) -> result : stopped working
hostnya aku isi manual pake notepad++ -> result : tetep stopped working

biar GUInya bisa jalan lagi, hostnya harus di delete (kosong atau terisi hasilnya akan stopped working, otomatis harus install dulu)

**Comment by nxzlem** [comment]
Aneh, saya juga kek gitu. Pas pilih sfw, hosts nya ilang sendiri.

**Comment by nxzlem** [comment]
Sama juga di issue #276 bebasid has stopeed working, windows 10 & 7.

**Comment by gvoze32** [comment]
Sementara pake yang versi batch dulu

**Comment by nxzlem** [comment]
> Sementara pake yang versi batch dulu

Yes bro, harus pake batch dulu, soalnya GUI nya kadang" rusak dalam script kode nya.
