### ISSUE TITLE
[BUG] TUI: findstr cannot open

### ISSUE THREAD

**Issue by closetsukebei** [bebasid/bebasid#294]
**Deskripsi mengenai bug**
Karena versi GUI error, mencoba install yg versi TUI. FINDSTR: Cannot Open {host path} dan seperti SS dibawah

**Screenshot**
![ww](https://user-images.githubusercontent.com/79117991/108134782-65a5fd00-70e9-11eb-8309-6be723acbfdc.jpg)

**Device**
 - OS: Win. 7 64 bit
 - Browser Opera

**Comment by Ncode2014** [comment]
coba ente cek di folder tersebut siapa tau file nya ke hapus, soalnya ane juga kek gitu pas ane bikin ulang file hostsnya  akhirnya fix

**Comment by Ncode2014** [comment]
nah ane berhasil reproduce kenapa itu terjadi 

skenarionya
1. jalankan aplikasi bebasid.exe lalu klik update
2. lalu pas dia mau grab file host dari github aplikasi nya tiba tiba force close dan file hosts di folder etc pun hilang

sepertinya pas dia mau ambil file host nya ada aktifitas mencurigakan yang dimana pas sedang ambil file nya tiba tiba aplikasi nya force close dan file host yang didalam folder etc hilang seketika

OS: Win 10 64 bit
Browser: Chrome dan Firefox

**Comment by closetsukebei** [comment]
i see, udah solved yg error "FINDSTR"nya. thank you
tapi yg step download (error merah) tetep error
SS
![ww](https://user-images.githubusercontent.com/79117991/108362208-0b5e8680-7226-11eb-99f9-6fe6d87cd2a6.jpg)

how to solve : tambah file "hosts" ke folder etc. [link](https://support.microsoft.com/en-us/topic/how-to-reset-the-hosts-file-back-to-the-default-c2a43f9d-e176-c6f3-e4ef-3500277a6dae)

close ya. makasih
