### ISSUE TITLE
[BUG] windows GUI saat dark mode

### ISSUE THREAD

**Issue by ijash** [bebasid/bebasid#3]
**Deskripsi mengenai bug**
di dark theme teks hitam ga gitu jelas. baiknya di tiap button pakein background atau mungkin ada implementasi lebih baik.

tambahan: secara User experience. baiknya ada tambahan tombol back. saran aja sih.

**Screenshot**
![image](https://user-images.githubusercontent.com/30673286/76123302-dfed8680-602a-11ea-90f8-61de519d7d8e.png)

**Device**
 - OS: win10
 - Browser -
sayang saya ga gitu ngerti windows apps. kalau bisa saya pull req.

**Comment by nxzlem** [comment]
Ini bukan bug, developernya kasih text warna hitam makanya begitu.
