### ISSUE TITLE
[BUG] chaturbate.com

### ISSUE THREAD

**Issue by devanada** [bebasid/bebasid#304]
**Deskripsi mengenai bug**
Chaturbate bisa diakses, tapi asset-assetnya jadi missing seperti gambar terlampir

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.
![image](https://user-images.githubusercontent.com/53251131/109430223-d4148480-7a32-11eb-8611-595146ee0085.png)

**Device**
 - OS: Windows 10
 - Browser: Edge

**Comment by gvoze32** [comment]
$=contains lot of var
==========================
$-fallback.pa.highwebmedia.com
edge$.stream.highwebmedia.com
chatw-$.stream.highwebmedia.com
realtime.pa.highwebmedia.com
cbjpeg.stream.highwebmedia.com

**Comment by nxzlem** [comment]
ini gimana gan? saya bingung issue ini.

**Comment by nxzlem** [comment]
silakan coba diperbaruikan hosts bebasid

**Comment by nxzlem** [comment]
kalo mau close issue silakan. kalo gak respon, sudah mengerti, issue nya akan di tutup dalam beberapa waktu.
