### ISSUE TITLE
[REQ] yts.lt redirect ke yts.mx

### ISSUE THREAD

**Issue by adhiwena** [bebasid/bebasid#307]
yts.lt redirect ke yts.mx, sedangkan yts.mx nya belum kebuka.

saya pake ini untuk ngebukanya:

```
# [yts.mx]
172.67.72.176 yts.mx www.yts.mx img.yts.mx
```

**Comment by nxzlem** [comment]
silakan update hosts bebasid ya
makasih
kalo mau close issue silakan. kalo gak respon, sudah mengerti, issue nya akan di tutup dalam beberapa waktu.
