### ISSUE TITLE
[REQ] torrentz2.eu

### ISSUE THREAD

**Issue by DecimusYna** [bebasid/bebasid#31]
When I was a young boy
My father took me into the city
To see a marching band

Gan, makasih sudah bukain subscene, paheal, dll. :)
Kaget kemarin saya lihat situs-situs kesukaan pada ke-blokir semua. Apalagi saya malas buka-buka vpn (malas juga bayar premium XD).
Thank you, truly.

**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts

**Comment by DecimusYna** [comment]
Wait a minute, maksudnya paheal. Pahe ada domain lain wkwk. Tapi pahe.in masih bisa request nggak? :1

**Comment by gvoze32** [comment]
pahe ada domain baru .me jadi yang .in kami hapus
