### ISSUE TITLE
[REQ] mrdeepfakes.com

### ISSUE THREAD

**Issue by Nosoba** [bebasid/bebasid#313]
```
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts
```
Sudah di cek dan memang belum ada.

**Comment by nxzlem** [comment]
Halo, @Nosoba.
mrdeepfakes.com sudah di tambahkan dari hosts bebasid.
Issuenya akan di tutup dari sementara waktu. 
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih.
