### ISSUE TITLE
[REQ] 9anime.to, .ru, beserta mirrornya

### ISSUE THREAD

**Issue by nattadasu** [bebasid/bebasid#314]
Domain utama website sudah diblokir oleh pemerintah, tetapi untuk _mirror_ belum. Jika bisa, mohon untuk dapat didaftarkan juga domain _mirror_ ke dalam berkas Hosts.

Daftar domain 9ANIME:
| No | Domain | Status |
| -: | ------ | :----: |
| 1 | [9anime.to](https://9anime.to/) | Utama |
| 2 | [9anime.ru](https://9anime.ru/) | Utama |
| 3|[9anime.pw](https://9anime.pw/) | _Mirror_ |
| 4|[9anime.at](https://9anime.at/) | _Mirror_ |
| 5|[9anime.video](https://9anime.video/) | _Mirror_ |
| 6|[9anime.page](https://9anime.page/) | _Mirror_ |
| 7|[9anime.life](https://9anime.life/) | _Mirror_ |
| 8|[9anime.live](https://9anime.live/) | _Mirror_ |
| 9|[9anime.one](https://9anime.one/) | _Mirror_ |
| 10|[9anime.love](https://9anime.love/) | _Mirror_ |
| 11|[9anime.app](https://9anime.app/) | _Mirror_ |

**Comment by nattadasu** [comment]
Sedikit tambahan, semua domain yang saya lampirkan bersumber dari laman web berikut: https://9anime.zone/

**Comment by nxzlem** [comment]
Baik saya akan menambahkan situs mirror dan utama nya terimakasih

**Comment by nxzlem** [comment]
Oke, situs mirror sama utamanya sudah di tambahkan dari hosts bebasid.
Issuenya akan di tutup dari sementara waktu. 
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih.
