### ISSUE TITLE
[BUG] www.pornhub.com & xhamster.com

### ISSUE THREAD

**Issue by muzzin-ctrl** [bebasid/bebasid#315]
**Deskripsi mengenai bug**
pake firstmedia gak bisa buka pornhub .. 
*edit xhamster jg gak bisa nih ..

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.

**Device**
 - OS: [cth. Windows 10]
 - Browser [cth. Chrome, Firefox]

**Comment by nxzlem** [comment]
pornhub.com dan xhamster.com sudah digantikan dengan ip baru dan sudah ditambahkan subdomain. 
Issuenya akan di tutup dari sementara waktu. 
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih.
