### ISSUE TITLE
[REQ] opposite6890.com

### ISSUE THREAD

**Issue by syofyanzuhad** [bebasid/bebasid#317]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts

**Comment by nxzlem** [comment]
Halo, @syofyanzuhad.
opposite6890.com sudah di tambahkan dari hosts bebasid.
Issuenya akan di tutup dari sementara waktu. 
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih.

**Comment by syofyanzuhad** [comment]
ada lg update yg baru min, ini : [opposite6890](https://oppositeleaks.com/)

**Comment by syofyanzuhad** [comment]
sementara itu dulu https://oppositeleaks.com/

**Comment by nxzlem** [comment]
!(m4juCzL)[https://i.imgur.com/m4juCzL.png]
