### ISSUE TITLE
[BUG] nijie.info Fixed

### ISSUE THREAD

**Issue by Ebi12054j1** [bebasid/bebasid#318]
**Deskripsi mengenai bug**
Nijie.info gak bisa kebuka
saya udah fix
nih untuk tambahan

# [nijie.info]
160.16.230.19 nijie.info sp.nijie.info 
160.16.213.212 watch.nijie.info api.nijie.info sp.stg3.nijie.info sp.stg.nijie.info www.nijie.info admin.nijie.info
160.16.149.244 pic05.nijie.info pic.nijie.info admin.stg.nijie.info pic04.nijie.info 
160.16.65.50 hc.a1.imgw.nijie.info 
160.16.139.93 mail02.nijie.info dev02.nijie.info admin.stg4.nijie.info stg.nijie.info 
160.16.98.98 mail.nijie.info mb.dev01.nijie.info admin.dev03.nijie.info admin.dev02.nijie.info mail01.nijie.info
160.16.201.170 pic01.nijie.info pic02.nijie.info thumbs.nijie.info
160.16.65.50 imgw.nijie.info dev03.nijie.info stg3.nijie.info sp.dev03.nijie.info 
160.16.233.122 mail03.nijie.info 
160.16.78.98 hc.m.imgw.nijie.info hc.b1.imgw.nijie.info admin.stg3.nijie.info sp.stg2.nijie.info img.nijie.info stg4.nijie.info stg2.nijie.info sp.dev02.nijie.info hc.imgw.nijie.info sp.dev01.nijie.info dev01.nijie.info sp.stg4.nijie.info admin.dev01.nijie.info admin.stg2.nijie.info mb.stg.nijie.info
160.16.198.126 hc.m2.imgw.nijie.info 
160.16.105.76 gw01.nijie.info
160.16.73.194 pic03.nijie.info

**Device**
OS: win10

**Comment by nxzlem** [comment]
nijie.info sudah digantikan dan diperbaikan untuk issue anda.
Issuenya akan di tutup dari sementara waktu. 
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih.
