### ISSUE TITLE
[REQ] https://gogoanime.pro/

### ISSUE THREAD

**Issue by masato052** [bebasid/bebasid#322]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts

**Comment by nxzlem** [comment]
Halo, @masato052.
gogoanime.pro sudah di tambahkan dari hosts bebasid.
Issuenya akan di tutup dari sementara waktu. 
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih.

**Comment by masato052** [comment]
Thanks
