### ISSUE TITLE
[BUG] http://www.mangago.me/

### ISSUE THREAD

**Issue by scarletyx** [bebasid/bebasid#327]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts

**Comment by nxzlem** [comment]
Halo, @scarletyx 
mangago.me telah sudah tambahkan di hosts bebasid dari orang lain.
Jadinya, mangago.me sudah digantikan dengan IP lama dengan IP baru & Ditambahkan subdomains lain"nya.
Issuenya akan di tutup dari sementara waktu.
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih.
