### ISSUE TITLE
[REQ] myhdjav.me javgiga.com goodporn.to javopen.co

### ISSUE THREAD

**Issue by jumanji778** [bebasid/bebasid#328]
myhdjav.me
javgiga.com
goodporn.to
javopen.co

**Comment by nxzlem** [comment]
Halo, @jumanji778.
javgiga.com telah sudah tambahkan di hosts bebasid dari orang lain.
Jadinya, mangago.me sudah digantikan dengan IP lama dengan IP baru & Ditambahkan subdomains lain"nya.
myhdjav.me, goodporn.to dan javopen.co sudah ditambahkan dari hosts bebasid.
Issuenya akan di tutup dari sementara waktu.
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih.

**Comment by jumanji778** [comment]
thankyu sir
