### ISSUE TITLE
[BUG] javcl.com

### ISSUE THREAD

**Issue by fjr619** [bebasid/bebasid#329]

**Comment by nxzlem** [comment]
Halo, @fjr619.
javcl.com sudah digantikan dengan IP terbaru dan sudah ditambahkan subdomain nya.
Issuenya akan di tutup dari sementara waktu.
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih.
