### ISSUE TITLE
[BUG] subscene.com

### ISSUE THREAD

**Issue by marlenexxx** [bebasid/bebasid#33]
**Deskripsi mengenai bug**
Tidak bisa login, soalnya mau up sub

**Screenshot**
ngga ada soalnya jelas.

**Device**
 - OS: Win 7
 - Browser: Chrome

**Comment by gvoze32** [comment]
Login dites bisa dari sini, coba agan buka identity.jeded.com atau jeded.com bisa atau tidak, kalau bisa atau tidak bisa silahkan balas chat ini

v2.subscene.com

**Comment by marlenexxx** [comment]
ga bisa..

**Comment by marlenexxx** [comment]
take a long to respond

**Comment by gvoze32** [comment]
diredirect ke internet positif?

**Comment by marlenexxx** [comment]
enggak, cuma "This site can't be reached"
