### ISSUE TITLE
[REQ] graphis.ne.jp

### ISSUE THREAD

**Issue by 12345axc** [bebasid/bebasid#330]
https://graphis.ne.jp/

**Comment by nxzlem** [comment]
Halo, @12345axc.
graphis.ne.jp sudah ditambahkan dari hosts bebasid.
Issuenya akan di tutup dari sementara waktu.
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih.

**Comment by 12345axc** [comment]
![21-05-02_ t12-46-22-508PM_firefox](https://user-images.githubusercontent.com/83169800/116803754-9e7c3c80-ab44-11eb-9ae1-7bc50131bd56.png)
![21-05-02_ t12-47-46-674PM_firefox](https://user-images.githubusercontent.com/83169800/116803759-a0de9680-ab44-11eb-993e-fc64c61afbaf.png)

Masih belum muncul gambar nih

**Comment by nxzlem** [comment]
Halo, @12345axc.
Silakan coba lagi, sudah diperbaikan dari user lain...
Terimakasih
