### ISSUE TITLE
[REQ] pandajago.com

### ISSUE THREAD

**Issue by DestinyModz** [bebasid/bebasid#331]
**Ketentuan**
Selamat datang di pandajago
Pendaftar harus berusia 17 tahun keatas.
Anda wajib memberikan data informasi dengan lengkap dalam formulir yang tersedia saat melakukan registrasi (Nomor telepon
Proses Transaksi hanya bisa dilakukan pada jam bank online.
Kami berhak menolak proses setiap member yang memanipulasi atau mencurigakan.
Peringatan keras bagi bonus hunter / player hantu / betting syndicate tidak terima disini. Jika terindikasi adanya keganjilan dalam betlist maka kami berhak menutup akun dan menyita seluruh kredit yang ada.
Kami melarang keras penggunaan perangkat, software, "bots", program atau metode apapun yang diaplikasikan untuk menghasilkan taruhan yang tidak wajar dan merugikan pihak kami. Penutupan account akan dilakukan tanpa adanya pemberitahuan terlebih dahulu dan semua kemenangan dari taruhan yang dilakukan akan dibatalkan dan sisa saldo akan dihanguskan.
Kami tidak menerima komplain atas Void dan Reject dalam permainan, Sebab itu diluar tanggung jawab kami.
Proses Withdraw atau penarikan tidak dapat dilakukan apabila informasi rekening tertuju berbeda seperti informasi rekening pada database kami. Oleh sebab itu wajib memberikan data informasi yang benar saat melakukan registrasi.

**Comment by nxzlem** [comment]
Halo, @DestinyModz.
pandajago.com sudah ditambahkan dari hosts bebasid.
Issuenya akan di tutup dari sementara waktu.
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih.
