### ISSUE TITLE
[REQ] chaturbate.wiki & www.sakuralive.com

### ISSUE THREAD

**Issue by muzzin-ctrl** [bebasid/bebasid#332]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts

**Comment by nxzlem** [comment]
Halo, @muzzin-ctrl.
chaturbate.wiki dan sakuralive.com sudah ditambahkan dari hosts bebasid.
Issuenya akan di tutup dari sementara waktu.
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih.
