### ISSUE TITLE
[SARAN] jangan mengganti file hosts original users

### ISSUE THREAD

**Issue by azhr-project** [bebasid/bebasid#333]
Daripada mengganti file hosts users. Kenapa tidak mengappend atau menggabungkan dengan milik bebasid.

**Comment by nxzlem** [comment]
Maaf, bagaimana maksudnya?

**Comment by azhr-project** [comment]
Maaf hanya kesalahan pada saat instalasi saya.

**Comment by nxzlem** [comment]
Oh, baik tidak ada apa-apa keadaan salah. Terima kasih.
