### ISSUE TITLE
[REQ] erome.com & [BUG] redgifs.com

### ISSUE THREAD

**Issue by vercouver** [bebasid/bebasid#334]
**Deskripsi mengenai bug**
Tidak bisa memutar video pada situs erome.com dan situs redgifs.com tidak bisa diakses.

**Screenshot**
https://drive.google.com/file/d/1wmpDghDq8UGzrJ-YojQvO47vwPxyihz0/view?usp=sharing
https://drive.google.com/file/d/1g5qXxjjCvMDXRfLz7Kub5LQwMVGYVy3t/view?usp=sharing

**Device**
 - OS: Windows 10
 - Browser: Chrome

**Comment by nxzlem** [comment]
Halo, @vercouver.
erome.com sudah ditambahkan di hosts bebasid oleh dari seorang user @timothydillan.
redgifs.com sudah diperbaikan oleh dari seorang user @timothydillan.
Issuenya akan di tutup dari sementara waktu.
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih.
