### ISSUE TITLE
[BUG] s-jav.com, javhhh.com & oploverz.in

### ISSUE THREAD

**Issue by fjr619** [bebasid/bebasid#335]
https://s-jav.com/
www.javhhh.com
www.oploverz.in

**Comment by nxzlem** [comment]
Halo, @fjr619.
s-jav.com, javhhh.com & oploverz.in sudah digantikan dengan IP terbaru dan sudah ditambahkan subdomain nya.
Issuenya akan di tutup dari sementara waktu.
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih.
