### ISSUE TITLE
[BUG] i.nhentai.net

### ISSUE THREAD

**Issue by MikaAndroid** [bebasid/bebasid#337]
**Deskripsi mengenai bug**
Gambar cover dan thumbnail bisa muncul, tapi gambar halaman saat dibuka tidak muncul
ERR_CONNECTION_REFUSED

**Screenshot**
![Screenshot_20210503-003224_Chrome.png](https://user-images.githubusercontent.com/72053306/116822076-0fecd700-aba7-11eb-8566-d52654fe5cdb.png)

![Screenshot_20210503-003328_Chrome.png](https://user-images.githubusercontent.com/72053306/116822125-390d6780-aba7-11eb-8d32-250a32aea20e.png)

**Device**
 - OS: Android
 - Browser: Chrome

**Comment by mangkoran** [comment]
Untuk file host-nya pakai ini kak: [bebasid/releases/hosts](https://github.com/bebasid/bebasid/blob/master/releases/hosts)

Sepertinya dokumentasi untuk Android perlu di-update. Kemarin gua pakai [bebasid/dev/resources/hosts.android](https://raw.githubusercontent.com/bebasid/bebasid/master/dev/resources/hosts.android) juga nggak bisa. Ternyata ada beberapa host yang belum di-update untuk Android. Mungkin dokumentasi untuk Android perlu di-update karena pakai hosts file yang sama seperti desktop sudah bisa.

**Comment by MikaAndroid** [comment]
Trims, setelah saya coba pakai host file yang sama dengan desktop sudah bisa

**Comment by nxzlem** [comment]
Fix ini telah sudah diissuedkan oleh @mangkoran.
Halo, @MikaAndroid jika mau tutup issue. Silakan saja ya.
Jika ada masalah kontakkan kami. Terimakasih
