### ISSUE TITLE
Need tester for Linux

### ISSUE THREAD

**Issue by icaksh** [bebasid/bebasid#34]
Need tester for who use Manjaro

**Req**
 - OS: Manjaro
 - Browser: Google Chrome Stable
 - Have Netflix Premium Account

**What should I do?**

Get the bash script
`sudo wget https://raw.githubusercontent.com/bebasid/bebasid/master/dev/scripts/green-tunnel/gt.sh -O /usr/local/bin/bebasid-gt`

Give permission
`chmod +x /usr/local/bin/bebasid-gt`

Execute
`bebasid-gt`

It will installing NPM, Green Tunnel, and Screen also it will kill all opened Chrome and open Green Tunnel and  new Chrome Stable but using Proxy Server on background (screen), new Chrome will be appear

Open Netflix and Play a Video

If you wanna restore
`killall screen`
`rm -rf /usr/local/bin/bebasid-gt`

**What should I report?**

If you can play video or not, report it 

Thank You

NB: I will close this issue if no reply / comment after 3 days and I issue this because I don't use Netflix; Netflix Trial Program has ended...

**Comment by gvoze32** [comment]
green tunnel isn't working for netflix here

**Comment by icaksh** [comment]
![2020-03-26-185209_1366x768_scrot](https://user-images.githubusercontent.com/19889081/77618709-6251d200-6f69-11ea-9335-cbb6d8d06d61.png)

Status success playing Netflix on Indihome, but this is ALPHA version (and I dont wanna develop this feature more because need RHEL & Debian Derivative tester)

Special thanks to LeLe

**Comment by icaksh** [comment]
> green tunnel isn't working for netflix here

coba pake gt yg cli, terus dns servernya pakai dnslify..

**Comment by gvoze32** [comment]
iya kmaren posisi pake yang cli, tested di manjaro, buat dns dnslify belum dicoba sih, nanti mungkin dicoba, kalo bisa nanti kukabarin

**Comment by gvoze32** [comment]
Bisa pake tmux aja nggk daripada pake screen?

**Comment by gvoze32** [comment]
Sama tambahin buat browser lain kek firefox atau chromium
