### ISSUE TITLE
[REQ] gravuretube.net

### ISSUE THREAD

**Issue by fjr619** [bebasid/bebasid#341]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts

**Comment by nxzlem** [comment]
Halo, @fjr619.
gravuretube.net sudah ditambahkan dari hosts bebasid.
Issuenya akan di tutup dari sementara waktu.
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih. 🙏🏻
