### ISSUE TITLE
[BUG] narutopixxx.com

### ISSUE THREAD

**Issue by muzzin-ctrl** [bebasid/bebasid#344]
**Deskripsi mengenai bug**
pake firstmedia , thumbnailnya pada gak muncul .

**Screenshot**
![pixxx](https://user-images.githubusercontent.com/78278322/118298218-63491880-b509-11eb-84c1-df6c0d349b3f.png)

**Device**
 - OS: [cth. Windows 10]
 - Browser [cth. Chrome, Firefox]

**Comment by nxzlem** [comment]
Mungkin kalo ditambahin subdomain bakal diperbaiki.
`208.167.227.185 narutopixxx.com
208.167.227.185 www2.narutopixxx.com
208.167.227.185 2a.narutopixxx.com
208.167.227.185 shared.narutopixxx.com
208.167.227.185 imap.narutopixxx.com
208.167.227.185 ftp.narutopixxx.com
208.167.227.185 www.narutopixxx.com
208.167.227.185 com252fdns252fwww.narutopixxx.com
208.167.227.185 robtex.com252fdns252fwww.narutopixxx.com
208.167.227.185 htmlwww.narutopixxx.com
208.167.227.185 com.htmlwww.narutopixxx.com
208.167.227.185 comwww.narutopixxx.com
208.167.227.185 wwww.narutopixxx.com`

**Comment by nxzlem** [comment]
Maaf sebelumnya, yg image dari website itu beda yang domainnya (hentaikey.com). Jadikan bakal dinambahin domainnya dari situnya.

**Comment by nxzlem** [comment]
Update 2. Permasalahnya hentaikey.com nya belum tentu diupdate dari hosts bebasid. Maaf atas segeranya. Nanti akan diperbarui. Terimakasih
