### ISSUE TITLE
[BUG] hpjav.tv

### ISSUE THREAD

**Issue by irfanbee** [bebasid/bebasid#345]
**Ketentuan**
kena ipo :(

**Comment by nxzlem** [comment]
Halo, @irfanbee.
hpjav.tv sudah digantikan dengan IP terbaru dan sudah ditambahkan subdomainnya.
Issuenya akan di tutup dari sementara waktu.
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih.
