### ISSUE TITLE
[BUG] fapforfun.net

### ISSUE THREAD

**Issue by NoiseBox20** [bebasid/bebasid#346]
Tidak dapat masuk ke website muncul ERR_CONNECTION_TIMED_OUT. lepas hosts baru bisa masuk.

**Screenshot**
![image](https://user-images.githubusercontent.com/65381461/118391345-057a1500-b65e-11eb-9888-fc056b6dd64e.png)

**Device**
 - OS: Windows 10
 - Browser Brave

**Comment by nxzlem** [comment]
Halo, @NoiseBox20.
fapforfun.net sudah digantikan dengan IP terbaru dan sudah ditambahkan subdomainnya.
Issuenya akan di tutup dari sementara waktu.
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih.
