### ISSUE TITLE
[BUG] oploverz.in

### ISSUE THREAD

**Issue by fjr619** [bebasid/bebasid#348]
**Deskripsi mengenai bug**
Deskripsi yang jelas dan ringkas tentang apa yang terjadi.

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.

**Device**
 - OS: [cth. Windows 7]
 - Browser [cth. Chrome, Firefox]

**Comment by nxzlem** [comment]
Bisa kasih contoh screenshotnya kak? Terimakasih.

**Comment by fjr619** [comment]
klo pakai incognito tidak masalah

**Comment by nxzlem** [comment]
Hm, iya karena ada ekstensi plugin-pluginya di dalam chrome tanpa samaran. Kalo samaran itu tidak ada di ekstensi. Kalo mau dinyalakan bisa ke chrome://extensions > Details > Allow in Incongnito (Samaran) Dinyalakan.

Iya sama-sama kak. Terimakasih.
