### ISSUE TITLE
[BUG] netflix.com

### ISSUE THREAD

**Issue by fluxyz** [bebasid/bebasid#35]
**Deskripsi mengenai bug**
Baru" ini mau nonton netflix keluar error gini, mungkin ada yang senasib?

**Screenshot**
![image](https://user-images.githubusercontent.com/62659781/77561322-224f0880-6ef1-11ea-9ab6-c12812c95598.png)

**Device**
 - OS: [cth. Windows 8]
 - Browser [cth. Chrome]

**Comment by gvoze32** [comment]
hosts akan diupdate

**Comment by fluxyz** [comment]
its works perfectly rn thankyou
