### ISSUE TITLE
[BUG] nekopoi.care

### ISSUE THREAD

**Issue by Lustsifer** [bebasid/bebasid#351]
**Deskripsi mengenai bug**
Website nekopoi.care selalu menuju internet positif di Android tapi aman di pc. Saya coba akses website lain aman aja soalnya.

**Screenshot saat akses nekopoi.care**
![Screenshot_20210523-190641](https://user-images.githubusercontent.com/84452966/119259777-0da3f880-bbfa-11eb-8a83-02d63ea004ff.jpg)

**Screenshot saat akses web lain**
![Screenshot_20210523-190835](https://user-images.githubusercontent.com/84452966/119259905-9458d580-bbfa-11eb-8ba0-c3379ebae781.jpg)
![Screenshot_20210523-190846](https://user-images.githubusercontent.com/84452966/119259912-991d8980-bbfa-11eb-9290-4c0276affd71.jpg)

**Device**
 - OS: [ReloadedOS Android 10]
 - Browser [Chrome, Brave, Via]

**Comment by nxzlem** [comment]
Halo, @Lustsifer.
nekopoi.care sudah digantikan dengan IP terbaru.
Screenshots:
![y0ufmNc](https://i.imgur.com/y0ufmNc.png)
Issuenya akan di tutup dari sementara waktu.
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih.
