### ISSUE TITLE
[REQ] tenor.com

### ISSUE THREAD

**Issue by Lustsifer** [bebasid/bebasid#353]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts

**Keterangan**
Situs tenor.com bisa diakses normal tapi beberapa keyword seperti porn (https://tenor.com/search/porn-gifs) tidak dapat di gunakan untuk mencari gif.

**Screenshot**
![Screenshot_20210526-175623](https://user-images.githubusercontent.com/84452966/119649057-666acf80-be4c-11eb-8789-de1100c9d2d8.jpg)
![Screenshot_20210526-175711](https://user-images.githubusercontent.com/84452966/119649073-6c60b080-be4c-11eb-88e8-5951b07f0d54.jpg)
*Screenshot 1 saat melakukan pencarian tanpa vpn
*Screenshot 2 saat melakukan pencarian dengan vpn

**Comment by nxzlem** [comment]
Bentar saya akan mencobakan lewat komputer/website.
!(DL61exR)[https://i.imgur.com/DL61exR.png]
Saya bisa kok, terus saya check di trustpositif, statusnya tidak memblokir.
!(3GpFa5Z)[https://i.imgur.com/3GpFa5Z.png]

**Comment by Lustsifer** [comment]
Bukan websitenya kak. 

Beberapa kata kunci kalau dicari tidak ditemukan gif tapi kalau pake vpn (atau sejenisnya) pakai kata kunci yang sama dapat ketemu gifnya.

**Comment by nxzlem** [comment]
Ok, saya mau mencoba tambahkan websitenya dari hosts bebasid dulu.
```
54.186.152.33 gateway-tenor-us-west-1.tenor.com
151.101.114.49 media1.tenor.com
13.32.24.4 media.tenor.com
151.101.114.217 qa.tenor.com
142.250.185.193 c.tenor.com
99.86.3.92 g.tenor.com
52.5.181.79 blog.tenor.com
44.235.11.204 api.tenor.com
44.235.11.204 admin-api.tenor.com
52.37.176.73 qa-admin-api.tenor.com
35.83.89.87 dev-api.tenor.com
52.36.111.111 stark.tenor.com
99.86.3.92 touchpal.tenor.com
44.237.206.201 stride-app.tenor.com
35.83.17.88 webview-helpers.tenor.com
13.32.21.112 skypebot.tenor.com
143.204.202.112 facebookbot.tenor.com
52.88.95.44 viberbot.tenor.com
151.101.114.217 www.tenor.com
151.101.130.217 tenor.com
143.204.202.112 facebookbot-webhook.tenor.com
52.5.181.79 www.blog.tenor.com
```

**Comment by nxzlem** [comment]
Baik kak berarti yang saya jawab sebelumnya benar tidak ada di gifs nya pas mencari "porn" nya

**Comment by nxzlem** [comment]
Bisa ditunggu ya kak, kalo sudah bisa nanti saya tutupin issue nya

**Comment by timothydillan** [comment]
Dari melihat request yang dikirim dan diterima oleh client ketika mencari, asumsi sementara saya hal ini terjadi karena tenor "sengaja" ngeblok hal-hal NSFW untuk client yang connect dari Indonesia. Tanpa VPN, ketika saya cek, ternyata ada cookie yang digenerate oleh Tenor yang menyatakan asal negara client (di kasus ini ID [Indonesia]), dan tenor mengirimkan bad response ke client (404).
<img width="632" alt="Tanpa VPN" src="https://user-images.githubusercontent.com/55008869/119858229-d9f10780-bf46-11eb-90a5-b4a916f80035.png">

Ketika menggunakan VPN, dapat dilihat bahwa cookienya berubah, sesuai dengan negara yang diset di VPNnya (Singapur) dan GIF dapat dilihat, serta respons yang dikirimkan beda. 
<img width="933" alt="VPN" src="https://user-images.githubusercontent.com/55008869/119858420-086ee280-bf47-11eb-97a7-ff2af6a7e94e.png">

**Comment by nxzlem** [comment]
> Dari melihat request yang dikirim dan diterima oleh client ketika mencari kata kunci yang dilampirkan, asumsi sementara saya hal ini terjadi karena tenor "sengaja" ngeblok hal-hal NSFW untuk client yang connect dari Indonesia. Tanpa VPN, ketika saya cek, ternyata ada cookie yang digenerate oleh Tenor yang menyatakan asal negara client (di kasus ini ID [Indonesia]), dan tenor mengirimkan bad response ke client (404).
> <img alt="Tanpa VPN" width="632" src="https://user-images.githubusercontent.com/55008869/119858229-d9f10780-bf46-11eb-90a5-b4a916f80035.png">
> 
> Ketika menggunakan VPN, dapat dilihat bahwa cookienya berubah, sesuai dengan negara yang diset di VPNnya (Singapur) dan GIF dapat dilihat, serta respons yang dikirimkan beda (tidak error).
> <img alt="VPN" width="933" src="https://user-images.githubusercontent.com/55008869/119858420-086ee280-bf47-11eb-97a7-ff2af6a7e94e.png">

Nah betul kak, info yg sangat betul ini.

**Comment by timothydillan** [comment]
> Nah betul kak, info yg sangat betul ini. Saya menemukan beberapa hal ini ada di berita luarnya.
> ![3CKg03A](https://camo.githubusercontent.com/020cc3c810baeed8ae48d98218741da7fe474bdbe00865c2ef568b37e2254c52/68747470733a2f2f692e696d6775722e636f6d2f33434b673033412e706e67)
> Tapi cara mengatasi kayak begitu bagaimana kak?

Nah ini saya kurang tahu gimana cara betulinnya 😂, saya juga kurang banyak pengalaman kalau udah ke dunia networking. Saya mengasumsikan tenor menentukan countryCodenya berdasarkan IP dari client, jadi modifikasi dari /etc/hosts mungkin gak bisa. Satu-satunya workaround adalah menggunakan VPN atau aplikasi seperti https://1.1.1.1/ dan semacamnya agar IPnya berubah. Sepertinya masalah seperti ini sudah di luar scope project bebasid, kecuali ada cara lain yang bisa diimplementasikan ke /etc/hostsnya agar bisa membenarkan masalah ini.

**Comment by nxzlem** [comment]
Baik terimakasih kak, terimakasih. Halo @Lustsifer, bagaimana dengan @timothydillan yang bisa dijawabkan?
