### ISSUE TITLE
[BUG] i.stack.imgur.com

### ISSUE THREAD

**Issue by Syakhisk** [bebasid/bebasid#354]
**Deskripsi mengenai bug**
muncul error `Secure Connection Failed` ketika visit `i.stack.imgur.com`.

**Screenshot**
![image](https://user-images.githubusercontent.com/63556086/119905392-61a23a80-bf76-11eb-8ebd-0317b270981e.png)

**Device**
 - OS: Ubuntu 20.04
 - Browser: Firefox

**Comment by nxzlem** [comment]
Halo, @Syakhisk.
imgur.com sudah digantikan dengan IP terbaru dan ditambahkan subdomain lain.
Issuenya akan di tutup dari sementara waktu.
Kalo mau komen silakan aja ya, tanya sesuatu kalo ada yang gak benar, dll. Boleh ditutup issue sekarang atau senantinya.
Terimakasih.
