### ISSUE TITLE
[BUG] subscene.com

### ISSUE THREAD

**Issue by ErwinAvrio** [bebasid/bebasid#357]
**Deskripsi mengenai bug**
ga bisa masuk subscene ( keterangannya can't reach this page) untuk lebih jelasnya,silahkan liat screenshootnya

**Screenshot**
![bug subsene](https://user-images.githubusercontent.com/64609493/120105986-73a5f800-c185-11eb-88b9-e02227a95963.png)

**Device**
 - OS: Windows 10
 - Browser : Microsoft edge

**Comment by kuzunagi** [comment]
coba www.subscene.com karena saya jg pernah kayak gitu dan work dengan memakai www

**Comment by ErwinAvrio** [comment]
> coba [www.subscene.com](http://www.subscene.com) karena saya jg pernah kayak gitu dan work dengan memakai www

barusan nyoba,ga work di ane.. :(

**Comment by kuzunagi** [comment]
> > coba [www.subscene.com](http://www.subscene.com) karena saya jg pernah kayak gitu dan work dengan memakai www
> 
> barusan nyoba,ga work di ane.. :(

coba flushdnsnya dengan cara masukkan kode dibawah di cmd, kalau enggak work bisa comment lg <(＿　＿)>
`ipconfig /release
ipconfig /renew
ipconfig /flushdns`

**Comment by nxzlem** [comment]
Silakan coba lagi kak, kalo gak bisa mungkin harus di flushdns dlu

**Comment by ErwinAvrio** [comment]
kok error gan? apa ada yang salah ya?
![error](https://user-images.githubusercontent.com/64609493/120481834-b8769c80-c3da-11eb-8154-d0c4781feff9.png)


> > > coba [www.subscene.com](http://www.subscene.com) karena saya jg pernah kayak gitu dan work dengan memakai www
> > 
> > 
> > barusan nyoba,ga work di ane.. :(
> 
> coba flushdnsnya dengan cara masukkan kode dibawah di cmd, kalau enggak work bisa comment lg <(＿　＿)>
> `ipconfig /release ipconfig /renew ipconfig /flushdns`

**Comment by ErwinAvrio** [comment]
> > > coba [www.subscene.com](http://www.subscene.com) karena saya jg pernah kayak gitu dan work dengan memakai www
> > 
> > 
> > barusan nyoba,ga work di ane.. :(
> 
> coba flushdnsnya dengan cara masukkan kode dibawah di cmd, kalau enggak work bisa comment lg <(＿　＿)>
> `ipconfig /release ipconfig /renew ipconfig /flushdns`

![error](https://user-images.githubusercontent.com/64609493/120482331-3a66c580-c3db-11eb-8d12-212b33f27858.png)
ga bisa gan

**Comment by pandamoon21** [comment]
> > > > coba [www.subscene.com](http://www.subscene.com) karena saya jg pernah kayak gitu dan work dengan memakai www
> > > 
> > > 
> > > barusan nyoba,ga work di ane.. :(
> > 
> > 
> > coba flushdnsnya dengan cara masukkan kode dibawah di cmd, kalau enggak work bisa comment lg <(＿　＿)>
> > `ipconfig /release ipconfig /renew ipconfig /flushdns`
> 
> ![error](https://user-images.githubusercontent.com/64609493/120482331-3a66c580-c3db-11eb-8d12-212b33f27858.png)
> ga bisa gan

Diinput satu-satu per command,
`ipconfig /release`
`ipconfig /renew`
`ipconfig /flushdns`
Semoga membantu..

**Comment by ErwinAvrio** [comment]
> > > > > coba [www.subscene.com](http://www.subscene.com) karena saya jg pernah kayak gitu dan work dengan memakai www
> > > > 
> > > > 
> > > > barusan nyoba,ga work di ane.. :(
> > > 
> > > 
> > > coba flushdnsnya dengan cara masukkan kode dibawah di cmd, kalau enggak work bisa comment lg <(＿　＿)>
> > > `ipconfig /release ipconfig /renew ipconfig /flushdns`
> > 
> > 
> > ![error](https://user-images.githubusercontent.com/64609493/120482331-3a66c580-c3db-11eb-8d12-212b33f27858.png)
> > ga bisa gan
> 
> Diinput satu-satu per command,
> `ipconfig /release`
> `ipconfig /renew`
> `ipconfig /flushdns`
> Semoga membantu..

tq gan

**Comment by ErwinAvrio** [comment]
> > > coba [www.subscene.com](http://www.subscene.com) karena saya jg pernah kayak gitu dan work dengan memakai www
> > 
> > 
> > barusan nyoba,ga work di ane.. :(
> 
> coba flushdnsnya dengan cara masukkan kode dibawah di cmd, kalau enggak work bisa comment lg <(＿　＿)>
> `ipconfig /release ipconfig /renew ipconfig /flushdns`

masi ga work gan..:(

**Comment by nxzlem** [comment]
> > > > coba [www.subscene.com](http://www.subscene.com) karena saya jg pernah kayak gitu dan work dengan memakai www
> > > 
> > > 
> > > barusan nyoba,ga work di ane.. :(
> > 
> > 
> > coba flushdnsnya dengan cara masukkan kode dibawah di cmd, kalau enggak work bisa comment lg <(＿　＿)>
> > `ipconfig /release ipconfig /renew ipconfig /flushdns`
> 
> masi ga work gan..:(

Coba pake manual aja di C:\Windows\system32\etc\driver\hosts

**Comment by ErwinAvrio** [comment]
> > > > > coba [www.subscene.com](http://www.subscene.com) karena saya jg pernah kayak gitu dan work dengan memakai www
> > > > 
> > > > 
> > > > barusan nyoba,ga work di ane.. :(
> > > 
> > > 
> > > coba flushdnsnya dengan cara masukkan kode dibawah di cmd, kalau enggak work bisa comment lg <(＿　＿)>
> > > `ipconfig /release ipconfig /renew ipconfig /flushdns`
> > 
> > 
> > masi ga work gan..:(
> 
> Coba pake manual aja di C:\Windows\system32\etc\driver\hosts pakai notepad/notepad++ adminstrator terus salin hosts bebasid lewat raw github

ok..udah bisa..tq yah

**Comment by nxzlem** [comment]
> > > > > > coba [www.subscene.com](http://www.subscene.com) karena saya jg pernah kayak gitu dan work dengan memakai www
> > > > > 
> > > > > 
> > > > > barusan nyoba,ga work di ane.. :(
> > > > 
> > > > 
> > > > coba flushdnsnya dengan cara masukkan kode dibawah di cmd, kalau enggak work bisa comment lg <(＿　＿)>
> > > > `ipconfig /release ipconfig /renew ipconfig /flushdns`
> > > 
> > > 
> > > masi ga work gan..:(
> > 
> > 
> > Coba pake manual aja di C:\Windows\system32\etc\driver\hosts pakai notepad/notepad++ adminstrator terus salin hosts bebasid lewat raw github
> 
> ok..udah bisa..tq yah

Oke, masama.
