### ISSUE TITLE
[BUG] Tidak dapat memperbarui file hosts, error tertulis : "The request was aborted: Could not create SSL/TLS secure channel"

### ISSUE THREAD

**Issue by arunstop** [bebasid/bebasid#358]
**Deskripsi mengenai bug**
Tidak dapat memperbarui file hosts. Pada saat memilih perintah "Y/N/D/E/W", semua opsi sudah tercoba, hasilnya, mengeluarkan error yang sama.

**Screenshot**
![Screenshot_192](https://user-images.githubusercontent.com/10150211/120186557-da86e800-c23d-11eb-955a-767e9148ca11.png)

**Device**
 - OS: Windows 7
 - Browser Chrome

**Comment by nxzlem** [comment]
Mungkin anda belum diupdate NET. Framwork versi terbaru. Silakan update lagi [disini](https://dotnet.microsoft.com/download/dotnet-framework).

**Comment by nxzlem** [comment]
Mungkin ini bisa menambahkan kode dalam ini
```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

**Comment by nxzlem** [comment]
Silakan pakai Manual saja dulu untuk Windows 7nya. Terimakasih.
Bisa buka pakai Notepad++/Notepad biasa, lokasinya di C:\Windows\system32\driver\etc\hosts.
