### ISSUE TITLE
[REQ] telegra.ph

### ISSUE THREAD

**Issue by pandamoon21** [bebasid/bebasid#359]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts

**Keterangan**
Web telegra.ph tidak bisa diakses lewat jaringan indihome. Saya coba akses dengan vpn bisa dibuka.
Untuk tambahan, saya juga tidak bisa mengunduh gambar di telegram desktop di kondisi tertentu, kasus pertama saya bisa mengunduh gambar yg dikirim oleh user asal Indonesia, di kasus lain ketika saya mau mengunduh gambar yang dikirim oleh user asal Russia, progress download tidak jalan.

Web contoh: https://telegra.ph/Tes-BebasID-06-01

**Comment by nxzlem** [comment]
!(fgZ1kgr)[https://i.imgur.com/fgZ1kgr.png]

**Comment by nxzlem** [comment]
Silakan coba lagi, kalo bisa. Bisa di tutupkan issuenya.

**Comment by pandamoon21** [comment]
Terima kasih sudah di update, tetapi setelah saya add ke hosts tetap tidak bisa diakses.
Saya coba ping ke telegra.ph selalu RTO, saya coba lewat android karena saya pikir ada yg bermasalah di pc saya tetapi hasilnya sama saja (This site can't be reached).

**Comment by pandamoon21** [comment]
Update: Beberapa orang yang ditanya dengan jaringan indihome, sama-sama tidak bisa mengakses web telegra.ph sampai saat ini.

**Comment by nxzlem** [comment]
> Terima kasih sudah di update, tetapi setelah saya add ke hosts tetap tidak bisa diakses.
> Saya coba ping ke telegra.ph selalu RTO, saya coba lewat android karena saya pikir ada yg bermasalah di pc saya tetapi hasilnya sama saja (This site can't be reached).
> 
> Saya coba buka dengan vpn benar-benar bisa terbuka, ketika dimatikan tidak bisa lagi.

Sudah ditambahkan hosts masih tidak bisa diakses?

**Comment by nxzlem** [comment]
Ternyata tidak bisa akses pas ditambahkan situsnya

**Comment by nxzlem** [comment]
Mohon Maaf, saya sudah check di trustpositif, hasilnya tidak memblokir. Saya tidak tahu kenapa tidak bisa konek ke telegra.ph. Maaf ya, saya akan ditutupkan issuenya sekarang. Terimakasih.

**Comment by nxzlem** [comment]
Update: Sudah bisa memakai telegra.ph lagi.
