### ISSUE TITLE
[BUG] luscious.net

### ISSUE THREAD

**Issue by wolvenworks** [bebasid/bebasid#360]
udh cek di trustpositif confirm diblok

**Comment by nxzlem** [comment]
> udh cek di trustpositif confirm diblok

Oke, sabar ya. Nanti saya menambahkan di hosts bebasid.

**Comment by nxzlem** [comment]
Halo, @wolvenworks.
luscious.net sudah digantikan dengan IP terbaru dan sudah menambahkan subdomainnya.
Issuenya akan nanti di tutup dari sementara waktu.
Mau komen atau saran boleh kapanpun saja, apabila tanya sesuatu kalo ada yang tidak ada yang benar atau masalah, dllnya. Kalo situsnya sudah bisa, boleh silakan ditutupkan issuenya sekarang atau senantinya.
Pas sudah 7 hari, nanti saya akan ditutupkan issuenya.
Terimakasih.

**Comment by wolvenworks** [comment]
ok mantep gw dah DL latest hosts udh bisa skarang ty

**Comment by nxzlem** [comment]
> ok mantep gw dah DL latest hosts udh bisa skarang ty

Yoi, masama gan
