### ISSUE TITLE
[REQ] hitprn.com

### ISSUE THREAD

**Issue by jumanji778** [bebasid/bebasid#361]
www.hitprn.com

**Comment by nxzlem** [comment]
Halo, @jumanji778.
hitprn.com sudah ditambahkan dari hosts bebasid.
Issuenya akan nanti di tutup dari sementara waktu.
Mau komen atau saran boleh kapanpun saja, apabila tanya sesuatu kalo ada yang tidak ada yang benar atau masalah, dllnya. Kalo situsnya sudah bisa, boleh silakan ditutupkan issuenya sekarang atau senantinya.
Pas sudah 7 hari, nanti saya akan ditutupkan issuenya.
Terimakasih.
