### ISSUE TITLE
[REQ] sg.apexmc.co

### ISSUE THREAD

**Issue by zamzamzhafry** [bebasid/bebasid#362]
alamat IP adalah server hosting minecraft Apex Hosting yang mana ketika di akses melalui ISP merah susah terhubung dan mendapatkan ping merah kemudian selalu timed out. ada kecurigaan di kawan-kawan gamer koneksi di manipulasi oleh hosting sebelah yang tersaingi karena layanan yang lebih murah

**Comment by nxzlem** [comment]
Ok, sudah ditambahkan. Silakan coba lagi.

**Comment by nxzlem** [comment]
Issuenya akan nanti di tutup dari sementara waktu.
Mau komen atau saran boleh kapanpun saja, apabila tanya sesuatu kalo ada yang tidak ada yang benar atau masalah, dllnya. Kalo situsnya sudah bisa, boleh silakan ditutupkan issuenya sekarang atau senantinya.
Pas sudah 7 hari, nanti saya akan ditutupkan issuenya.
Terimakasih.

**Comment by nxzlem** [comment]
![SoRrU1h](https://i.imgur.com/SoRrU1h.png)
