### ISSUE TITLE
[BUG] Socket binance.com

### ISSUE THREAD

**Issue by fyfirman** [bebasid/bebasid#363]
**Deskripsi mengenai bug**
Binance.com berhasil dibuka dengan bebas.id, tetapi ketika masuk ke halaman trade yang menggunakan socket beberapa fitur realtime nya tidak berjalan. Apakah bebasid dapat menghandle blocked socket?

**Screenshot**
Issue pada tab `network` di chrome debugger.
![image](https://user-images.githubusercontent.com/37064641/121294475-a97e7580-c917-11eb-9785-bdb432ead595.png)

Console
![image](https://user-images.githubusercontent.com/37064641/121294616-e3e81280-c917-11eb-88d2-36031e03e6cf.png)

**Device**
 - OS: Ubuntu 20.04
 - Browser : Chrome

**Comment by nxzlem** [comment]
Ok, sudah ditambahkan sama diganti dengan ip baru. Silakan coba lagi.

**Comment by fyfirman** [comment]
Work. Terimakasih banyak bang @nxzlem !

**Comment by nxzlem** [comment]
> Work. Terimakasih banyak bang @nxzlem !

Oke, Masama bang. @fyfirman
