### ISSUE TITLE
[REQ] bokepindohot.pw

### ISSUE THREAD

**Issue by neeyooo** [bebasid/bebasid#364]
93.104.211.211 bokepindohot.pw

**Comment by nxzlem** [comment]
Halo, @neeyooo.
bokepindohot.pw sudah ditambahkan dari hosts bebasid.
Issuenya akan nanti di tutup dari sementara waktu.
Mau komen atau saran boleh kapanpun saja, apabila tanya sesuatu kalo ada yang tidak ada yang benar atau masalah, dllnya. Kalo situsnya sudah bisa, boleh silakan ditutupkan issuenya sekarang atau senantinya.
Pas sudah 7 hari, nanti saya akan ditutupkan issuenya.
Terimakasih.

**Comment by nxzlem** [comment]
![vZVy7WC](https://i.imgur.com/vZVy7WC.png)
