### ISSUE TITLE
Gak bisa akses apa-apa kecuali Reddit.com

### ISSUE THREAD

**Issue by vercouver** [bebasid/bebasid#365]
Gak bisa akses apa-apa kecuali Reddit.

![image](https://user-images.githubusercontent.com/31980809/121697368-91694a80-caff-11eb-9cbf-3919b43501cf.png)

**Device**
 - OS: Win 10
 - Browser : Chrome

**Comment by vercouver** [comment]
Gak bisa akses apa-apa kecuali reddit. Redgifs juga salah satunya.

**Comment by nxzlem** [comment]
> Gak bisa akses apa-apa kecuali reddit. Redgifs juga salah satunya.

Udah di coba perbarui hosts bebasid blm?

**Comment by vercouver** [comment]
Sudah dicoba buat update manual, semuanya bisa diakses tinggal redgifs aja.
![image](https://user-images.githubusercontent.com/31980809/121757805-54c63f00-cb51-11eb-9643-44c9d11d937c.png)

![image](https://user-images.githubusercontent.com/31980809/121757847-8939fb00-cb51-11eb-8c97-ebacd1ff85e2.png)

Sudah coba buat flushdns sebelum manual update, masih belum berubah.

**Comment by nxzlem** [comment]
> Sudah dicoba buat update manual, semuanya bisa diakses tinggal redgifs aja.
> ![image](https://user-images.githubusercontent.com/31980809/121757805-54c63f00-cb51-11eb-9643-44c9d11d937c.png)
> 
> ![image](https://user-images.githubusercontent.com/31980809/121757847-8939fb00-cb51-11eb-8c97-ebacd1ff85e2.png)
> 
> Sudah coba buat flushdns sebelum manual update, masih belum berubah.

Oke, nanti saya akan diperbarukan redgifs.com nya. Terimakasih

**Comment by nxzlem** [comment]
Sudah kak, silakan update lagi hostsnya. Terimakasih.

**Comment by vercouver** [comment]
Oke kak, sudah bisa lagi. Terima kasih.
