### ISSUE TITLE
[REQ] live-nba.stream

### ISSUE THREAD

**Issue by muzzin-ctrl** [bebasid/bebasid#366]
di android bisa kebuka , 
tp di laptop gak bisa ..

**Comment by nxzlem** [comment]
Ok, sudah ditambahkan. Silakan coba lagi.
Issuenya akan nanti di tutup dari sementara waktu.
Mau komen atau saran boleh kapanpun saja, apabila tanya sesuatu kalo ada yang tidak ada yang benar atau masalah, dllnya. Kalo situsnya sudah bisa, boleh silakan ditutupkan issuenya sekarang atau senantinya.
Pas sudah 7 hari, nanti saya akan ditutupkan issuenya.
Terimakasih.

**Comment by muzzin-ctrl** [comment]
![nba](https://user-images.githubusercontent.com/78278322/122321597-4e1f3980-cf4e-11eb-9901-b68663127600.png)

masih gak bisa nih

**Comment by nxzlem** [comment]
> ![nba](https://user-images.githubusercontent.com/78278322/122321597-4e1f3980-cf4e-11eb-9901-b68663127600.png)
> 
> masih gak bisa nih

berarti ininya https://freefeds.com/stream/111166.html

**Comment by muzzin-ctrl** [comment]
tp di android kok bisa yah , cuma di pc aja nih

**Comment by nxzlem** [comment]
oke, ini sudah ya. coba ulang lagi

**Comment by nxzlem** [comment]
Mohon maaf, Issuenya saya akan tutupin ya sudah lebihi 7 hari. Terimakasih.
