### ISSUE TITLE
[BUG] www.reddit.com

### ISSUE THREAD

**Issue by blackjacksme** [bebasid/bebasid#367]
**Deskripsi mengenai bug**
kemarin pake ini lancar aja, tapi hari ini **www**.reddit.com jadi ga bisa dibuka.
Anehnya **old**.reddit.com dan **new**.reddit.com masih bisa, masalahnya kalo pake google link ke reddit pake **www** semua.
Pake anonymoX/ip proxy masih bisa buka link **www**

**Screenshot**
![image](https://user-images.githubusercontent.com/4676384/122239799-7164cd00-ceeb-11eb-9406-8f04dbe988d1.png)

**Device**
 - OS: Windows 10
 - Browser: Chrome, Firefox, Edge

**Comment by nxzlem** [comment]
Oke, sudah bisa belum websitenya? Coba diperbarui lagi hostsnya.

**Comment by blackjacksme** [comment]
sip mantap udah bisa

**Comment by nxzlem** [comment]
> sip mantap udah bisa

Baik, terimakasih.
