### ISSUE TITLE
[REQ] en.fullmatchsports.co

### ISSUE THREAD

**Issue by muzzin-ctrl** [bebasid/bebasid#369]
perubahan dari fullmatchsports.co

**Comment by nxzlem** [comment]
Oke, silakan coba lagi kak. Terimakasih.

**Comment by nxzlem** [comment]
Mohon maaf, Issuenya saya akan tutupin ya, sudah lebihi 7 hari. Terimakasih.
Kalo masih ada masalah bisa dibukain issuenya.
Terimakasih.
