### ISSUE TITLE
[REQ] hesgoal.tv

### ISSUE THREAD

**Issue by muzzin-ctrl** [bebasid/bebasid#370]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts

**Comment by nxzlem** [comment]
Ok, websitenya sudah ditambahkan di hosts bebasid. Silakan coba lagi.
Issuenya nanti di tutup dari beberapa waktu dalam 7 hari atau lebihan.
Kalo mau saran komen, boleh kapanpun saja, apabila tanya sesuatu kalo ada yang tidak ada yang benar. 
Kalo situsnya sudah bisa, Anda boleh ditutupkan Issuenya.
Kalo sudah 7 hari tidak dikomen (sudah bisa), issue ini akan ditutup.
Terimakasih.

**Comment by nxzlem** [comment]
Oke sudah melebihi batas 7 hari, saya akan tutupkan issuenya ya. Terimakasih. Kalo mau komen silakan buka issuenya lagi.
