### ISSUE TITLE
[BUG] streamable.com

### ISSUE THREAD

**Issue by heywolf15** [bebasid/bebasid#371]
Needs to be updated.

**Comment by nxzlem** [comment]
Ok, now try again. (Ok, sekarang coba lagi.)

**Comment by heywolf15** [comment]
I think it got Geo lock. I can only open it with VPN

**Comment by timothydillan** [comment]
> I think it got Geo lock. I can only open it with VPN

Nope. Works fine for me. Have you updated your hosts file with the newly added IP addresses?

**Comment by heywolf15** [comment]
> 
> 
> > I think it got Geo lock. I can only open it with VPN
> 
> Nope. Works fine for me. Have you updated your hosts file with the newly added IP addresses?

Before and after the update, still saying this.

Secure Connection Failed

An error occurred during a connection to streamable.com. PR_CONNECT_RESET_ERROR

**Comment by nxzlem** [comment]
> > > I think it got Geo lock. I can only open it with VPN
> > 
> > 
> > Nope. Works fine for me. Have you updated your hosts file with the newly added IP addresses?
> 
> Before and after the update, still saying this.
> 
> Secure Connection Failed
> 
> An error occurred during a connection to streamable.com. PR_CONNECT_RESET_ERROR

https://support.mozilla.org/en-US/questions/1280856
That's because there's firewall antivirus software on your computer. Try turning off every buttons in the antivirus settings.

**Comment by nxzlem** [comment]
Or maybe try removing/turn off extension on your browser.

**Comment by nxzlem** [comment]
I already checked and updated all streamable links with new IP and you still getting errors, that's because you have a firewall or any extensions installed must be a problem. Try by solving turn off firewall and remove every single extension.

**Comment by heywolf15** [comment]
Disable all the extensions and firewall. I'm using windows security. I even try to use Dnscrypt.
I can't even open it on the phone with Dnscrypt.
I'm always doing a manual hosts.

https://www.minitool.com/news/troubleshoot-secure-connection-failed-error.html

**Comment by nxzlem** [comment]
> Disable all the extensions and firewall. I'm using windows security. I even try to use Dnscrypt.
> I can't even open it on the phone with Dnscrypt.
> I'm always doing a manual hosts.
> 
> https://www.minitool.com/news/troubleshoot-secure-connection-failed-error.html

Try clearing all cookies/cache data it'll result work
or even try reset ipconfig on cmd

**Comment by nxzlem** [comment]
> Disable all the extensions and firewall. I'm using windows security. I even try to use Dnscrypt.
> I can't even open it on the phone with Dnscrypt.
> I'm always doing a manual hosts.
> 
> https://www.minitool.com/news/troubleshoot-secure-connection-failed-error.html

Alright, is it fixed right now?

**Comment by heywolf15** [comment]
> Alright, is it fixed right now?
> Ok since it didn't respond, I will close the issue now. thank you for your time.

it's not, even after i flush dns and reset the ip.
Sorry I forgot to respond.

**Comment by nxzlem** [comment]
> > Alright, is it fixed right now?
> > Ok since it didn't respond, I will close the issue now. thank you for your time.
> 
> it's not, even after i flush dns and reset the ip.
> Sorry I forgot to respond.

Try switching browsers

**Comment by heywolf15** [comment]
> 
> 
> > > Alright, is it fixed right now?
> > > Ok since it didn't respond, I will close the issue now. thank you for your time.
> > 
> > 
> > it's not, even after i flush dns and reset the ip.
> > Sorry I forgot to respond.
> 
> Try switching browsers.

yeah I'm still trying to fix this FIrefox browser. thank you.
I'm going to close this.

**Comment by nxzlem** [comment]
> > > > Alright, is it fixed right now?
> > > > Ok since it didn't respond, I will close the issue now. thank you for your time.
> > > 
> > > 
> > > it's not, even after i flush dns and reset the ip.
> > > Sorry I forgot to respond.
> > 
> > 
> > Try switching browsers.
> 
> yeah I'm still trying to fix this FIrefox browser. thank you.
> I'm going to close this.

Okay, no problem. Thank you for your time.
