### ISSUE TITLE
[BUG] danbooru.donmai.us

### ISSUE THREAD

**Issue by hanahaneull** [bebasid/bebasid#373]
**Deskripsi mengenai bug**
Preview image tidak dapat di load. [Contoh](https://cdn.donmai.us/preview/91/5e/915ea9dd00bf7fb176a4d2fadb769868.jpg)
Sudah dipastikan preview image danbooru tidak dalam kondisi `Offline`, dikarenakan gambar dapat difetch oleh Discord
Original image dapat diload tanpa masalah.

**Screenshot**
Discord:
![Discord](https://cdn.upload.systems/uploads/ZA0zmrhv.png)
CURL:
![curl](https://cdn.upload.systems/uploads/s57GmQTX.png)

**Device**
 - OS: Arch Linux
 - Browser: Firefox (DOH Cloudflare)

**Comment by nxzlem** [comment]
Oke sudah ya, perbarui dulu file hostsnya di komputer anda.
