### ISSUE TITLE
[REQ] Pembuatan Magisk Module

### ISSUE THREAD

**Issue by ModiFlasher** [bebasid/bebasid#374]
Gan bisa gk buatin module magisk nya buat support android ?

**Comment by gvoze32** [comment]
sepertinya masih susah soalnya harus mengubah struktur hostsnya dulu jadi one ip one domain, karena hosts bebasid terkadang masih ada yang menggunakan one ip multiple domain, jadinya akan cukup memakan waktu

mungkin nanti bakal dibuatin program convertnya dulu, kalo itu sudah jadi, makan pembuatan module magisk jadi memungkinkan

**Comment by nxzlem** [comment]
Iya jadi, agak susah membuatnya sih.

**Comment by ModiFlasher** [comment]
Lapor setelah saya nemu Magisk Module Adblock ini dan replace file host nya pake bebasid ternyata work
[hosts_v16.4.zip](https://github.com/bebasid/bebasid/files/6795301/hosts_v16.4.zip)

**Comment by nxzlem** [comment]
> Lapor setelah saya nemu Magisk Module Adblock ini dan replace file host nya pake bebasid ternyata work
> [hosts_v16.4.zip](https://github.com/bebasid/bebasid/files/6795301/hosts_v16.4.zip)

Ok, nice. Selanjutnya gimana?

**Comment by nxzlem** [comment]
[bebasidhosts_v1.0.0_10_07_2021.zip](https://github.com/bebasid/bebasid/files/6795499/bebasidhosts_v1.0.0_10_07_2021.zip)
nih sudah dibikin lewat saya. kalo ada masalah bilang saja

**Comment by nxzlem** [comment]
Sudah di add di github release, cek aja kalo butuh

**Comment by ModiFlasher** [comment]
Sorry baru buka sekarang udah work sekarang pake Magisk Module yg ente buat

**Comment by nxzlem** [comment]
> Sorry baru buka sekarang udah work sekarang pake Magisk Module yg ente buat

Wokeh
