### ISSUE TITLE
green tunnel sudah diinstall "Install Dulu Green-Tunnelnya"

### ISSUE THREAD

**Issue by ridwantanjung** [bebasid/bebasid#38]
#### Pertama 
udah coba install green tunnel manual `npm install -g green-tunnel`
pas jalananin `bebasid-gt start` muncul pesan "Install Dulu Green-Tunnelnya",

#### Kedua
saya coba uninstall green-tunnelnya, trus coba run `bebasid-gt install`, done,
dan jalanin lagi `bebasid-gt start` masih tetep muncul pesan "Install Dulu Green-Tunnelnya",

pas di check sesuai di script bash `/usr/bin/gt` emang gaada directory/file `gt`

**Any Ideas ?**

**FMI :**
`# bebasid-gt gete`
`> There is no screen to be resumed matching 6f4f9a675d5c67aa28350b0276bf911d.`

**Comment by icaksh** [comment]
Apa distro linux yg dipakai? Karena untuk Turunan Debian sendiri masih dalam tahap ujicoba, baru tested di Manjaro

**Comment by icaksh** [comment]
`command -v gt`

**Comment by icaksh** [comment]
sudah ada update baru untuk bash gt.. silahkan dicoba.

**Comment by ridwantanjung** [comment]
@icaksh sudah bisa, tpi netflix tetep gabisa dibuka, loading terus, mungkin IP netflix salah ?
