### ISSUE TITLE
[BUG] binance.com

### ISSUE THREAD

**Issue by monixL** [bebasid/bebasid#381]
Price tidak update secara real time

**Comment by nxzlem** [comment]
> Price tidak update secara real time

Bisa kasih link domain/subdomain-nya?

**Comment by monixL** [comment]
> > Price tidak update secara real time
> 
> Boleh bisa jelasin informasinya untuk subdomain binance?

![image](https://user-images.githubusercontent.com/52873193/128122052-64e98224-e342-45cb-b816-af1ebe1acb61.png)
Ini versi aplikasi desktop Binance. Normalnya pricenya berubah tiap detik. Ini nggk merespon sama sekali.

**Comment by nxzlem** [comment]
> > > Price tidak update secara real time
> > 
> > 
> > Boleh bisa jelasin informasinya untuk subdomain binance?
> 
> ![image](https://user-images.githubusercontent.com/52873193/128122052-64e98224-e342-45cb-b816-af1ebe1acb61.png)
> Ini versi aplikasi desktop Binance. Normalnya pricenya berubah tiap detik. Ini nggk merespon sama sekali.

Ini perbaikan gimana kak? Ganti semua IP domainnya?

**Comment by monixL** [comment]
> > > > Price tidak update secara real time
> > > 
> > > 
> > > Boleh bisa jelasin informasinya untuk subdomain binance?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/52873193/128122052-64e98224-e342-45cb-b816-af1ebe1acb61.png)
> > Ini versi aplikasi desktop Binance. Normalnya pricenya berubah tiap detik. Ini nggk merespon sama sekali.
> 
> Ini perbaikan gimana kak? Ganti semua IP domainnya?

Coba cek aja dulu. Mungkin ada beberapa IP yg berubah

**Comment by nxzlem** [comment]
Oke udah ya, coba perbarui hosts lagi. @monixL.
