### ISSUE TITLE
[REQ] example.com

### ISSUE THREAD

**Issue by AlberttFrgk** [bebasid/bebasid#383]
# [semprot.com]
104.21.234.221 www.semprot.com
104.21.234.221 ww.semprot.com
104.21.234.220 www.semprot.com
104.21.234.220 ww.semprot.com

**Comment by nxzlem** [comment]
Oke, sudah ditambahin ke hosts bebasid ya. Jangan lupa update hosts dulu, terimakasih!
Issue nya akan ditutup dalam beberapa 7 hari.

**Comment by syahti** [comment]
Nyimak nunggu ip baru

**Comment by nxzlem** [comment]
> Nyimak nunggu ip baru

Wkwwk, sudah pak
