### ISSUE TITLE
[REQ] qwant.com

### ISSUE THREAD

**Issue by franksling** [bebasid/bebasid#385]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts

Tolong ya kak,

**Comment by nxzlem** [comment]
![8TkPsJB](https://i.imgur.com/8TkPsJb.png)
Permisi, saya barusan check di trustpositif, statusnya tidak ada.

**Comment by nxzlem** [comment]
Oke kalo gak bisa, saya sudah ditambahin ke hosts bebasid ya. Jangan lupa update hosts dulu, terimakasih!
Issue nya akan ditutup dalam beberapa 7 hari.

**Comment by nxzlem** [comment]
Update: Kayanya ini tidak bisa difix karena asal negara client (di kasus ini ID [Indonesia]) makanya tidak boleh.

**Comment by nxzlem** [comment]
Saya tunggu jawaban anda, kalo anda sudah tau, saya akan tutupkan issuenya. Terimakasih.

**Comment by franksling** [comment]
@nxzlem ohhh gitu baik baik kak terima kasih

**Comment by nxzlem** [comment]
> @nxzlem ohhh gitu baik baik kak terima kasih

Sip, saya akan tutup issuenya
