### ISSUE TITLE
[REQ] fapopedia.net

### ISSUE THREAD

**Issue by rufusw02** [bebasid/bebasid#387]
Belum ada di hosts

Terima kasih

**Comment by nxzlem** [comment]
Oke, sudah ditambahin ke hosts bebasid ya. Jangan lupa diupdate hosts terlebih dahulu. Terimakasih!

**Comment by rufusw02** [comment]
Sudah bisa! Terima kasih banyak!

**Comment by nxzlem** [comment]
> Sudah bisa! Terima kasih banyak!

Sama-sama!
