### ISSUE TITLE
[BUG] reddit.com redirect ke IPO pada KaiOS rooted

### ISSUE THREAD

**Issue by nattadasu** [bebasid/bebasid#388]
**Deskripsi mengenai bug**
Saat menggunakan _hosts_ bebasid yang juga bersamaan dengan berkas _hosts_ milik Energized (Energized Basic Protection dan Energized Regional Extension), Reddit tidak dapat diakses, dan langsung _redirect_/dialihkan ke Internet Positif.

Untuk akses ke situs lainnya (NSFW) dapat dilewati.

Posisi _hosts_ bebasid berada paling atas. Opsi `localhost` di bebasid dihapus karena Energized sudah mendaftarkannya, dan _untick_ komentar untuk fitur _SafeSearch_ Google dan YouTube

**Device**
 - OS: Advan Hape Online (Model: 2406, Rooted), KaiOS 2.5.2 `200420R2`
 - Browser: KaiOS 2.5.2 (Firefox Gecko 48)

**Comment by nxzlem** [comment]
Sudah diperbaruikan hostsnya?

**Comment by nattadasu** [comment]
Untuk hostnya, saya ambil dari commit a311cf60f63287eb2e9e68abd40a3fb0905e32ff, bukan yang terbaru (88160f9a93c4a031c1b6f6f6819642edac5e2225). Akan saya kabari kembali besok pagi, karena saya lagi tidak dapat akses laptop.

Jika masih ada kendala, pertanyaan saya adalah, apakah host dari Energized juga memengaruhi ini?

**Comment by nxzlem** [comment]
> Untuk hostnya, saya ambil dari commit [a311cf6](https://github.com/bebasid/bebasid/commit/a311cf60f63287eb2e9e68abd40a3fb0905e32ff), bukan yang terbaru ([88160f9](https://github.com/bebasid/bebasid/commit/88160f9a93c4a031c1b6f6f6819642edac5e2225)). Akan saya kabari kembali besok pagi, karena saya lagi tidak dapat akses laptop.
> 
> Jika masih ada kendala, pertanyaan saya adalah, apakah host dari Energized juga memengaruhi ini?

Kayaknya sih, iya mas. Saya sudah cek subdomain/dnsdumpster reddit.com, sudah terupdate ke IP terbaru.

**Comment by nxzlem** [comment]
Saya izin tutup issuenya ya, mas Jika masih ada masalah, silakan re-open lagi issuenya. Terimakasih.
