### ISSUE TITLE
[REQ] sextb.net

### ISSUE THREAD

**Issue by harumembiru** [bebasid/bebasid#389]
belum ada di hosts,
trima kasih

**Comment by nxzlem** [comment]
Oke, sudah ditambahin ke hosts bebasid ya. Jangan lupa diupdate hosts terlebih dahulu. Terimakasih!

**Comment by harumembiru** [comment]
terima kasih :D, 

salam.

**Comment by nxzlem** [comment]
> terima kasih :D,
> 
> salam.

Sip, saya akan tutupin issuenya sekarang. Terimakasih.
