### ISSUE TITLE
[REQ] Situs Streaming Olahraga

### ISSUE THREAD

**Issue by franksling** [bebasid/bebasid#396]
Kakak request unblock situs streaming olahraga dong ini

https://ripple.stream/
https://sportshub.stream/
https://socceronline.me/

**Comment by nxzlem** [comment]
Oke, sudah ditambahkan ke hosts bebasid, ya! Jangan lupa di-update hosts-nya terlebih dahulu. Terima Kasih!
Issuenya bakal ditutup seteleah 7 hari lewat.
