### ISSUE TITLE
[REQ] socialclub.rockstargames.com

### ISSUE THREAD

**Issue by hanifwork125** [bebasid/bebasid#397]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts

**Comment by nxzlem** [comment]
Oke, sudah ditambahkan ke hosts bebasid, ya! Jangan lupa di-update hosts-nya terlebih dahulu. Terima Kasih!
Issuenya bakal ditutup seteleah 7 hari lewat.
