### ISSUE TITLE
[BUG] tombol netflix salah url

### ISSUE THREAD

**Issue by ijash** [bebasid/bebasid#4]
**Deskripsi mengenai bug**
saya ga tau guna tombolnya apa. tapi pas ngeklik tombol netflix sama aja kayak ngeklik tombol sites. mungkin harusnya ke yang lain?

**Screenshot**

![image](https://user-images.githubusercontent.com/30673286/76123878-268fb080-602c-11ea-90fe-f395195c0b94.png)

**Device**
 - OS: [cth. Windows 10]
 - Browser -

**Comment by nxzlem** [comment]
Apakah ini versi lama yg dari proyek arsip?
