### ISSUE TITLE
[REQ] 127.0.0.1 localhost

### ISSUE THREAD

**Issue by rhnkbr** [bebasid/bebasid#40]
![Screen Shot 2020-03-30 at 4 42 15 PM](https://user-images.githubusercontent.com/62373321/77898492-70735b80-72a5-11ea-9069-e83bcc77d5b4.png)
can't resolve localhost on macos

**Comment by nxzlem** [comment]
Bisa saya check internet kamu ngeload "google.com" ?

**Comment by rhnkbr** [comment]
> Bisa saya check internet kamu ngeload "google.com" sama "reddit.com" ?

![Screen Shot 2020-03-30 at 11 07 37 PM](https://user-images.githubusercontent.com/62373321/77935201-56ed0680-72db-11ea-9a4f-c5275fdfed70.png)
![Screen Shot 2020-03-30 at 11 09 12 PM](https://user-images.githubusercontent.com/62373321/77935338-7f750080-72db-11ea-9ad6-060d22999b2b.png)
untuk di macos sendiri perlu konfigurasi 127.0.0.1 localhost pada file hosts agar bisa melakukan loopback

**Comment by nxzlem** [comment]
Tunggu dulu for the developer ok? Sabar ya.

**Comment by gvoze32** [comment]
![image](https://user-images.githubusercontent.com/28755051/78103622-90c32780-7417-11ea-8092-d2d57d246797.png)

Terima kasih sudah melaporkan adanya bug, silahkan gunakan ekstensi localhost untuk memasang default localhost loopback
