### ISSUE TITLE
[BUG] saat instal

### ISSUE THREAD

**Issue by anwarfors123** [bebasid/bebasid#41]
**Deskripsi mengenai bug**
Error saat instal

**Screenshot**
http://puu.sh/FrNaP/97ed19cbd9.png

**Device**
 - Windows 7
 - Chrome

**Comment by gvoze32** [comment]
coba winver dan ss kemudian kirimkan ke sini

**Comment by anwarfors123** [comment]
![](https://puu.sh/FsbpU/4b4537a7c3.png)

**Comment by nxzlem** [comment]
Versi Powershell kamu v2.0 berarti gak ada Invoke-Webrequest Support.
Kamu harus upgrade Powershell v2.0 ke v3.0 maka linknya ada di sini.
https://www.microsoft.com/en-us/download/details.aspx?id=54616
Kalau ada yang masalah bilang ke saya ya, terima kasih.
