### ISSUE TITLE
tidak terkoneksi ke internet

### ISSUE THREAD

**Issue by crossroaddemon** [bebasid/bebasid#42]
pas install (buka BEBASID.bat) ada tulisan tidak terkoneksi ke internet padahal internet masi lancar.
![image](https://user-images.githubusercontent.com/63005874/78153561-6435fc80-7465-11ea-95fd-e0fc714fa42f.png)

**Comment by gvoze32** [comment]
pergi ke Properties di My computer
klik Advanced system settings ----->Advanced -----> Environment Variables
pilih 'PATH' dari list system variable dan edit kemudian set PATH ke c:\windows\system32
