### ISSUE TITLE
[BUG] gogoanime.pro

### ISSUE THREAD

**Issue by masato052** [bebasid/bebasid#422]
Kemarin masih lancar tapi sekarang kena internet positif

**Comment by nxzlem** [comment]
gogoanime.pro sudah ada mas dari hosts bebasid. 
Domainnya akan saya perbarui dengan IP baru ya. Mohon sabarnya. Terimakasih.

**Comment by nxzlem** [comment]
Oke sudah ya, jangan lupa diperbarui dulu file hostsnya, di komputer anda. Terimakasih.
Jika masih ada masalah, silakan re-open issue nya dan tanyakan kenapa terjadinya.
