### ISSUE TITLE
[BUG] ryuugames.com

### ISSUE THREAD

**Issue by frank77777** [bebasid/bebasid#423]
**Deskripsi mengenai bug**
Tertulis the connection has timed out. website baru bisa dibuka jika menggunakan vpn

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.

**Device**
 - OS: Windows 10
 - Browser Firefox

**Comment by nxzlem** [comment]
Oke sudah ya, jangan lupa diperbarui dulu file hostsnya, di komputer anda. Terimakasih.
Jika masih ada masalah, silakan re-open issue nya dan tanyakan kenapa terjadinya.
