### ISSUE TITLE
[REQ] movies123.show

### ISSUE THREAD

**Issue by rizkireynaldi** [bebasid/bebasid#428]
Mohon tambahkan: movies123.show

terima kasih

**Comment by nxzlem** [comment]
Oke, sudah ditambahkan ke hosts bebasid, ya! Jangan lupa di-update hosts-nya terlebih dahulu. Terima Kasih!
Issuenya bakal ditutup seteleah 7 hari terlewat.

**Comment by nxzlem** [comment]
Issuenya saya tutup sekarang ya mas, kalo jika ada masalah silakan re-open issuenya lagi. Terimakasih.

**Comment by nxzlem** [comment]
Update barusan salah issue, harusnya di 430, maaf.
