### ISSUE TITLE
Need tester for Mac

### ISSUE THREAD

**Issue by icaksh** [bebasid/bebasid#43]
**Need tester for who use MacOS**
Req
OS: OSX
Browser: Google Chrome Stable
Have Netflix Premium Account

**What should I do?**
```
Get the bash script
sudo curl -o /usr/local/bin/bebasid-gt https://raw.githubusercontent.com/bebasid/bebasid/master/dev/scripts/green-tunnel/gt-mac.sh

Give permission
chmod +x /usr/local/bin/bebasid-gt

Execute
bebasid-gt install
bebasid-gt start

If you wanna help
bebasid-gt --help
```

It will installing Homebrew, NPM, Green Tunnel, and Tmux also it will kill all opened Chrome and open Green Tunnel and new Chrome Stable but using Proxy Server on background (screen), new Chrome will be appear

Open Netflix and Play a Video

If you wanna restore (deleting the script)
`sudo rm -rf /usr/local/bin/bebasid-gt`

**What should I report?**

If you can play video or not, report it

Thank You

NB: I will close this issue if no reply / comment after 5 days

**Comment by kaizenlolo** [comment]
chmod: Unable to change file mode on /usr/local/bin/bebasid-gt: Operation not permitted, ini kenapa ya? saat enter code chmod +x /usr/local/bin/bebasid-gt selalu operation not permitted.

**Comment by gvoze32** [comment]
coba sudo chmod +x /usr/local/bin/bebasid-gt

**Comment by kaizenlolo** [comment]
oke thanks bisa, tapi next saat install (bebasid-gt install) resutnya kayak gini
/usr/local/bin/bebasid-gt: line 48: syntax error near unexpected token `fi'
/usr/local/bin/bebasid-gt: line 48: `  fi'

**Comment by icaksh** [comment]
line 48 ada kata fi, bisa dihapus.. atau jika tidak bisa, download script yang baru (updated)

**Comment by surahmans** [comment]
Tadi udah coba trus ada error gt harus diinstall. Padahal udah ada. Akhirnya saya langsung bypass aja jalanin function `open_gt` dan berhasil run. Cuma pas buka Netflix tetap kena blok.

**Comment by icaksh** [comment]
> Tadi udah coba trus ada error gt harus diinstall. Padahal udah ada. Akhirnya saya langsung bypass aja jalanin function `open_gt` dan berhasil run. Cuma pas buka Netflix tetap kena blok.

noted bug di cek command

apa buat buka web lain bisa?

**Comment by icaksh** [comment]
Nunggu issue dari Green Tunnel beres dulu
