### ISSUE TITLE
[REQ] fullmatchsports.cc

### ISSUE THREAD

**Issue by wawawow** [bebasid/bebasid#430]
```
# [fullmatchsports.cc]
172.67.171.233 fullmatchsports.cc
172.67.171.233 www.fullmatchsports.cc
172.67.171.233 en.fullmatchsports.cc
172.67.171.233 us.fullmatchsports.cc
104.21.95.253 fullmatchsports.cc
104.21.95.253 www.fullmatchsports.cc
104.21.95.253 en.fullmatchsports.cc
104.21.95.253 us.fullmatchsports.cc
```

**Comment by nxzlem** [comment]
Taronya di pull request ya, nanti tinggal di edit hostsnya biar saya akan dicek. Terimakasih untuk domain & subdomainnya.

**Comment by nxzlem** [comment]
Oke, sudah ditambahkan ke hosts bebasid, ya! Jangan lupa di-update hosts-nya terlebih dahulu. Terima Kasih!
Issuenya bakal ditutup seteleah 7 hari terlewat.
