### ISSUE TITLE
[BUG] Windows 11 terdeteksi bebasid sebagai windows 10

### ISSUE THREAD

**Issue by raismaulana** [bebasid/bebasid#434]
**Deskripsi mengenai bug**
Windows 11 terdeteksi bebasid sebagai windows 10

**Screenshot**
![image](https://user-images.githubusercontent.com/22321111/147375579-8ee504f6-5a5a-410a-a230-982da3532e25.png)

**Device**
 - OS: [cth. Windows 11]

**Comment by gvoze32** [comment]
Belum ada cara untuk membedakan antara Windows 10 dengan Windows 11 dalam perintah batch merujuk pada
https://stackoverflow.com/questions/69373447/is-there-an-official-way-to-detect-windows-11

Windows 10 : 10.0.xxxx
Windows 11 : 10.0.xxxx

Sehingga hanya bisa menunggu adanya penambahan angka unik untuk versi kedepannya misal 10.1.xxxx baru nanti bisa kami implementasikan ke dalam aplikasi.

**Comment by gvoze32** [comment]
Fix sementara
https://github.com/bebasid/bebasid/commit/d24aba2be4e8a1a355fb2fd82ef7e71487f19754

**Comment by ikr4mm** [comment]
> Belum ada cara untuk membedakan antara Windows 10 dengan Windows 11 dalam perintah batch merujuk pada https://stackoverflow.com/questions/69373447/is-there-an-official-way-to-detect-windows-11
> 
> Windows 10 : 10.0.xxxx Windows 11 : 10.0.xxxx
> 
> Sehingga hanya bisa menunggu adanya penambahan angka unik untuk versi kedepannya misal 10.1.xxxx baru nanti bisa kami implementasikan ke dalam aplikasi.

Menurut [forum Microsoft ini](https://docs.microsoft.com/en-us/answers/questions/586619/windows-11-build-ver-is-still-10022000194.html) katanya build Windows 11 itu dimulai dari 10.0.2200 keatas, dan di bawahnya sudah dipastikan itu merupakan Windows 10.

Adapun tadi saya sempat searching untuk mendapatkan full build number dari Windows itu [dari sini](https://stackoverflow.com/a/25978837). Semoga bisa difix 🙏

**Comment by gvoze32** [comment]
Terima kasih @ikr4mm atas informasinya, saya telah melakukan commit untuk memperbaiki masalah tersebut.
https://github.com/bebasid/bebasid/commit/55cb48f1fe081f507835556ba76e4b2deaff903b

Beri tahu saya jika issue Anda sudah diperbaiki.

**Comment by raismaulana** [comment]
@gvoze32 mantap sudah benar terdeteksi windows 11
![image](https://user-images.githubusercontent.com/22321111/147756659-0a9b4835-b69e-4f9a-879c-447f84b075de.png)

**Comment by nxzlem** [comment]
Oke sudah benar ya, saya tutupkan isu nya untuk sekarang. Terimakasih atas dukungan anda.
