### ISSUE TITLE
[BUG] jaringan XL masih kena blok

### ISSUE THREAD

**Issue by ModiFlasher** [bebasid/bebasid#436]
Gan semenjak saya gantk kartu sim dari telkomsel ke XL (LiveON) malah gk work yah di jaringan XL(LiveON) semua situs di file hosts nya masih terblokir
**Device**
 - OS: Android 11
 - Browser Chrome

**Comment by nxzlem** [comment]
Maaf mas, saya bukan penggunaan telkomsel/XL, saya memakai smartfren masih aman saja, mas.

**Comment by gvoze32** [comment]
@ModiFlasher bisa diinfokan memakai metode yang mana?

**Comment by ModiFlasher** [comment]
Pake metode magisk
Push ke system juga sama

**Comment by hendysama** [comment]
@ModiFlasher 
> Gan semenjak saya gantk kartu sim dari telkomsel ke XL (LiveON) malah gk work yah di jaringan XL(LiveON) semua situs di file hosts nya masih terblokir **Device**
> 
>     * OS: Android 11
> 
>     * Browser Chrome

saya user xl... tampakknya firewall xl lbih canggih... mungkin kebanyakan resource... jadi ip terdetek di trust positif bnar benar dibuat Down lumpuh... ini sudah 2-3 mingguan...

**Comment by ModiFlasher** [comment]
> @ModiFlasher
> 
> > Gan semenjak saya gantk kartu sim dari telkomsel ke XL (LiveON) malah gk work yah di jaringan XL(LiveON) semua situs di file hosts nya masih terblokir **Device**
> > ```
> > * OS: Android 11
> > 
> > * Browser Chrome
> > ```
> 
> saya user xl... tampakknya firewall xl lbih canggih... mungkin kebanyakan resource... jadi ip terdetek di trust positif bnar benar dibuat Down lumpuh... ini sudah 2-3 mingguan...

Berarti emang dari provider nya yah ?

**Comment by nxzlem** [comment]
> > @ModiFlasher
> > > Gan semenjak saya gantk kartu sim dari telkomsel ke XL (LiveON) malah gk work yah di jaringan XL(LiveON) semua situs di file hosts nya masih terblokir **Device**
> > > ```
> > > * OS: Android 11
> > > 
> > > * Browser Chrome
> > > ```
> > 
> > 
> > saya user xl... tampakknya firewall xl lbih canggih... mungkin kebanyakan resource... jadi ip terdetek di trust positif bnar benar dibuat Down lumpuh... ini sudah 2-3 mingguan...
> 
> Berarti emang dari provider nya yah ?

Bisa ngaruh ke provider nya mas, saya mau kabar sekarang nih, tapi gimana dengan keadaan xl sekarang? masih diblok apa sudah kembali ke akses?

**Comment by ModiFlasher** [comment]
Masih kena blok tapi ada solusi nya sih
Install module dns cloudflare

**Comment by nxzlem** [comment]
> Masih kena blok tapi ada solusi nya sih Install module dns cloudflare

Sudah dicoba kan? gimana hasilnya?

**Comment by nxzlem** [comment]
untuk dns bebasid, sudah ditambahkan dns google dan cloudflare.
![a](https://files.catbox.moe/78eq84.png)
![b](https://files.catbox.moe/eoq4q1.png])

**Comment by ModiFlasher** [comment]
> > Masih kena blok tapi ada solusi nya sih Install module dns cloudflare
> 
> Sudah dicoba gan? gimana hasilnya?

Udah di coba pake module terpisah dan work
Coba bongkar file ini buat referensi
[[MagiskApp.com]_CloudflareDNS4Magisk-v2.727.zip](https://github.com/bebasid/bebasid/files/7860371/MagiskApp.com._CloudflareDNS4Magisk-v2.727.zip)

**Comment by nxzlem** [comment]
> > > Masih kena blok tapi ada solusi nya sih Install module dns cloudflare
> > 
> > 
> > Sudah dicoba gan? gimana hasilnya?
> 
> Udah di coba pake module terpisah dan work Coba bongkar file ini buat referensi [[MagiskApp.com]_CloudflareDNS4Magisk-v2.727.zip](https://github.com/bebasid/bebasid/files/7860371/MagiskApp.com._CloudflareDNS4Magisk-v2.727.zip)

Oke, nanti diceknya sama si @gvoze32 ya.

**Comment by nxzlem** [comment]
Halo mas @ModiFlasher, mau kabar nih sekarang. Jadi jaringan XL sudah bisa akses lagi atau masih kena blokir? Tolong di respon ya. Terimakasih

**Comment by thatismunn** [comment]
![image](https://user-images.githubusercontent.com/32958839/162554226-7439fa80-e222-4ad6-988f-095b6c65d5a0.png)
Untuk XL Home di TKP Makassar sendiri, hari ini udah bisa kebuka. Sempat minggu lalu goyang lagi dan akhirnya bisa kebuka.

**Comment by nxzlem** [comment]
Oke, saya masih tunggu jawaban untuk pengguna XL home sama pemiliknya yang buat isu ini.

**Comment by vjbenn** [comment]
Mungkin bisa dicoba pake APN polosan tanpa proxy om, "internet" misalnya. Karena bawaan apn XL pake proxy 202.152.240.50 yang bikin adaway gak jalan.

**Comment by nxzlem** [comment]
Halo, saya mau ngasih kabar.
Jika lagi make XL dari operator/XL LiveON, silakan pake powertunnel atau vpn dulu ya.
Kalo ada yg pakai XL Home(Provider) dan masih ada masalah, tolong di diskusikan ya.
Terimakasih.
