### ISSUE TITLE
[REQ] doujindesu.xxx

### ISSUE THREAD

**Issue by akn19** [bebasid/bebasid#437]

**Comment by nxzlem** [comment]
Halo, @akn19.
Domain anda sudah ditambahkan ke hosts bebasid, ya! Jangan lupa diupdate hostsnya terlebih dahulu. Agar hostnya tetap update ke terbaru. Issue anda akan ditutup setelah 3-7 hari terlewat. Jika ada masalah setelah issuenya tertutup atau sekarang. Tolong berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih!
dari @nxzlem.
