### ISSUE TITLE
[REQ] welovemanga.net

### ISSUE THREAD

**Issue by masato052** [bebasid/bebasid#438]

**Comment by nxzlem** [comment]
Halo mas, saya mau membales isu request anda.
Sebenarnya, welovemanga.net tidak ada status keblokir dari trustpositif. Silakan periksa lagi dengan benar. Terimakasih.
![vve523](https://i.imgur.com/DJAZpKA.jpeg)
![a43an3](https://i.imgur.com/TaqCYsb.png)
