### ISSUE TITLE
Operation not permitted saat install di Mac

### ISSUE THREAD

**Issue by kaizenlolo** [bebasid/bebasid#44]
saat input code chmod +x /usr/local/bin/bebasid-gt ke terminal, hasilnya chmod: Unable to change file mode on /usr/local/bin/bebasid-gt: Operation not permitted. kenapa ya?

**Comment by gvoze32** [comment]
kasih sudo

**Comment by gvoze32** [comment]
ini saya close ya, pindah ke issue sebelumnya
