### ISSUE TITLE
[BUG] No Internet Connection

### ISSUE THREAD

**Issue by kamalls** [bebasid/bebasid#443]
**Deskripsi mengenai bug**
Setelah update host lancar-lancar saja tapi setelah reboot device tidak bisa akses internet, semua browser dan terminal juga tidak bisa melakukan ping, semua jaringan GSM maupun Wifi minta Login walaupun tidak ada Login Page nya.

**Device**
 - OS: Windows 11 & Android 10
 - Browser : Semua Browser

**Comment by nxzlem** [comment]
Yang masalah dengan internetnya di android apa di laptop/computer?
