### ISSUE TITLE
[REQ] p2p.binance.com

### ISSUE THREAD

**Issue by wandriputra** [bebasid/bebasid#444]

**Comment by nxzlem** [comment]
Halo, @wandriputra.
Subdomain anda sudah ditambahkan ke hosts bebasid, ya! Jangan lupa diupdate hostsnya terlebih dahulu. Agar hostnya tetap update ke terbaru. Issue anda akan ditutup setelah 3-7 hari terlewat. Jika ada masalah setelah issuenya tertutup atau sekarang. Tolong berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih!
dari @nxzlem.

**Comment by wandriputra** [comment]
thanks @nxzlem works as expected, I'll close this issue.
