### ISSUE TITLE
[REQ] Binance Testnet RPC

### ISSUE THREAD

**Issue by YogaSakti** [bebasid/bebasid#445]
Testnet RPC: 
- https://data-seed-prebsc-1-s1.binance.org:8545
- https://data-seed-prebsc-2-s1.binance.org:8545
- https://data-seed-prebsc-1-s2.binance.org:8545
- https://data-seed-prebsc-2-s2.binance.org:8545
- https://data-seed-prebsc-1-s3.binance.org:8545
- https://data-seed-prebsc-2-s3.binance.org:8545

Testnet Faucet:
- https://testnet.binance.org/faucet-smart

Testnet Explorer:
- https://testnet-explorer.binance.org/

[Source](https://github.com/ethereum-lists/chains/blob/6e3b5d8821425df43088bfab9af0dd581006e1d6/_data/chains/eip155-97.json)

**Comment by nxzlem** [comment]
Ini nama subdomainnya ya?

**Comment by YogaSakti** [comment]
iya

**Comment by nxzlem** [comment]
Halo, @YogaSakti.
Subdomain anda sudah ditambahkan ke hosts bebasid, ya! Jangan lupa diupdate hostsnya terlebih dahulu. Agar hostnya tetap update ke terbaru. Issue anda akan ditutup setelah 3-7 hari terlewat. Jika ada masalah setelah issuenya tertutup atau sekarang. Tolong berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih!
dari @nxzlem.
