### ISSUE TITLE
[REQ] pahe.li & pahe.stream

### ISSUE THREAD

**Issue by harumembiru** [bebasid/bebasid#446]

**Comment by nxzlem** [comment]
Halo, @harumembiru.
Domain & Subdomain anda sudah ditambahkan ke hosts bebasid, ya! Jangan lupa diupdate hostsnya terlebih dahulu. Agar hostnya tetap update ke terbaru. Issue anda akan ditutup setelah 3-7 hari terlewat. Jika ada masalah setelah issuenya tertutup atau sekarang. Tolong berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih!
dari @nxzlem.

**Comment by bakomon** [comment]
Sekalian tambahkan domain utama: pahe.in

Terima kasih.

**Comment by nxzlem** [comment]
> 

Baik, akan saya tambahkan secepatnya. Terimakasih.

**Comment by nxzlem** [comment]
Halo, @bakomon.
Domain & Subdomain anda sudah ditambahkan ke hosts bebasid, ya! Jangan lupa diupdate hostsnya terlebih dahulu. Agar hostnya tetap update ke terbaru. Jika ada masalah. Tolong berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih!
dari @nxzlem.
