### ISSUE TITLE
[BUG] hitomi.la

### ISSUE THREAD

**Issue by as4lan** [bebasid/bebasid#450]
**Deskripsi mengenai bug**
Situs **hitomi.la** tidak bisa diakses, tolong IP Address di update.

Thanks.

**Comment by nxzlem** [comment]
> **Deskripsi mengenai bug** Situs **hitomi.la** tidak bisa diakses, tolong IP Address di update.
> 
> Thanks.

Halo, @as4lan.
Maaf, bisa tolong sertakan lebih detail dan kasih screenshotnya? Saya sudah coba saat ini bisa diakseskan sekarang. Coba diperbarui lagi di komputer hosts anda. Terimakasih.
Dari @nxzlem.

**Comment by nxzlem** [comment]
Saat ini, ip situs hitomi.la masih sama dalam kondisinya.

**Comment by nxzlem** [comment]
Jika anda tidak merespon dalam 3-7 hari, kami akan mentutupkan issue anda. Berarti anda sudah jelas bisa apa masih belum dijawab. Terimakasih.

**Comment by as4lan** [comment]
![Screenshot_20220207-224437](https://user-images.githubusercontent.com/99103844/152810233-9c2c2781-5c06-42c2-93be-600f9fdc2658.jpg)

Duplicate data.

**Comment by nxzlem** [comment]
> ![Screenshot_20220207-224437](https://user-images.githubusercontent.com/99103844/152810233-9c2c2781-5c06-42c2-93be-600f9fdc2658.jpg)
> 
> Duplicate data.

Anda memakai magisk atau adaway??

**Comment by nxzlem** [comment]
Jika tidak ada masalah maka saya akan tutupkan issue sekarang, kalo masih ada masalah bisa direopen lagi dan jelaskan apa bagian duplicate data nya. Terimakasih.
