### ISSUE TITLE
[REQ] www.bilibili.tv

### ISSUE THREAD

**Issue by niizam** [bebasid/bebasid#455]
Saya mencoba menambahkan ip address di bawah ini

> 23.236.97.62 i.w.bilicdn1.com
23.236.97.62 www.bilibili.tv
>164.52.28.62 bilibili.tv

namun sepertinya ada yang saya lewatkan sehingga tidak bisa login seperti biasanya.
Jadi mohon bantuannya

**Comment by niizam** [comment]
Sepertinya sudah tidak diblokir IPO, jadi saya tutup.

**Comment by nxzlem** [comment]
Oke.
