### ISSUE TITLE
[BUG] nhentai.net

### ISSUE THREAD

**Issue by muzzin-ctrl** [bebasid/bebasid#457]
**Deskripsi mengenai bug**
thumbnail atau image bermasalah , sering failed load image error.

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.

**Device**
 - OS: [cth. Windows 10]
 - Browser [cth. Chrome, Firefox]

**Comment by nxzlem** [comment]
Halo, mas @muzzin-ctrl. Situs nhentai.net telah sudah diperbarukan ya.
Silakan diperbarui hosts komputer anda selain perangkatnya juga, agar tetap di versi terbarunya.
Terimakasih. Salam dari @nxzlem.
