### ISSUE TITLE
[REQ] rin.ru & cs.rin.ru

### ISSUE THREAD

**Issue by Amarizky** [bebasid/bebasid#458]
**Deskripsi mengenai bug**
cs.rin.ru tidak bisa dibuka di jaringan Telkomsel. Setelah menambahkan fix dari #269 baru bisa dibuka

**Screenshot**
![image](https://user-images.githubusercontent.com/36600028/160296169-68a5d499-b9a0-44cd-8dd9-b7a4119ce982.png)

**Device**
 - OS: Windows 10
 - Browser: Microsoft Edge

**Comment by nxzlem** [comment]
Halo mas @Amarizky, sebagai situs rin.ru belum ditambahkan dari hosts bebasid, saya tambahkan sekarang ya.
Silakan diperbarui hosts komputer anda selain perangkatnya juga, Agar hostnya tetap update ke versi terbaru. Issue anda akan ditutup setelah 3-7 hari terlewat. Jika ada masalah setelah issuenya tertutup atau sekarang. Tolong berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih! dari @nxzlem.
