### ISSUE TITLE
[BUG] rule34video.com

### ISSUE THREAD

**Issue by closetsukebei** [bebasid/bebasid#461]
**Deskripsi mengenai bug**
sudah copas latest release untuk r34v=rule34video
bisa buka situs r34v.com, tapi ketika buka video "html5: Video file not found"
jika menggunakan built-in vpn (dari opera), lancar, tidak ada masalah

**Device**
 - OS: Windows 7 64bit
 - Browser: Opera

**Comment by nxzlem** [comment]
bisakah anda lebih detailkan nama situs yang anda mau buka video nya?

**Comment by nxzlem** [comment]
Halo, mas @closetsukebei. Situs rul34video.com telah sudah diperbarukan ya.
Silakan diperbarui hosts komputer anda selain perangkatnya juga, Agar hostnya tetap update ke versi terbaru. Issue anda akan ditutup setelah 3-7 hari terlewat. Jika ada masalah setelah issuenya tertutup atau sekarang. Tolong berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih! dari @nxzlem.
