### ISSUE TITLE
Info: bebasid tidak dapat jalan di provider Te****sel

### ISSUE THREAD

**Issue by icaksh** [bebasid/bebasid#463]
Berdasarkan analisis yang telah dilakukan, dapat disimpulkan bahwa untuk beberapa website tertentu dinyatakan **tidak dapat diakses dengan menggunakan bebasid dan bebasit**

Te****sel telah menggunakan fitur BIG-IP yang memungkinkan untuk **dropping** paket yang masuk dengan hasil identifikasi dengan menggunakan wireshark
![unknown](https://user-images.githubusercontent.com/19889081/162693230-be8572cd-0e44-4e6f-bf25-f0dd977f885e.png)

Dan untuk DoH tidak diblokir oleh provider
![image](https://user-images.githubusercontent.com/19889081/162694376-47e2f2bc-f6f6-48ff-bee0-05c053a85230.png)

Tunnelling dengan bebasit, request berhasil tetapi ketika mendapatkan response langsung RESET
![image](https://user-images.githubusercontent.com/19889081/162694937-e744c923-a4ac-4e96-ba9c-061a940459da.png)

Perlu diketahui mekanisme penembusan DPI hanya mengubah packet request, untuk packet response tidak _difool_, sehingga akan di drop oleh ISP

Jalan penembusan blokiran ini hanyalah menggunakan Cloudflare WARP atau VPN Pribadi
 
Sekian Informasinya

**Comment by nxzlem** [comment]
Ini mungkin bisa ngaruh ke dns bebasid, didalam pengaturan dns nya ada beberapa ditambahkan DNS Google & Cloudflare.

**Comment by nxzlem** [comment]
Pake [powertunnel](https://github.com/krlvm/PowerTunnel) bisa gak?

**Comment by RacBallonMC** [comment]
Bisa pake [https://github.com/bol-van/zapret](url)

**Comment by mangkoran** [comment]
@RacBallonMC Maaf bertanya, bagaimana cara install dan setup nya?
