### ISSUE TITLE
[REQ] kisstvshow.to

### ISSUE THREAD

**Issue by skyskymerlin** [bebasid/bebasid#464]

**Comment by nxzlem** [comment]
Halo mas @skyskymerlin, sebagai situs kisstvshow.to belum ditambahkan dari hosts bebasid, saya tambahkan sekarang ya.
Silakan diperbarui hosts komputer anda selain perangkatnya juga, Agar hostnya tetap update ke versi terbaru. Issue anda akan ditutup setelah 3-7 hari terlewat. Jika ada masalah setelah issuenya tertutup atau sekarang. Tolong berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih! dari @nxzlem.
