### ISSUE TITLE
[BUG] nhentai.net

### ISSUE THREAD

**Issue by closetsukebei** [bebasid/bebasid#465]
**Deskripsi mengenai bug**
nhentai ganti IP. request untuk new host. makasih

**Device**
 - OS: Windows 7 64bit
 - Browser: Opera

**Comment by nxzlem** [comment]
Halo, kak @closetsukebei. Situs nhentai.net sudah telah diperbarui ya.
Silakan diperbarui hosts komputer anda selain untuk perangkatnya juga, agar hostnya tetap update ke versi terbaru. Jika issue anda belum ditutupkan dalam 3-7 hari, maka issue anda akan ditutup. Kalo ada masalah setelah issuenya tertutup atau masih terbuka/sekarang. Tolong berikan kenapa alesannya dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih dari @nxzlem.
