### ISSUE TITLE
[BUG] Instruksi installasi bebasid.com

### ISSUE THREAD

**Issue by heisid** [bebasid/bebasid#468]
**Deskripsi mengenai bug**
Instruksi installasi di situs bebasid.com, untuk linux ditulis: `sudo wget https://raw.githubusercontent.com/bebasid/bebasid/master/releases/hosts -O /etc/hosts && sudo chmod +x /usr/local/bin/bebasid`, bagaimana bisa chmod kalau skripnya belum terdownload?

Bukankah seharusnya `sudo curl https://raw.githubusercontent.com/bebasid/bebasid/master/releases/bebasid.sh -o /usr/local/bin/bebasid && sudo chmod +x /usr/local/bin/bebasid`?

**Device**
 - OS: Linux

**Comment by Aiuraa** [comment]
> bagaimana bisa chmod kalau skripnya belum terdownload?

Setahu aku, `chmod` akan berjalan ketika wget telah sukses tereksekusi (mengindikasikan file sudah berhasil terdownload), ketika file dari wget gagal, maka perintah tidak akan dilanjutkan ke `chmod`

Yang kamu kasih dari atas hingga bawah aku rasa tidak ada bedanya, karena sama-sama menggunakan &&.

**Comment by Nuginity** [comment]
> > bagaimana bisa chmod kalau skripnya belum terdownload?
> 
> ̶S̶e̶t̶a̶h̶u̶ ̶a̶k̶u̶,̶ ̶`̶c̶h̶m̶o̶d̶`̶ ̶a̶k̶a̶n̶ ̶b̶e̶r̶j̶a̶l̶a̶n̶ ̶k̶e̶t̶i̶k̶a̶ ̶w̶g̶e̶t̶ ̶t̶e̶l̶a̶h̶ ̶s̶u̶k̶s̶e̶s̶ ̶t̶e̶r̶e̶k̶s̶e̶k̶u̶s̶i̶ ̶(̶m̶e̶n̶g̶i̶n̶d̶i̶k̶a̶s̶i̶k̶a̶n̶ ̶f̶i̶l̶e̶ ̶s̶u̶d̶a̶h̶ ̶b̶e̶r̶h̶a̶s̶i̶l̶ ̶t̶e̶r̶d̶o̶w̶n̶l̶o̶a̶d̶)̶,̶ ̶k̶e̶t̶i̶k̶a̶ ̶f̶i̶l̶e̶ ̶d̶a̶r̶i̶ ̶w̶g̶e̶t̶ ̶g̶a̶g̶a̶l̶,̶ ̶m̶a̶k̶a̶ ̶p̶e̶r̶i̶n̶t̶a̶h̶ ̶t̶i̶d̶a̶k̶ ̶a̶k̶a̶n̶ ̶d̶i̶l̶a̶n̶j̶u̶t̶k̶a̶n̶ ̶k̶e̶ ̶`̶c̶h̶m̶o̶d̶`̶
> 
> ̶Y̶a̶n̶g̶ ̶k̶a̶m̶u̶ ̶k̶a̶s̶i̶h̶ ̶d̶a̶r̶i̶ ̶a̶t̶a̶s̶ ̶h̶i̶n̶g̶g̶a̶ ̶b̶a̶w̶a̶h̶ ̶a̶k̶u̶ ̶r̶a̶s̶a̶ ̶t̶i̶d̶a̶k̶ ̶a̶d̶a̶ ̶b̶e̶d̶a̶n̶y̶a̶,̶ ̶k̶a̶r̶e̶n̶a̶ ̶s̶a̶m̶a̶-̶s̶a̶m̶a̶ ̶m̶e̶n̶g̶g̶u̶n̶a̶k̶a̶n̶ ̶&̶&̶.̶
> 
> Oh mata aku sliwer xd, maaf, tapi kenapa harus berubah menjadi curl yah 🤔

curl merupakan tools dari library libcurl dimana lebih advanced dari pada wget, namun basicnya sama saja jika ingin melakukan transfer yang lebih advanced seperti upload lebih baik memakai curl, hanya saja curl merupakan bagian dari sebuah library libcurl sedangkan wget berdiri sendiri

**Comment by heisid** [comment]
> > bagaimana bisa chmod kalau skripnya belum terdownload?
> 
> ̶S̶e̶t̶a̶h̶u̶ ̶a̶k̶u̶,̶ ̶`̶c̶h̶m̶o̶d̶`̶ ̶a̶k̶a̶n̶ ̶b̶e̶r̶j̶a̶l̶a̶n̶ ̶k̶e̶t̶i̶k̶a̶ ̶w̶g̶e̶t̶ ̶t̶e̶l̶a̶h̶ ̶s̶u̶k̶s̶e̶s̶ ̶t̶e̶r̶e̶k̶s̶e̶k̶u̶s̶i̶ ̶(̶m̶e̶n̶g̶i̶n̶d̶i̶k̶a̶s̶i̶k̶a̶n̶ ̶f̶i̶l̶e̶ ̶s̶u̶d̶a̶h̶ ̶b̶e̶r̶h̶a̶s̶i̶l̶ ̶t̶e̶r̶d̶o̶w̶n̶l̶o̶a̶d̶)̶,̶ ̶k̶e̶t̶i̶k̶a̶ ̶f̶i̶l̶e̶ ̶d̶a̶r̶i̶ ̶w̶g̶e̶t̶ ̶g̶a̶g̶a̶l̶,̶ ̶m̶a̶k̶a̶ ̶p̶e̶r̶i̶n̶t̶a̶h̶ ̶t̶i̶d̶a̶k̶ ̶a̶k̶a̶n̶ ̶d̶i̶l̶a̶n̶j̶u̶t̶k̶a̶n̶ ̶k̶e̶ ̶`̶c̶h̶m̶o̶d̶`̶
> 
> ̶Y̶a̶n̶g̶ ̶k̶a̶m̶u̶ ̶k̶a̶s̶i̶h̶ ̶d̶a̶r̶i̶ ̶a̶t̶a̶s̶ ̶h̶i̶n̶g̶g̶a̶ ̶b̶a̶w̶a̶h̶ ̶a̶k̶u̶ ̶r̶a̶s̶a̶ ̶t̶i̶d̶a̶k̶ ̶a̶d̶a̶ ̶b̶e̶d̶a̶n̶y̶a̶,̶ ̶k̶a̶r̶e̶n̶a̶ ̶s̶a̶m̶a̶-̶s̶a̶m̶a̶ ̶m̶e̶n̶g̶g̶u̶n̶a̶k̶a̶n̶ ̶&̶&̶.̶
> 
> Oh mata aku sliwer xd, maaf, tapi kenapa harus berubah menjadi curl yah thinking

maaf... maaf kalo saya agak membingungkan. Intinya bukan masalah wget atau curlnya sih, tapi file yg didownload, itukan yg didonlot host filenya aja, scriptnya belum.

**Comment by heisid** [comment]
mungkin bisa dicoba dulu di linux yg masih fresh belum ada bebasidnya, command itu jalan ngga, hehe. Soalnya kalo di saya ngga bisa `chmod: cannot access '/usr/local/bin/bebasid' : No such file or directory`

**Comment by fransiscusrolandamalau** [comment]
seharusnya sih permasalahannya bukan antara wget atau curl, mungkin bisa diperhatikan lagi letak perbedaannya

diwebsite seperti ini:
`sudo wget https://raw.githubusercontent.com/bebasid/bebasid/master/releases/hosts -O /etc/hosts && sudo chmod +x /usr/local/bin/bebasid`

dan yang diharapkan seperti ini:
`sudo wget https://raw.githubusercontent.com/bebasid/bebasid/master/releases/bebasid.sh -o /usr/local/bin/bebasid && sudo chmod +x /usr/local/bin/bebasid`

**Comment by gvoze32** [comment]
Hai @heisid maaf baru bisa diproses, bisa dicek di sini apakah sudah betul instruksinya?

https://bebasid.com/#install
