### ISSUE TITLE
[REQ] catbox.moe

### ISSUE THREAD

**Issue by monixL** [bebasid/bebasid#469]
sekitar 2 minggu lalu sudah gk bisa diakses tanpa vpn

**Comment by nxzlem** [comment]
halo kak, iya pas saya ngecek tidak bisa di reach situsnya

**Comment by nxzlem** [comment]
catbox.moe tidak diblokir oleh kominfo, setelah saya cek, yang saya liat situs nya juga kena tempor down. saya cek lagi di isitdownrightnow begini hasil nya

![](https://media.discordapp.net/attachments/630416441996476436/976740374716497950/unknown.png?width=809&height=215)
![](https://media.discordapp.net/attachments/630416441996476436/976740561253982258/unknown.png?width=947&height=463)

**Comment by nxzlem** [comment]
Saya dapat info dari yang orang komentar katanya ini.
Karna ini "The Australian government has blocked all catbox links in an attempt to stop the flow of Ukrainian war footage into our country. The website is accessible but no video links can be accessed without a VPN. "

**Comment by Nuginity** [comment]
catbox.moe dapat dibuka dengan internet tanpa filter milik digital ocean, sudah dipastikan website ini di block oleh seluruh ISP Indonesia, dan sayangnya catbox.moe menggunakan provider hosting yang tidak memiliki alternative ip
![Screenshot (109)](https://user-images.githubusercontent.com/63849044/177064938-dc753203-f2c1-4fd2-8789-512c461830f2.png)

**Comment by Nuginity** [comment]
> catbox.moe dapat dibuka dengan internet tanpa filter milik digital ocean, sudah dipastikan website ini di block oleh seluruh ISP Indonesia, dan sayangnya catbox.moe menggunakan provider hosting yang tidak memiliki alternative ip ![Screenshot (109)](https://user-images.githubusercontent.com/63849044/177064938-dc753203-f2c1-4fd2-8789-512c461830f2.png)
Alternativenya adalah menggunakan Secured DNS, VPN, ataupun proxy server

**Comment by nxzlem** [comment]
> catbox.moe dapat dibuka dengan internet tanpa filter milik digital ocean, sudah dipastikan website ini di block oleh seluruh ISP Indonesia, dan sayangnya catbox.moe menggunakan provider hosting yang tidak memiliki alternative ip ![Screenshot (109)](https://user-images.githubusercontent.com/63849044/177064938-dc753203-f2c1-4fd2-8789-512c461830f2.png)

Mau tanya. Di gambar itu, contohnya pakai apa?

**Comment by heywolf15** [comment]
@Nuginity Setau gua secure dns gak bisa sekalipun dnscrypt

**Comment by Nuginity** [comment]
> > catbox.moe dapat dibuka dengan internet tanpa filter milik digital ocean, sudah dipastikan website ini di block oleh seluruh ISP Indonesia, dan sayangnya catbox.moe menggunakan provider hosting yang tidak memiliki alternative ip ![Screenshot (109)](https://user-images.githubusercontent.com/63849044/177064938-dc753203-f2c1-4fd2-8789-512c461830f2.png)
> > Alternativenya adalah menggunakan Secured DNS, VPN, ataupun proxy server
> 
> Mau tanya. Di gambar itu, contohnya pakai apa

Ini pake VPN dengan server pribadi ane sendiri

**Comment by Nuginity** [comment]
> @Nuginity Setau gua secure dns gak bisa sekalipun dnscrypt

Berarti kita akalin dengan tunneling
