### ISSUE TITLE
Netflix tdk bisa HD

### ISSUE THREAD

**Issue by neziak24** [bebasid/bebasid#47]
Streaming netflix stuck di 480p, dan gabisa HD (kadang susah buat nyentuh 480) sedangkan saat di check connection speed >15Mbps jadi seharusnya aman. Apa ada hubungannya dns yang dipilih apa bagaimana ya? thx

**Device**
 - OS: Win10
 - Browser: Chrome

**Comment by nxzlem** [comment]
Paket Netflix kamu apa? 
Kamu di Komputer atau di Laptop?

**Comment by neziak24** [comment]
yang ultra HD plan, dan di laptop.

**Comment by nxzlem** [comment]
Laptop Brand/Model nya?

**Comment by neziak24** [comment]
MSI GL63. Ok soalnya buka beberapa website kerasa jadi sedikit lemot gitu

**Comment by nxzlem** [comment]
Speedtest dulu mas kalau internet cepetanmu lemot/tidak,

**Comment by gvoze32** [comment]
pakai ekstensi ini
https://github.com/truedread/netflix-1080p
