### ISSUE TITLE
[REQ] buzzav.com bigasiantube.com pornharbour.net

### ISSUE THREAD

**Issue by muzzin-ctrl** [bebasid/bebasid#470]
di android bisa tp di laptop gak bisa dibuka.

**Comment by nxzlem** [comment]
Halo kak @muzzin-ctrl, sebagai situs buzzav.com, bigasiantube.com & pornharbour.net belum ditambahkan dari hosts bebasid, saya tambahkan sekarang ya.
Silakan diperbarui hosts komputer anda selain perangkatnya juga, Agar hostnya tetap update ke versi terbaru. Issue anda akan ditutup setelah 3-7 hari terlewat. Jika ada masalah setelah issuenya tertutup atau sekarang. Tolong berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih! dari @nxzlem.
