### ISSUE TITLE
[BUG] Binance.com

### ISSUE THREAD

**Issue by Kampring** [bebasid/bebasid#471]

**Comment by nxzlem** [comment]
Halo kak, untuk domain binance.com sudah lama ditambahkan dari hosts bebasid, kondisi di anda masih bisa konek?
https://github.com/bebasid/bebasid/commit/04e2d82d201c72306cd3e5e99f4347dfd9a2d442

**Comment by Kampring** [comment]
saya pakai indihome, apa mungkin bebasid tidak bisa tembus indihome ya, sehingga binance tetap tidak bisa diakses, kalau pakai VPN bisa :( , silahkan di close kalau memang masalahnya di ISP Indihome

**Comment by nxzlem** [comment]
> saya pakai indihome, apa mungkin bebasid tidak bisa tembus indihome ya, sehingga binance tetap tidak bisa diakses, kalau pakai VPN bisa :( , silahkan di close kalau memang masalahnya di ISP Indihome

Kakak sudah mencoba update hosts di perangkat anda? apakah masih tidak bisa tembus dalam situsnya?

**Comment by Kampring** [comment]
saya cek host di C:\Windows\System32\drivers\etc\
sudah ada binance di hosts filenya
saya buka subscene, dan web2 xxx bisa kebuka juga,
berikut tracert ke binance,com ( dns 1.1.1.1 dan 1.0.0.1) , pakai dns bawaan indihome sama saja hasilnya
![binance](https://user-images.githubusercontent.com/10830722/171995805-55ec1333-a574-461b-bde1-aac75c903dcf.png)

**Comment by gvoze32** [comment]
Fixed
https://github.com/bebasid/bebasid/commit/3f1050d35e10b140ee97976cc15762aef457c837

**Comment by Kampring** [comment]
terima kasih untuk FIXnya, tapi barusan saya update dan coba belum bisa.
saya coba ambil IP dari HOST lama yg dulu bisa akses binance dan ganti di host nya, akhirnya bisa

13.224.7.78 binance.com 
13.224.7.78 www.binance.com

silahkan bisa di closed, terima kasih untuk semua team bebasid

**Comment by nxzlem** [comment]
> terima kasih untuk FIXnya, tapi barusan saya update dan coba belum bisa. saya coba ambil IP dari HOST lama ( bebasin ) yg dulu bisa akses binance dan ganti di host nya, akhirnya bisa
> 
> 13.224.7.78 binance.com 13.224.7.78 [www.binance.com](http://www.binance.com)
> 
> silahkan bisa di closed, terima kasih untuk semua team bebasid

Oke, sudah saya perbarui dengan IP baru digantikan ke IP lama, kakak boleh silakan ditutupkan isu anda.
