### ISSUE TITLE
[REQ] mangabuddy.com

### ISSUE THREAD

**Issue by YogaSakti** [bebasid/bebasid#474]
thanks

**Comment by nxzlem** [comment]
Halo kak @YogaSakti, sebagai situs mangabuddy.com belum ditambahkan dari hosts bebasid, saya tambahkan sekarang ya.
Silakan diperbarui hosts komputer anda selain perangkatnya juga, Agar hostnya tetap update ke versi terbaru. Issue anda akan ditutup setelah 3-7 hari terlewat. Jika ada masalah setelah issuenya tertutup atau sekarang. Tolong berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih! dari @nxzlem.
