### ISSUE TITLE
[BUG] kshow123.net

### ISSUE THREAD

**Issue by fadeltd** [bebasid/bebasid#475]
# Deskripsi mengenai bug
Buka di chrome internet positif
Tidak bisa buka di incognito/safari

https://github.com/bebasid/bebasid/blob/45c5cfb1ba6460436900960ce290d3f403dd5466/releases/hosts#L12498 Sepertinya update ke `104.21.78.19`

## Screenshot
<img width="575" alt="Screen Shot 2022-06-20 at 09 40 34" src="https://user-images.githubusercontent.com/4526413/174515839-ce0b73ee-08d3-4149-8958-f6d21ddcb20c.png">
<img width="1215" alt="Screen Shot 2022-06-20 at 09 41 37" src="https://user-images.githubusercontent.com/4526413/174515877-2b1172f6-97f3-4a3d-a261-c404439bf2c8.png">
<img width="683" alt="Screen Shot 2022-06-20 at 09 42 29" src="https://user-images.githubusercontent.com/4526413/174515893-5dae756d-74b1-48af-91ac-aa6147320112.png">

## Device
 - OS: macOS Monterey
 - Browser Chrome, Safari

**Comment by nxzlem** [comment]
Halo, kak @fadeltd, situs kshow123.net sudah diperbarui ya.
Silakan diperbarui hosts komputer anda selain untuk perangkatnya juga, agar hostnya tetap update ke versi terbaru. Jika issue anda belum ditutupkan dalam 3-7 hari, maka issue anda akan ditutup. Kalo ada masalah setelah issuenya tertutup atau masih terbuka/sekarang. Tolong berikan kenapa alesannya dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih dari @nxzlem.
