### ISSUE TITLE
[REQ] Steam/Dota

### ISSUE THREAD

**Issue by rekyb** [bebasid/bebasid#477]
Dikarenakan adanya PSE 😄, apakah memungkinkan untuk menambahkan Steam/Dota ke dalam database host? Terima kasih 🙇  

TKP: Makassar
ISP: Indosat, Telkomsel, dan XL

**Comment by Kampring** [comment]
https://inet.detik.com/law-and-policy/d-6206001/10-pse-terancam-diblokir-kominfo-ada-dota-steam-epic-games-dan-yahoo

sekedar menambahkan info untuk admin

**Comment by rekyb** [comment]
23.1.105.23 a23-1-105-23.deploy.static.akamaitechnologies.com
23.1.105.13 a23-1-105-13.deploy.static.akamaitechnologies.com
23.54.200.86 a23-54-200-86.deploy.static.akamaitechnologies.com 
23.1.105.21 a23-1-105-21.deploy.static.akamaitechnologies.com
23.1.105.6 a23-1-105-6.deploy.static.akamaitechnologies.com

**Comment by ceedadev** [comment]
Steam down
TKP: Surabaya
ISP: Biznet

**Comment by fijar-lazuardy** [comment]
sudah saya PR, semoga segera diliat admin repo

**Comment by rekyb** [comment]
> sudah saya PR, semoga segera diliat admin repo

GGWP, semoga cepet di approve. Sementara masih pake VPN dan nge-lag nya bukan main.

**Comment by zephyroths** [comment]
Steam down
TPK: Palangka Raya
ISP: Indihome

**Comment by dickyindra** [comment]
Steam down
TKP: Jakarta Selatan
ISP: Firstmedia

**Comment by gvoze32** [comment]
Bisa dicek untuk dotanya sekarang apakah sudah bisa @rekyb

**Comment by rekyb** [comment]
@gvoze32 Untuk Steam launcher udah bisa login, Dota udah bisa masuk lobby. Untuk Steam launcher, store page masih belum ke load. Untuk dota belum bisa find match.

**Comment by zephyroths** [comment]
untuk steam store sama wishlistnya udah bisa dibuka

**Comment by rekyb** [comment]
Update:

- Steam udah bisa kebuka semua kecuali fitur chat/friend list.
- Dota udah bisa finding match

![Untitled2](https://user-images.githubusercontent.com/29610518/181905347-0c462817-6516-4eda-a692-4f256c85a23e.png)
 
![Untitled](https://user-images.githubusercontent.com/29610518/181905343-f59ad8d0-add3-4996-9950-95d708a569d7.png)

Tiketnya boleh di tutup kalau nggak ada lagi update. Terima kasih banyak semuanya. 🙏

**Comment by Kampring** [comment]
yang closed ente sebagai thread starternya bro, kemarin ane juga gitu :)

**Comment by rekyb** [comment]
> yang closed ente sebagai thread starternya bro, kemarin ane juga gitu :)

wkwkwk wokeh bro, takutnya masih ada yang mau update. Yowes ane tutup deh.

**Comment by lintangtimur** [comment]
kok tetep ga bisa ya

**Comment by rekyb** [comment]
Coba pake [Bebasit](https://bebasid.github.io/bebasit/) @lintangtimur 

Sekedar info: https://www.liputan6.com/tekno/read/5028629/blokir-steam-segera-dibuka-kominfo-valve-saat-ini-sedang-lengkapi-berkas

**Comment by nxzlem** [comment]
Isu ini akan ditutupkan karena sudah diunblock oleh PSE. Terimakasih.
