### ISSUE TITLE
[REQ] Paypal

### ISSUE THREAD

**Issue by thatismunn** [bebasid/bebasid#479]
Mengingat PSE diberlakukan hari ini, adapun #477 dan Paypal saat ini yang jadi korbannya. Diperkirakan TKP di seluruh Indonesia dikarenakan trending di Twitter.

**Comment by fjr619** [comment]
ini paypal masih ga bisa nih di biznet

**Comment by nxzlem** [comment]
Isu ini akan ditutupkan karena sudah diunblock oleh PSE. Terimakasih.
