### ISSUE TITLE
[BUG] Rockstar Games Social Club

### ISSUE THREAD

**Issue by Vaerrwenn** [bebasid/bebasid#487]
**Deskripsi mengenai bug**
Ketika pakai file hosts yg di generate, gabisa connect ke Rockstar Games Launcher. Namun, ketika saya comment bagian Rockstar nya, bisa connect.

**Screenshot**
![Screenshot 2022-07-31 123454](https://user-images.githubusercontent.com/11299005/182011996-010ac332-fbad-4d3b-a3b2-505fab38c09f.jpg)

**Device**
 - OS: Windows 11
 - Browser: -

**Comment by nxzlem** [comment]
isu duplikat baru: #492

**Comment by nxzlem** [comment]
halo kak. untuk saat ini, apakah masih bisa terhubung ke rockstar games social club atau masih belum bisa?
ada 2 commit pembaruan di hosts bebasid, silakan di cek ya.
https://github.com/bebasid/bebasid/commit/50d707ba0000ebc472f87454c2c4aaea63ee5830 https://github.com/bebasid/bebasid/commit/5fd6a0499bbd61f12d15e6a3008cd6341cd66e50
jangan lupa diupdate terlebih dahulu. kalo sudah terhubung, isu nya boleh ditutupkan.
jika masih belum bisa, silakan di komentar ya. terimakasih.

**Comment by nxzlem** [comment]
Halo kak, kakak masih bisa berfungsi untuk mengkoneksi ke rockstargames? Jika belum bisa, tolong dijelaskan ya. Terimakasih
isu anda akan ditutupkan dalam 7 hari setelah masih belum ada respon untuk balasan nya anda.

**Comment by nxzlem** [comment]
integrating the same issue with #511
