### ISSUE TITLE
[BUG] Steam profile picture not loaded (CSGO)

### ISSUE THREAD

**Issue by sl0zy** [bebasid/bebasid#488]
Steam dan CSGO

**Deskripsi mengenai bug**
Deskripsi yang jelas dan ringkas tentang apa yang terjadi.
Profile picture steam gak keload sampai di ingame csgo pun gak keload (Saya bingung jelasinnya)

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.
![1](https://user-images.githubusercontent.com/35650680/182012752-3abf32c4-a909-4789-a040-dfdf5154b1fa.png)
![2](https://user-images.githubusercontent.com/35650680/182012755-45c5a572-aa6e-424f-83d2-e00e3b128403.png)
![3](https://user-images.githubusercontent.com/35650680/182012762-74f9302d-d911-477e-8c94-b4a22aba6dff.png)
![unknown](https://user-images.githubusercontent.com/35650680/182012765-52381ef6-cf10-4929-8324-1e08953a2b94.png)

**Device**
 - OS: windows 10
 - Browser: chrome

**Comment by nxzlem** [comment]
Isu ini akan ditutupkan karena sudah diunblock oleh PSE. Terimakasih.
