### ISSUE TITLE
[BUG] Gagal Menginstall Bebasid di Windows 8.1

### ISSUE THREAD

**Issue by dikallagher** [bebasid/bebasid#489]
**Deskripsi mengenai bug**
Telah 2 bulan ini saya tidak bisa menginstall bebasid di PC saya, sebelumnya saya downgrade dari Windows 11 ke Windows 8.1 (Potato Version)

**Screenshot**
![bebasid bug](https://user-images.githubusercontent.com/47213364/182016552-5db25dc5-dcbd-4ec4-a8af-2968ded213c1.PNG)

**Device**
 - OS: [Windows 8.1]

**Comment by gvoze32** [comment]
@dikallagher Silahkan gunakan versi .exe dari bebasid
