### ISSUE TITLE
[REQ] Epic Games

### ISSUE THREAD

**Issue by Rokuazery** [bebasid/bebasid#490]
Epic Games gak bisa konek
![image](https://user-images.githubusercontent.com/48817307/182087508-bf6ec6ba-8113-4e6c-a812-82fc63005409.png)

**ISP:** Indihome

**Comment by gvoze32** [comment]
https://github.com/bebasid/bebasid/commit/af8268ce44ce3fb176bc49cf84e0f86d32139153

Silahkan update dan jika sudah bekerja, silahkan bisa menutup issue
