### ISSUE TITLE
[BUG] book.dmm.com

### ISSUE THREAD

**Issue by 0xh3LL0** [bebasid/bebasid#491]
**Deskripsi mengenai bug**
book.dmm.com tak bisa di buka
kayaknya ganti ip
![Screenshot 2022-08-01 at 15-03-11 Find IP Address Of Your Website, Server or Domain Site24x7 Tools](https://user-images.githubusercontent.com/23132217/182102329-efd2dc17-ecfb-4efd-9567-690c52aac227.png)
di bebasid
![ccccccccccccc](https://user-images.githubusercontent.com/23132217/182102585-06c2c128-9980-4089-b53e-20fae6d175f6.png)

**Device**
 - OS: win 10
 - Browser: firefox 96.3

**Comment by nxzlem** [comment]
Halo, kak @0xh3LL0, situs subdomain book.dmm.com sudah diperbarui ya.
Silakan diperbarui hosts komputer anda selain untuk perangkatnya juga, agar hostnya tetap update ke versi terbaru. Jika issue anda belum ditutupkan dalam 3-7 hari, maka issue anda akan ditutup. Kalo ada masalah setelah issuenya tertutup atau masih terbuka/sekarang. Tolong berikan kenapa alesannya dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih dari @nxzlem.

**Comment by 0xh3LL0** [comment]
ternyata masih kurang kayaknya,
dmm.com ada relasi sama dmm.co.jp,
book.dmm.com blom bisa di buka karena
rcv.ixd.dmm.co.jp masih di blokir

tolong di tambahkan
terima kasih

**Comment by gvoze32** [comment]
https://github.com/bebasid/bebasid/commit/af8268ce44ce3fb176bc49cf84e0f86d32139153

Silahkan update dan jika sudah bekerja, silahkan bisa menutup issue

**Comment by 0xh3LL0** [comment]
yang bener rcv.ixd.dmm.**co.jp** bukan rcv.ixd.dmm.**com**
![qqqqqqqq](https://user-images.githubusercontent.com/23132217/183364709-7116319a-096e-47e2-9487-3c9232260dea.png)

**Comment by 0xh3LL0** [comment]
makasih.

**Comment by 0xh3LL0** [comment]
book.dmm.com gak bisa di akses lagi

**Comment by nxzlem** [comment]
Oke, silakan di update lagi ya. terimakasih.

**Comment by 0xh3LL0** [comment]
makasih
