### ISSUE TITLE
[BUG] rockstargames.com

### ISSUE THREAD

**Issue by ariexx** [bebasid/bebasid#492]
**Deskripsi mengenai bug**
Untuk website rockstargames.com tidak bisa dibuka "took long respond" tetapi untuk subdomain dll aman, dan game seperti
rdr2 online tidak bisa di akses fiture online, selalu kena kode 0x10001038

**Device**
 - OS: Windows 11 Pro
 - Browser Chrome

**Comment by nxzlem** [comment]
isu ini sudah ada yang isu sebelumnya: #487

**Comment by nxzlem** [comment]
halo kak. untuk saat ini, apakah masih bisa terhubung ke rockstar games atau masih belum bisa?
ada 2 commit pembaruan di hosts bebasid, silakan di cek ya.
https://github.com/bebasid/bebasid/commit/50d707ba0000ebc472f87454c2c4aaea63ee5830 https://github.com/bebasid/bebasid/commit/5fd6a0499bbd61f12d15e6a3008cd6341cd66e50
jangan lupa diupdate terlebih dahulu. kalo sudah terhubung, isu nya boleh ditutupkan.
jika masih belum bisa, silakan di komentar ya. terimakasih.

**Comment by nxzlem** [comment]
Halo kak, kakak masih bisa berfungsi untuk mengkoneksi ke rockstargames? Jika belum bisa, tolong dijelaskan ya. Terimakasih
isu anda akan ditutupkan dalam 10 hari setelah masih belum ada respon untuk balasan nya anda.

**Comment by ariexx** [comment]
untuk kali ini aman sih, terimakasih udah mau susah payah bangun ini project

**Comment by nxzlem** [comment]
Baik kak. Kalo begitu, izinkan untuk menutupkan isu anda sekarang, terimakasih.
