### ISSUE TITLE
[REQ] junmeitu.com

### ISSUE THREAD

**Issue by 12345axc** [bebasid/bebasid#493]
junmeitu.com masuk di daftar trustpositif

**Comment by gvoze32** [comment]
https://github.com/bebasid/bebasid/commit/2853c6c5665f65812a9a867658202b7fc8f8a382

Silahkan update dan jika sudah bekerja, silahkan bisa menutup issue

**Comment by mrtampan** [comment]
> junmeitu.com masuk di daftar trustpositif

update aja langsung di file hostnya.

nyari IP nya tinggal ping aja via cmd atau bisa pake tools ini https://www.yougetsignal.com/tools/web-sites-on-web-server/

**Comment by nxzlem** [comment]
Oke, silakan di update ya. terimakasih.

**Comment by nxzlem** [comment]
Halo kak, izinkan saya tutupkan isu untuk hari ini ya. Karena belum ada respon, saya akan tutupkan untuk sekarang.
Jika masih ada masalah, silakan buka issue dan jelaskan.
Terimakasih.
