### ISSUE TITLE
[REQ] kemono.party

### ISSUE THREAD

**Issue by 12345axc** [bebasid/bebasid#497]
https://kemono.party masuk di daftar pemblokiran TrustPositif

**Comment by nxzlem** [comment]
Halo mas @12345axc, sebagai situs kemono.party belum ditambahkan dari hosts bebasid, saya tambahkan sekarang ya.
Silakan diperbarui hosts komputer anda selain perangkatnya juga, Agar hostnya tetap update ke versi terbaru. Issue anda akan ditutup setelah 3-7 hari terlewat. Jika ada masalah setelah issuenya tertutup atau sekarang. Tolong berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih! dari @nxzlem.

**Comment by 12345axc** [comment]
Terima kasih bang!
