### ISSUE TITLE
[BUG] example.com

### ISSUE THREAD

**Issue by mfauzanf** [bebasid/bebasid#5]
**Deskripsi mengenai bug**
https://1337x.to/ masih belum bisa diakses melalui jaringan indihome

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.

**Device**
 - OS: Windows 10
 - Browser : Chrome

**Comment by icaksh** [comment]
File hosts disarankan memasang secara manual dahulu (unduh file hostsnya, lalu timpa ke C:/Windows/system32/drivers/etc ) sambil menunggu aplikasi BEBASID.exe diupdate.

![image](https://user-images.githubusercontent.com/19889081/76137744-cbcd7780-6072-11ea-9812-6793218f905b.png)

Tampilan saat ditimpa manual

![image](https://user-images.githubusercontent.com/19889081/76137840-17345580-6074-11ea-810b-1b53ffc388a8.png)

Tampilan saat mengganti file hosts dengan aplikasi BEBASID
