### ISSUE TITLE
[REQ] exhentai.org

### ISSUE THREAD

**Issue by WhoSainT518** [bebasid/bebasid#50]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts

**Comment by nxzlem** [comment]
Sorry gans, situs exhentai.org sdh turun karena liat deskripsi di sini.
![chrome_4Ec6epIKSM](https://user-images.githubusercontent.com/30078972/78787925-458bb480-79d5-11ea-88e7-19bd9613023d.png)
