### ISSUE TITLE
[BUG] toonily.com

### ISSUE THREAD

**Issue by Nosoba** [bebasid/bebasid#500]
Makasih.

**Comment by nxzlem** [comment]
Halo, kak @Nosoba, situs toonily.com sudah diperbarui ya.
Silakan diperbarui hosts komputer anda selain untuk perangkatnya juga, agar hostnya tetap update ke versi terbaru. Jika issue anda belum ditutupkan dalam 3-7 hari, maka issue anda akan ditutup. Jika masih ada masalah setelah issuenya baru tertutup. Silakan di re-open issue nya dan berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih dari @nxzlem.
