### ISSUE TITLE
[REQ] javfinder.li

### ISSUE THREAD

**Issue by bobibesar** [bebasid/bebasid#501]

**Comment by nxzlem** [comment]
Halo kak @bobibesar, sebagai situs javfinder.li belum ditambahkan dari hosts bebasid, saya tambahkan sekarang ya.
Silakan diperbarui hosts komputer anda selain perangkatnya juga, Agar hostnya tetap update ke versi terbaru. Jika issue anda belum ditutupkan dalam 3-7 hari, maka issue anda akan ditutup. Jika masih ada masalah setelah issuenya baru tertutup. Silakan di re-open issue nya dan berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih! dari @nxzlem.
