### ISSUE TITLE
[REQ] micmicdoll.com

### ISSUE THREAD

**Issue by 12345axc** [bebasid/bebasid#503]
Situs masuk daftar trust positif

**Comment by nxzlem** [comment]
Halo kak @12345axc, sebagai situs micmicdoll.com belum ditambahkan dari hosts bebasid, saya tambahkan sekarang ya.
Silakan diperbarui hosts komputer anda selain perangkatnya juga, Agar hostnya tetap update ke versi terbaru. Jika issue anda belum ditutupkan dalam 3-7 hari, maka issue anda akan ditutup. Jika masih ada masalah setelah issuenya baru tertutup. Silakan di re-open issue nya dan berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih! dari @nxzlem.

**Comment by 12345axc** [comment]
Terima kasih min!

**Comment by nxzlem** [comment]
baik, sama-sama.
