### ISSUE TITLE
[REQ] rawmanga.cc

### ISSUE THREAD

**Issue by 12345axc** [bebasid/bebasid#504]
situs ada di trustpositif

**Comment by nxzlem** [comment]
Halo kak @12345axc, sebagai situs rawmanga.cc belum ditambahkan dari hosts bebasid, saya tambahkan sekarang ya.
Silakan diperbarui hosts komputer anda selain perangkatnya juga, Agar hostnya tetap update ke versi terbaru. Jika issue anda belum ditutupkan dalam 3-7 hari, maka issue anda akan ditutup. Jika masih ada masalah setelah issuenya baru tertutup. Silakan di re-open issue nya dan berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih! dari @nxzlem.
