### ISSUE TITLE
[BUG] nhentai.net

### ISSUE THREAD

**Issue by muzzin-ctrl** [bebasid/bebasid#505]
**Deskripsi mengenai bug**
gak muncul gambarnya 

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.

**Device**
 - OS: [cth. Windows 10]
 - Browser [cth. Chrome, Firefox]

**Comment by nxzlem** [comment]
bisa kah anda sertakan foto gambar2nya yang tidak muncul?

**Comment by muzzin-ctrl** [comment]
![nh](https://user-images.githubusercontent.com/78278322/187026838-c659acfd-cd3c-43f1-82cc-fd111abdd053.png)
apa cuma gw doang yg begini tampilannya ? pake firstmedia nih

**Comment by nxzlem** [comment]
> ![nh](https://user-images.githubusercontent.com/78278322/187026933-cb36da9a-0c74-4f14-831d-d7055f13f191.png) apa cuma gw doang yg begini tampilannya ? pake firstmedia nih

@muzzin-ctrl apakah sudah diupdate perangkat hosts anda? silakan cek dulu pakai notepad atau notepad++ lalu periksa dan cari tulisan nhentai.net terus kakak screenshot untuk bagian IP nya. nanti saya cek apakah hosts anda dan dari hosts bebasid itu ada bedanya.

**Comment by muzzin-ctrl** [comment]
![nh](https://user-images.githubusercontent.com/78278322/187041463-be9e4d91-502e-4c14-a431-3e2300abfa3d.png)

**Comment by nxzlem** [comment]
Halo, kak @muzzin-ctrl, situs nhentai.net sudah diperbarui ya.
Silakan diperbarui hosts komputer anda selain untuk perangkatnya juga, agar hostnya tetap update ke versi terbaru. Jika issue anda belum ditutupkan dalam 3-7 hari, maka issue anda akan ditutup. Jika masih ada masalah setelah issuenya baru tertutup. Silakan di re-open issue nya dan berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih dari @nxzlem.
