### ISSUE TITLE
[BUG] epicgames.com

### ISSUE THREAD

**Issue by crse** [bebasid/bebasid#506]
Removal request: Epic Games sudah bisa diakses tanpa host.

Versi saat ini malah membuat EG tidak bisa diakses sama sekali.

**Comment by crse** [comment]
Habis reinstall host, entah kenapa langsung bisa 🤔

**Comment by nxzlem** [comment]
Halo kak,
 Apakah anda sudah diupdatekan hosts ke terbaru? Silakan coba hapuskan seluruh di ``# [epicgames.com]`` dari hosts anda terlebih dahulu.
 Masih jika tidak bisa, mohon buktikan foto dan serta detailnya saat tidak bisa membuka situsnya.
 Terimakasih.

**Comment by nxzlem** [comment]
Oh ya, saya punya 1 pertanyaan.
Anda ISP nya apa? 
Jika anda memakai Indihome, mungkin agak throttle saat buka situsnya.

**Comment by gvoze32** [comment]
https://github.com/bebasid/bebasid/commit/a135f80a5eab7375da49754cde9a8c5516f8b4de
