### ISSUE TITLE
[REQ] jpopblog.com

### ISSUE THREAD

**Issue by 12345axc** [bebasid/bebasid#507]
masuk daftar trust positif

**Comment by nxzlem** [comment]
Halo kak @12345axc, sebagai situs jpopblog.com belum ditambahkan dari hosts bebasid, @gvoze32 sudah ditambahkan barusan ya. Maafkan atas kami untuk belum perbarui untuk situs hostsnya.
Silakan diperbarui hosts komputer anda selain perangkatnya juga, Agar hostnya tetap update ke versi terbaru. Jika issue anda belum ditutupkan dalam 3-7 hari, maka issue anda akan ditutup. Jika masih ada masalah setelah issuenya baru tertutup. Silakan di re-open issue nya dan berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih! dari @nxzlem.
