### ISSUE TITLE
Netflix tidak bisa diakses dengan Ind*H*** di MacOS

### ISSUE THREAD

**Issue by indrawp** [bebasid/bebasid#51]
**Deskripsi mengenai bug**
Sudah melakukan instalasi hosts bebas ID, akses ke web lain (seperti reddit) bisa

**Screenshot**
<img width="654" alt="Screen Shot 2020-04-06 at 1 29 12 PM" src="https://user-images.githubusercontent.com/42365530/78528880-a4510280-780a-11ea-9162-cccfbd3e95cd.png">

**Device**
 - OS: MacOS Catalina
 - Browser Chrome

**Comment by nxzlem** [comment]
Kamu harus install GreenTunnel dari sini :
https://github.com/bebasid/bebasid/blob/master/dev/readme/NETFLIX.md
(Bawah yg ada MacOS)

**Comment by nxzlem** [comment]
GreenTunnel : https://github.com/SadeghHayeri/GreenTunnel
PowerTunnel : https://github.com/krlvm/PowerTunnel/releases

**Comment by indrawp** [comment]
Yap, ini kondisi sudah install & jalankan GreenTunel kok

**Comment by nxzlem** [comment]
Berarti Reinstall dulu, situ coba buka situs Netflix lagi

**Comment by indrawp** [comment]
Sorry tapi ini problemnya bukan di GreenTunnel kayaknya, karena akses netflix tanpa hosts modifikasi pun ga bisa. Ekspektasinya kan muncul "Whoops, something went wrong...".

**Comment by nxzlem** [comment]
Hmm, Tunggu dulu ya nanti devnya respond.

**Comment by indrawp** [comment]
Bisa dibuka lagi issue ini?
Untuk Android sementara Netflix bisa diakses dengan App Intra (loading movie cukup lama, tapi setelah load langsung lancar streaming). Untuk Mac sedang coba alternatif dengan OpenVPN, saat ini stuck di "Pardon The Interruption" saat play movie.

**Comment by battdrr** [comment]
Untuk mac coba pakai tunnelblick lalu buat vpn nya di tcpvpn.com pilih server indonesia, jangan lupa untuk download dan load config openvpn server indonesianya dari tcpvpn

**Comment by indrawp** [comment]
Confimed working, thanks @battdrr
