### ISSUE TITLE
[BUG] Redgifs error

### ISSUE THREAD

**Issue by Xyzpqrabc** [bebasid/bebasid#510]
Redgifs ga bisa munculin video dan ga bisa login/sign up, selalu mental ke internet positif.

**Comment by nxzlem** [comment]
Halo kak, @Xyzpqrabc. 

Situs nhentai.net sudah diperbarui oleh @gvoze32 ya.
Maafkan atas kami untuk belum perbarui untuk situs hostsnya.

Silakan diperbarui hosts komputer anda selain untuk perangkatnya juga, agar hostnya tetap update ke versi terbaru. Jika issue anda belum ditutupkan dalam 3-7 hari, maka issue anda akan ditutup. Jika masih ada masalah setelah issuenya baru tertutup. Silakan di re-open issue nya dan berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.

Sekian, Terimakasih dari @nxzlem.
