### ISSUE TITLE
[BUG] socialclub.rockstargames.com

### ISSUE THREAD

**Issue by IvanFerdino** [bebasid/bebasid#511]
**Deskripsi mengenai bug**
- menggunakan host NSFW, ketika akses situs: https://socialclub.rockstargames.com/rockstar-games-launcher -> kemudian pencet tombol download launcher. akan error (seperti di blokir oleh rockstar games).
- Pada aplikasi rockstar Game Launcher juga tidak bisa terkoneksi dengan internet ketika menggunakan host NSFW. rockstar launcher error 3000.108

**Device**
 - OS: Windows 11
 - Semua Browser ketika pakai host NSFW. dan juga pada aplikasi Rockstart Games Launcher

**Comment by nxzlem** [comment]
halo kak, maaf
kenapa tidak menggantikan dengan hosts yang gabungan aja tanpa hosts nsfw/sfw terlebih dahulu.
pakaikan saja yang dipilih ini dulu, ya
https://raw.githubusercontent.com/bebasid/bebasid/master/releases/hosts
sekian terimakasih

**Comment by nxzlem** [comment]
bolehkah anda sertakan gambar terlebih dahulu? tanpa gambar, susah untuk mencari lebih detail nya.

**Comment by nxzlem** [comment]
sama dengan isu ini di bagian #487, tapi sudah ditutupkan.

**Comment by jpearce279** [comment]
Sama bro, socialclub gabisa dibuka. Saya pake ISP indihome
di chrome error nya "ERR_CONNECTION_TIMED_OUT"

**Comment by nxzlem** [comment]
> Sama bro, socialclub gabisa dibuka. Saya pake ISP indihome di chrome error nya "ERR_CONNECTION_TIMED_OUT"
> 
> Rockstar Games Launcher juga gabisa connect

Indihome ya, mugnkin ada masalah dengan throttle?
