### ISSUE TITLE
[BUG] twitter.com

### ISSUE THREAD

**Issue by muzzin-ctrl** [bebasid/bebasid#512]
**Deskripsi mengenai bug**
gw gak tau ini masuknya bug apa request , tp pemerintah mulai ngeblokir akun2 NSFW di twitter ... 
yg gw follow emg blm ada yg kena , tp pasti ntar merembet kena blokir satu per satu ..

**Screenshot**
![fue](https://user-images.githubusercontent.com/78278322/192964607-63ca3a09-02b2-4273-95a6-6296d15256e6.png)

**Device**
 - OS: [cth. Windows 10]
 - Browser [cth. Chrome, Firefox]

**Comment by RacBallonMC** [comment]
https://www.reddit.com/r/indonesia/comments/xquc6r/baru_pertama_kali_liat_account_withheld_in/

**Comment by heywolf15** [comment]
Hampir sama masalahnya sama catbox.moe, akun gua ada nomor +62 tapi bisa dibuka pake VPN. Setelah kebuka akunnya, matiin VPN itu masih bisa scroll ke bawah dan ke load semua tweet, gambar, video. Yg cuma gua tau pemblokiran secara nomor negara untuk R18 itu Telegram.
Atau coba pake alternative frontends kaya Nitter. Untuk lebih jelasnya [https://github.com/zedeus/nitter](url)
Biar lebih gampang untuk berbagai macam alternative frontends, extension [https://github.com/libredirect/libredirect](url)
Kalo bingung atau mau tanya, reply aja.

**Comment by Nuginity** [comment]
Account withheld twitter tidak akan bisa dibypass hanya dengan merubah hosts file. Twitter membaca geolokasi IP address device yang kita pakai. salah satu cara untuk membypassnya mau tidak mau harus menggunakan VPN, Proxy atau Tunneling
