### ISSUE TITLE
[REQ] okx.com

### ISSUE THREAD

**Issue by YogaSakti** [bebasid/bebasid#513]

**Comment by nxzlem** [comment]
Halo kak @YogaSakti, sebagai situs okx.com belum ditambahkan dari hosts bebasid, @gvoze32 sudah ditambahkan barusan ya. Maafkan atas kami untuk belum perbarui untuk situs hostsnya.
Silakan diperbarui hosts komputer anda selain perangkatnya juga, Agar hostnya tetap update ke versi terbaru. Jika issue anda belum ditutupkan dalam 3-7 hari, maka issue anda akan ditutup. Jika masih ada masalah setelah issuenya baru tertutup. Silakan di re-open issue nya dan berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.
Sekian, Terimakasih! dari @nxzlem.

**Comment by nxzlem** [comment]
> Thanks b4, ini versi webnya ya? Gw pake xl di mobile app kenapa masih gabisa ya

Untuk di mobile app ya?
Kalo untuk web nya bisa dibuka tidak?

**Comment by nxzlem** [comment]
Halo kak.

Apakah bisa pindah diskusi ke server discord bebasid? 
Jika tidak merespon, saya akan tutupkan isu ini. 
Silakan di re-open lagi kalo mau respon sekarang.

Terimakasih.
