### ISSUE TITLE
[BUG] mangakakalot.com

### ISSUE THREAD

**Issue by muzzin-ctrl** [bebasid/bebasid#517]
**Deskripsi mengenai bug**
pake firstmedia gak mau kebuka situsnya

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.

**Device**
 - OS: [cth. Windows 10]
 - Browser [cth. Chrome, Firefox]

**Comment by nxzlem** [comment]
Halo, kak @muzzin-ctrl.
Situs mangakakalot.com sudah diperbarui ya.

Tolong diperbarui hosts komputer anda selain untuk perangkatnya juga, agar hostnya tetap update ke versi terbaru. 
Issue anda akan ditutup dalam 3-7 hari bila tidak ada respon nya.  Jika masih ada masalah setelah issuenya baru tertutup. Silakan di re-open issue nya dan berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.

Sekian, Terimakasih.
dari @nxzlem.

**Comment by CriminalHijinix** [comment]
👀
