### ISSUE TITLE
[BUG] javdatabase.com

### ISSUE THREAD

**Issue by muzzin-ctrl** [bebasid/bebasid#518]
**Deskripsi mengenai bug**
gak bisa dibuka dgn firstmedia

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.

**Device**
 - OS: [cth. Windows 10]
 - Browser [cth. Chrome, Firefox]

**Comment by nxzlem** [comment]
Halo kak, @muzzin-ctrl.

Situs javdatabase.com sudah diperbarui oleh @gvoze32 ya.
Maafkan atas kami untuk belum perbarui untuk situs hostsnya.

Silakan diperbarui hosts komputer anda selain untuk perangkatnya juga, agar hostnya tetap update ke versi terbaru. Issue anda akan ditutup dalam 3-7 hari bila tidak ada respon nya. Jika masih ada masalah setelah issuenya baru tertutup. Silakan di re-open issue nya dan berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.

Sekian, Terimakasih.
dari @nxzlem.
