### ISSUE TITLE
[BUG] idol.sankakucomplex.com

### ISSUE THREAD

**Issue by AgusHerculeng** [bebasid/bebasid#520]
Gambar thumbnailnya gk muncul

**Comment by nxzlem** [comment]
Halo kak, @AgusHerculeng.
Saya menemukan, situs subdomain iv.sankakucomplex.com belum diperbarui dan sudah digantikan IP nya ya.

Silakan diperbarui hosts komputer anda selain untuk perangkatnya juga, agar hostnya tetap update ke versi terbaru. Issue anda akan ditutup dalam 3-7 hari bila tidak ada respon nya. Jika masih ada masalah setelah issuenya baru tertutup. Silakan di re-open issue nya dan berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.

Sekian, Terimakasih.
dari @nxzlem.
