### ISSUE TITLE
[REQ] koushoku.org

### ISSUE THREAD

**Issue by AgusHerculeng** [bebasid/bebasid#521]

**Comment by nxzlem** [comment]
Halo kak, @AgusHerculeng.
Sebagai situs koushoku.org belum ditambahkan dari hosts bebasid, saya tambahkan sekarang ya.

Silakan diperbarui hosts komputer anda selain untuk perangkatnya juga, agar hostnya tetap update ke versi terbaru. Issue anda akan ditutup dalam 3-7 hari bila tidak ada respon nya. Jika masih ada masalah setelah issuenya baru tertutup. Silakan di re-open issue nya dan berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.

Sekian, Terimakasih.
dari @nxzlem.
