### ISSUE TITLE
[BUG] bebasid.exe tidak dapat dijalankan pada Windows 11

### ISSUE THREAD

**Issue by mangkoran** [bebasid/bebasid#524]
**Deskripsi mengenai bug**
`bebasid.exe` tidak dapat dijalankan pada Windows 11. bebasid akan jalan sekejap/sebentar (saya cek Task Manager) tetapi akan langsung keluar/exit.

**Screenshot**
Not applicable

**Device**
```
Edition	        Windows 11 Pro
Version	        22H2
Installed on	‎2022-‎09-‎21
OS build	    22621.900
Experience	    Windows Feature Experience Pack 1000.22638.1000.0
```

**Comment by gvoze32** [comment]
Boleh dicoba dengan cara menghapus file hosts dan hosts-bebasid.bak kemudian restart dan buka kembali.

Kalau masih tidak bisa maka coba pakai cara manual dulu dengan mengcopy file hosts ke direktori hosts sistem, kemudian jalankan aplikasi bebasid.

**Comment by mangkoran** [comment]
Setelah menghapus file `hosts` dan `hosts-bebasid.bak`, aplikasi dapat dibuka dan digunakan. Thank you!

**Comment by mangkoran** [comment]
Selamat pagi. Saya mengalami isu ini kembali. Walaupun bisa di _workaround_ dengan menghapus `hosts-bebasid.bak`, saya pikir ini bukanlah hal yang bagus untuk solusi permanen. Apakah kita dapat melihat log dari `bebasid.exe` ?

**Comment by gvoze32** [comment]
Masalah ini kembali terjadi dikarenakan website bebasid yang di mana tempat menyimpan mirror file hosts sedang down. Saat ini sedang dilakukan pemulihan sistem, beberapa saat lagi seharusnya sudah kembali normal.

**Comment by gvoze32** [comment]
> Selamat pagi. Saya mengalami isu ini kembali. Walaupun bisa di _workaround_ dengan menghapus `hosts-bebasid.bak`, saya pikir ini bukanlah hal yang bagus untuk solusi permanen. Apakah kita dapat melihat log dari `bebasid.exe` ?

Untuk melihat kode atau log dari aplikasi bebasid.exe, Anda bisa build sendiri dari source https://github.com/bebasid/bebasid-src.

**Comment by nxzlem** [comment]
Permisi, @mangkoran.

Jika tidak ada pertanyakan lagi, saya akan melakukan tutup isu ini.
Anda bisa membuka isu ini bila anda mau masih lanjut dalam pertanyaannya.

Terimakasih.
