### ISSUE TITLE
[BUG] movies123.show

### ISSUE THREAD

**Issue by rizkireynaldi** [bebasid/bebasid#525]

**Comment by nxzlem** [comment]
halo kak, situs movies123.show sudah ada dari hosts bebasid.

**Comment by nxzlem** [comment]
Karena belum dijawab pertanyaan, saya akan tutupkan isu ini. Jika anda mau di re-open, silakan kasih situs dan gambar website yang tidak bisa akses/muat tampilannya. Sekian terimakasih.
