### ISSUE TITLE
[BUG] mexc.com

### ISSUE THREAD

**Issue by Kampring** [bebasid/bebasid#526]

**Comment by nxzlem** [comment]
halo kak, situs movies123.show sudah ada dari hosts bebasid. apakah sudah diperbarui hosts perangkat anda?

**Comment by Kampring** [comment]
Baik, setelah saya cek memang sudah ada di host, tapi belum bisa di akses, berikut tracertnya 

![image](https://user-images.githubusercontent.com/10830722/208325089-cf6dbd75-bf66-4ab2-91a4-a9a4f9917f35.png)

saya coba akses pakai "m.mexc,com" , baru bisa kebuka

![image](https://user-images.githubusercontent.com/10830722/208325153-b2b4307e-43c2-48f9-b683-bebea7e6f457.png)

**Comment by nxzlem** [comment]
sebentar ya, 

> Baik, setelah saya cek memang sudah ada di host, tapi belum bisa di aksesm ISP Ind*Ho**, berikut tracertnya
> 
> ![image](https://user-images.githubusercontent.com/10830722/208325089-cf6dbd75-bf66-4ab2-91a4-a9a4f9917f35.png)
> 
> saya coba akses pakai "m.mexc,com" , baru bisa kebuka
> 
> ![image](https://user-images.githubusercontent.com/10830722/208325153-b2b4307e-43c2-48f9-b683-bebea7e6f457.png)

oke, ntar saya periksain situs mexc.com untuk perbarui ipnya

**Comment by Kampring** [comment]
ada 3 IP di host 

www.mexc.com --->  Bisa
m.mexc.com ---> Bisa
mexc.com  ---> tidak bisa

biasanya ane kalau browsing ga nulis "www", barusan ane akalin saja IP "mexc.com" diganti menggunakan IP nya "www.mexc.com", aman sentosa

**Comment by nxzlem** [comment]
> ada 3 IP di host
> 
> [www.mexc.com](http://www.mexc.com) ---> Bisa m.mexc.com ---> Bisa mexc.com ---> tidak bisa
> 
> biasanya saya kalau browsing ga nulis "www", barusan saya akalin saja IP "mexc.com" diganti menggunakan IP nya "www.mexc.com", aman sentosa
> 
> jadi menurut saya sudah bisa diclose , terima kasih

`43.154.82.226 mexc.com` ganti aja dengan `72.247.81.144 mexc.com`. ntar saya akan perbarui hosts bebasidnya

**Comment by nxzlem** [comment]
Halo kak, @Kampring.

Situs mexc.com sudah diperbarui ya.

Silakan diperbarui hosts komputer anda selain untuk perangkatnya juga, agar hostnya tetap update ke versi terbaru. Issue anda akan ditutup dalam 3-7 hari bila tidak ada respon nya. Jika masih ada masalah setelah issuenya baru tertutup. Silakan di re-open issue nya dan berikan alesannya kenapa dan buktinya yang tidak bisa berfungsi.

Sekian, Terimakasih.
dari @nxzlem.

**Comment by Kampring** [comment]
Terima kasih untuk updatenya
