### ISSUE TITLE
"Install dulu GreenTunnelnya"

### ISSUE THREAD

**Issue by kaizenlolo** [bebasid/bebasid#53]
GreenTunnel sudah terinstall, namun masih muncul "install dulu Green tunnelnya"

**Pict.1**
![image](https://user-images.githubusercontent.com/46082759/78643358-59a0ba80-78de-11ea-8059-491b18d6dc84.png)

**Pict.2**
![image](https://user-images.githubusercontent.com/46082759/78643474-8359e180-78de-11ea-84f7-f9bcf650ede0.png)

**Device**
 - OS: MacOS Catalina
 - Browser Chrome

**Comment by icaksh** [comment]
Gunakan bash yang baru, pakai yang khusus untuk mac

**Comment by kaizenlolo** [comment]
masih gabisa ya? bash nya udah 5.0.16(1)-release tapi masih ada install dulu greentunnel nya
