### ISSUE TITLE
[BUG] redgifs.com

### ISSUE THREAD

**Issue by vercouver** [bebasid/bebasid#530]
Redgifs.com tidak bisa di loading gambar/gif
[https://drive.google.com/file/d/1REVa0XL9LMSvRPgaXC_LAbxlH2IUhaDX/view?usp=sharing](url)

Device :
Windows 10
Browser Google Chrome

**Comment by SlashyID** [comment]
Hosts sudah kami perbaiki ya..
Silahkan update hosts file anda.

Kalau sudah bisa atau masih ada masalah, silahkan reply message ini
