### ISSUE TITLE
[REQ] website nya microsoft

### ISSUE THREAD

**Issue by kenewjr** [bebasid/bebasid#533]
go.microsoft.com
aka.ms
download.visualstudio.microsoft.com
download.microsoft.com
download.visualstudio.com
dl.xamarin.com
xamarin-downloads.azureedge.net
marketplace.visualstudio.com
visualstudio.microsoft.com

**Comment by nxzlem** [comment]
ini kasus nya ada masalah apa dengan situs microsoft? kami menambahkan situs-situs yang terblokir oleh trustpositif

**Comment by kenewjr** [comment]
internet yg saya pake skrg kalo mau download / update aplikasi dari semua microsoft harus make vpn dulu baru bisa jalan progress nya

**Comment by nxzlem** [comment]
> internet yg saya pake skrg kalo mau download / update aplikasi dari semua microsoft harus make vpn dulu baru bisa jalan progress nya
isp anda apa? kalo indihome memang karena ada throttle nya.

**Comment by kenewjr** [comment]
make isp lokal sih ini

**Comment by nxzlem** [comment]
> 



> make isp lokal sih ini

boleh kah anda kasih tau nama isp lokal tersebut?

**Comment by kenewjr** [comment]
> 







> > make isp lokal sih ini
> 
> boleh kah anda kasih tau nama isp lokal tersebut? cek nya ada di [sini](https://browserleaks.com/dns), screenshot lalu kirimkan kesini

![browserleaks-dns-2023_02_21_23_58_03](https://user-images.githubusercontent.com/32585941/220411242-3eb4ce80-9b80-4b39-b959-aaf9427f62bc.png)

**Comment by nxzlem** [comment]
> > 
> 
> > > make isp lokal sih ini
> > 
> > 
> > boleh kah anda kasih tau nama isp lokal tersebut? cek nya ada di [sini](https://browserleaks.com/dns), screenshot lalu kirimkan kesini
> 
> ![browserleaks-dns-2023_02_21_23_58_03](https://user-images.githubusercontent.com/32585941/220411242-3eb4ce80-9b80-4b39-b959-aaf9427f62bc.png)

silakan menggunakan doh bebasid dari konfigurasi bawaan windows network atau memakai tiga pihak aplikasi dnscrypt-windows

**Comment by kenewjr** [comment]
DOH udh nyoba cuma tetep aja masih gk bisa download/update, make aplikasi jga udh coba tetep aja gk bisa make resolver otomatis

**Comment by SlashyID** [comment]
Kemungkinan ada masalah routing antara ISP anda dan Microsoft nya

Kalau kaya gini, mungkin bisa kontak CS biar cepet dibenerin

**Comment by nxzlem** [comment]
Jika masih ada masalah dengan website microsoft untuk anda, silakan menghubungi kontan CS nya terlebih dahulu.
