### ISSUE TITLE
[REQ] ci-en.dlsite.com

### ISSUE THREAD

**Issue by HitsuKo39** [bebasid/bebasid#534]

**Comment by SlashyID** [comment]
Hosts sudah diperbaiki ya, silahkan update hosts anda

**Comment by HitsuKo39** [comment]
blm mau kebuka min
![image](https://user-images.githubusercontent.com/126174860/222907848-24727b9e-6a05-45b6-92df-46435ce91167.png)

**Comment by HitsuKo39** [comment]
@SlashyID sorry ping min, kurang tau cara ubah issue jadi open lagi

**Comment by nxzlem** [comment]
> @SlashyID sorry ping min, kurang tau cara ubah issue jadi open lagi

pake ISP apa?

**Comment by HitsuKo39** [comment]
oxygen saya min

**Comment by nxzlem** [comment]
> oxygen saya min

Silakan gunakan metode doh, kami sudah mengadakan doh bebasdns untuk yang para pengganti hosts.

**Comment by SlashyID** [comment]
Jika masih ada masalah, jangan ragu untuk membuka issue dan bilang ke kami lagi
