### ISSUE TITLE
[REQ & BUG] cdn.sportcast.life & [BUG] (thumbnail xvideos.com)

### ISSUE THREAD

**Issue by muzzin-ctrl** [bebasid/bebasid#536]
sama bug xvideo yah diperbaharui lagi,  soalnya thumbnail gak muncul ...

**Comment by muzzin-ctrl** [comment]
> > sama bug xvideo yah diperbaharui lagi, soalnya thumbnail gak muncul ...
> 
> maaf, nama subdomain nya apa untuk thumbnail yang tidak muncul di xvideos?

xvideo.com

**Comment by SlashyID** [comment]
Boleh klik Inspect Element dan klik bagian Console?

**Comment by OfficialNandaP** [comment]
Nah, iya di reddit juga seperti itu. domain nya ini:

> https://i.redd.it/

**Comment by nxzlem** [comment]
Untuk sementara, silahkan pake [BebasDNS](https://github.com/bebasid/bebasdns)/[BebasIT](https://github.com/bebasid/bebasit) jika hosts nya tidak bisa & belum dibenarkan. Jika ISP anda menggunakan DPI, silahkan download [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI) dan langkah-langkahnya ada [disini](https://github.com/bebasid/bebasdns/blob/main/dev/readme/tutoraltport.md#goodbyedpi).
