### ISSUE TITLE
[BUG] NSFW website Connection Failed

### ISSUE THREAD

**Issue by barxanz** [bebasid/bebasid#538]
coba beberapa website NSFW tidak ada yang bisa dibuka muncul Secure Connection Failed

**Screenshot**
![image](https://user-images.githubusercontent.com/130688826/231827965-8d7bf6f6-342a-4470-9c19-cb5c97e96b3b.png)

**Device**
 - OS: Windows 11
 - Browser Firefox

**Comment by SlashyID** [comment]
Hampir semua ISP disini menggunakan DPI jadi untuk membypass DPI dari provider, silahkan gunakan [BebasIT](https://github.com/bebasid/bebasit) untuk membypass DPI nya
