### ISSUE TITLE
[BUG] gelbooru.com thumbnail tidak muncul

### ISSUE THREAD

**Issue by bobibesar** [bebasid/bebasid#539]
**Deskripsi mengenai bug**
thumbnail gelbooru tidak muncul 

**Screenshot**
![Capture](https://user-images.githubusercontent.com/111652927/231997301-446fe3bf-b431-4620-bef9-b9981ee9caf9.JPG)
![site unrech](https://user-images.githubusercontent.com/111652927/231997600-7b43e4f3-89d7-4898-adb3-e08aa66d584a.JPG)

**Device**
 - OS: windows 10
 - Browser: chrome

**Comment by SlashyID** [comment]
Sebentar saya cek dulu ya

**Comment by SlashyID** [comment]
![image](https://user-images.githubusercontent.com/115700386/232111828-9299d508-11d5-4587-b912-69b139722af0.png)
Sepertinya normal2 saja

Ini pake ISP apa?

**Comment by bobibesar** [comment]
firstmedia

**Comment by SlashyID** [comment]
Firstmedia menggunakan DPI
Silahkan gunakan tool tambahan seperti GoodbyeDPI atau PowerTunnel untuk membypass DPI nya
