### ISSUE TITLE
[BUG] www.sex.com

### ISSUE THREAD

**Issue by trusta77** [bebasid/bebasid#54]
Media won't load (image, gif, video)
![image](https://user-images.githubusercontent.com/40566453/78698848-276a7980-792d-11ea-9c2d-2255f026fded.png)

**Comment by nxzlem** [comment]
Sudah di Tambahkan "cdn.sex.com" IP ke hosts.
Terima Kasih melaporkan bug utk Anda.

**Comment by nxzlem** [comment]
Abang sehrsnya reinstall BebasID dulu ya. 
Terima Kasih.
-NXzLEM
