### ISSUE TITLE
[BUG] zenra.net

### ISSUE THREAD

**Issue by muzzin-ctrl** [bebasid/bebasid#540]
**Deskripsi mengenai bug**
gak bisa dibuka.

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.

**Device**
 - OS: [cth. Windows 10]
 - Browser [cth. Chrome, Firefox]

**Comment by SlashyID** [comment]
Sebentar saya cek dulu

**Comment by SlashyID** [comment]
Silahkan update host anda. Mohon maaf jika sudah membuat anda lama menunggu
