### ISSUE TITLE
[REQ] Neosubs.net

### ISSUE THREAD

**Issue by muzzin-ctrl** [bebasid/bebasid#546]

**Comment by SlashyID** [comment]
Ok sip sebentar ya saya add 🙏

**Comment by SlashyID** [comment]
Mohon maaf, sepertinya Github nya sedang ada masalah jadi gak bisa diupdate hostsnya
![image](https://github.com/bebasid/bebasid/assets/115700386/df8800ae-85d5-4bbf-9d9f-921a604ae881)

Jadi untuk solusinya, bisa tambahkan ini di file hosts anda:

```
# [neosubs.net]
# IPv4
2606:4700:3032::6815:5871 neosubs.net
2606:4700:3036::ac43:b124 www.neosubs.net
# IPv6
172.67.177.36 neosubs.net
104.21.88.113 www.neosubs.net
```
