### ISSUE TITLE
[BUG] hentai-image.com

### ISSUE THREAD

**Issue by muzzin-ctrl** [bebasid/bebasid#547]
**Deskripsi mengenai bug**
gak bisa dibuka

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.

**Device**
 - OS: [cth. Windows 10]
 - Browser [cth. Chrome, Firefox]

**Comment by SlashyID** [comment]
Sebentar ya saya cek 🙏

**Comment by SlashyID** [comment]
Sudah diperbaiki ya 🙏 

Silahkan update host anda
