### ISSUE TITLE
[REQ] degoo.com

### ISSUE THREAD

**Issue by Kampring** [bebasid/bebasid#548]

**Comment by SlashyID** [comment]
Sudah diupdate ya 🙏 

Silahkan update file hosts anda

**Comment by Kampring** [comment]
sudah update, restart pc, di cek di host sudah ada degoo nya
![image](https://github.com/bebasid/bebasid/assets/10830722/c39f2ad1-a4dd-476c-a0d2-b4b5a5869da6)

kalau pakai proxy bisa
![image](https://github.com/bebasid/bebasid/assets/10830722/fef49264-d87c-4d5a-907a-e6293aa0865e)
