### ISSUE TITLE
[BUG] iwara.tv

### ISSUE THREAD

**Issue by AgusHerculeng** [bebasid/bebasid#558]
Gambar thumbnailnya tidak muncul

**Comment by SlashyID** [comment]
Selamat pagi,

Terimakasih sudah membuat issue disini

Silahkan tunggu. Kita akan investigasi masalahnya 🙏

**Comment by SlashyID** [comment]
Selamat malam.

Sepertinya Iwara.tv setelah kami cek, tidak mendukung metode host file dikarenakan IP mereka dinamis.

Untuk mengakses iwara.tv, silahkan hapus hosts iwara.tv dari host file anda dan gunakan DNS dari kami 🙏

https://github.com/bebasid/bebasdns

Kami mohon maaf atas tidak kenyamanan anda dan terimakasih sudah membuat issue
