### ISSUE TITLE
[BUG] pornzog.com

### ISSUE THREAD

**Issue by muzzin-ctrl** [bebasid/bebasid#559]
**Deskripsi mengenai bug**
Deskripsi yang jelas dan ringkas tentang apa yang terjadi.

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.

**Device**
 - OS: [cth. Windows 10]
 - Browser [cth. Chrome, Firefox]

**Comment by SlashyID** [comment]
Selamat pagi,

Terimakasih sudah membuat issue disini

Silahkan tunggu

**Comment by SlashyID** [comment]
Host sudah dibetulkan.
Silahkan update host anda 🙏
