### ISSUE TITLE
[REQ] anonfiles.com

### ISSUE THREAD

**Issue by Nosoba** [bebasid/bebasid#560]

**Comment by nxzlem** [comment]
halo kak, anonfiles.com sudah ditambahkan dari kemarin.

https://github.com/bebasid/bebasid/commit/657f0324db1a2d457541c90074f5fe68a87f0ee1
https://github.com/bebasid/bebasid/commit/f11d81b0f224f455c326823eed65eab169556a41

mohon diperiksa lagi, dan update hosts anda ya. terimakasih.

jika masih belum ada akses atau isp nya memakai DPI+DNSN, silahkan gunakan [bebasdns / bebasid](https://github.com/bebasid/bebasdns) dns untuk melewati dari 2 tipe jenis pemblokirannya.

**Comment by nxzlem** [comment]
duplicate issue similar to the discord:
![QvxbUzcas5](https://github.com/bebasid/bebasid/assets/30078972/ad7d508e-1619-4d2a-9a41-89297484c558)
https://discord.com/channels/630415907021389825/630416441996476436/1122383904985321582
