### ISSUE TITLE
[BUG] reddit.com & vimeo.com

### ISSUE THREAD

**Issue by bilalbayasut** [bebasid/bebasid#561]
**Deskripsi mengenai bug**
tidak bisa mengakses reddit.com dan vimeo.com

**Screenshot**
<img width="820" alt="image" src="https://github.com/bebasid/bebasid/assets/3622158/a53128ae-d8e6-401c-ae0f-acbdc7db9a8e">

**Device**
 - OS: [Macos Ventura]
 - Browser [chrome]

**Comment by ryukora** [comment]
> **Deskripsi mengenai bug** tidak bisa mengakses reddit.com dan vimeo.com
> 
> **Screenshot** <img alt="image" width="820" src="https://user-images.githubusercontent.com/3622158/250118508-a53128ae-d8e6-401c-ae0f-acbdc7db9a8e.png">
> 
> **Device**
> 
> * OS: [Macos Ventura]
> * Browser [chrome]

jika ada tulisan sambungan telah reset atau isp nya memakai DPI+DNSN, silahkan gunakan [bebasdns / bebasid](https://github.com/bebasid/bebasdns) dns untuk melewati dari 2 tipe jenis pemblokirannya.

**Comment by SlashyID** [comment]
Connection Reset merupakan salah satu tanda provider anda menggunakan DPI jadi silahkan gunakan tool anti DPI untuk membypass DPI selagi memakai BebasID

- [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI/releases)
- [PowerTunnel](https://github.com/krlvm/PowerTunnel/releases)
- [GreenTunnel](https://github.com/SadeghHayeri/GreenTunnel/releases)

Kalau boleh tau, anda memakai provider apa ya?

**Comment by bilalbayasut** [comment]
@SlashyID terima kasih respon nya, indihome, biznet kadang broadband gsm juga
