### ISSUE TITLE
[BUG]Instalasi di Linux error

### ISSUE THREAD

**Issue by Kampring** [bebasid/bebasid#563]
Instalasi di linux Mint error
![image](https://github.com/bebasid/bebasid/assets/10830722/4a18ecfc-c89a-48dc-a850-37d2a6f9ef09)

**Device**
 - OS: Linux Mint

**Comment by ryukora** [comment]
Untuk sementara, silahkan pake [BebasDNS](https://github.com/bebasid/bebasdns)/[BebasIT](https://github.com/bebasid/bebasit) jika hosts nya tidak bisa & belum dibenarkan. Jika ISP anda menggunakan DPI, silahkan download [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI) dan langkah-langkahnya ada [disini](https://github.com/bebasid/bebasdns/blob/main/dev/readme/tutoraltport.md#goodbyedpi).
