### ISSUE TITLE
[FAQ] Setting Mikrotik

### ISSUE THREAD

**Issue by achmatch** [bebasid/bebasid#564]
Apakah jika menggunakan cara di [link ini](https://github.com/bebasid/bebasit/blob/master/docs/mikrotik-tutorial.md) ga perlu menambahkan DOH / DOT di bagian DNS mikrotik?

**Comment by ryukora** [comment]
> Apakah jika menggunakan cara di [link ini](https://github.com/bebasid/bebasit/blob/master/docs/mikrotik-tutorial.md) ga perlu menambahkan DOH / DOT di bagian DNS mikrotik?

Halo,
Script untuk DNS mikrotik nya berfungsi untuk menambahkan firewall nat lewat IP.
Itu hanya menggunakan IP DNS dan port kustom. Selain itu, ada script juga untuk cara melewati DPI nya.
Jika MikroTik anda mendukung DoH dan DoT, silahkan gunakan saja.

**Comment by achmatch** [comment]
Terima kasih, sangat membantu saya....

**Comment by SlashyID** [comment]
Sayangnya untuk DoH sampai sekarang (Router OS v7) masih ngebug

Jadi disarankan kalau provider anda tidak mengikuti aturan DNS Nasional, pake plain aja atau bisa buat server proxy DoH sendiri dirumah menggunakan AdGuard Home dan semacamnya.
