### ISSUE TITLE
[BUG] kemono.party

### ISSUE THREAD

**Issue by mangkoran** [bebasid/bebasid#565]
**Deskripsi mengenai bug**
Beberapa subdomain bermasalah. Dalam isu ini adalah subdomain cdn (c3.kemono etc)

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.

**Device**
 - OS: Android 13
 - Browser: Chrome

**Comment by SlashyID** [comment]
Selamat Pagi,

Untuk situs kemono, sudah kami betulkan 🙏 

Apakah ada CDN lain yang kena?

**Comment by mangkoran** [comment]
> Untuk situs kemono, sudah kami betulkan 🙏
Saya dapat mengkonfirmasi bahwa commit https://github.com/bebasid/bebasid/commit/895758e1174933cd1b3c5354e43ed723891eddbe telah menyelesaikan isu diatas.

> Apakah ada CDN lain yang kena?
Untuk saat ini hanya CDN diatas yang saya tahu.

Terimakasih banyak atas bantuannya!
