### ISSUE TITLE
[BUG] DNS Data Provider Unavailable

### ISSUE THREAD

**Issue by arvinyustin99** [bebasid/bebasid#566]
**Deskripsi mengenai bug**
Sepertinya url utk data DNS provider mati. Setelah cek dari script (gambar 1) dan log-nya, kembaliannya error HTML. Saya mencoba memakai url dari repo **bebasid**, yang value-nya **https://bebasid.herokuapp.com/?get=dns&dns=gt&n=$i** tetapi hasilnya sama, _Application Error_

**Screenshot**
![gambar 1](https://github.com/bebasid/bebasid/assets/44569953/a82138f3-6d04-4cb6-9ae0-51212997462d)
![gambar 2](https://github.com/bebasid/bebasid/assets/44569953/75c9ffb2-7ab2-47d7-985f-d50a92407f02)

**Device**
 - OS: MacOS Ventura 13.6, M1 16GB
 - Browser: Chrome 117.0.5938.92

**Comment by ryukora** [comment]
> **Deskripsi mengenai bug** Sepertinya url utk data DNS provider mati. Setelah cek dari script (gambar 1) dan log-nya, kembaliannya error HTML. Saya mencoba memakai url dari repo **bebasid**, yang value-nya **https://bebasid.herokuapp.com/?get=dns&dns=gt&n=$i** tetapi hasilnya sama, _Application Error_
> 
> **Screenshot** ![gambar 1](https://user-images.githubusercontent.com/44569953/271762153-a82138f3-6d04-4cb6-9ae0-51212997462d.png) ![gambar 2](https://user-images.githubusercontent.com/44569953/271762074-75c9ffb2-7ab2-47d7-985f-d50a92407f02.png)
> 
> **Device**
> 
> * OS: MacOS Ventura 13.6, M1 16GB
> * Browser: Chrome 117.0.5938.92

Coba pake bebasdns, gan...

**Comment by ryukora** [comment]
> **Deskripsi mengenai bug** Sepertinya url utk data DNS provider mati. Setelah cek dari script (gambar 1) dan log-nya, kembaliannya error HTML. Saya mencoba memakai url dari repo **bebasid**, yang value-nya **https://bebasid.herokuapp.com/?get=dns&dns=gt&n=$i** tetapi hasilnya sama, _Application Error_
> 
> **Screenshot** ![gambar 1](https://private-user-images.githubusercontent.com/44569953/271762153-a82138f3-6d04-4cb6-9ae0-51212997462d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjAwMTIsIm5iZiI6MTcwNjA1OTcxMiwicGF0aCI6Ii80NDU2OTk1My8yNzE3NjIxNTMtYTgyMTM4ZjMtNmQwNC00Y2I2LTlhZTAtNTEyMTI5OTc0NjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAxMjgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMmE2Y2QyZTg1NzRkODkwY2ZhOWViN2QzOGY4NGNlYWEyZmZhOWRiNWFiMDY0YzcyNzIzZmQ0OWNjOWM3ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zVs6oRwE3KmFsP5WfliydPMJHnfjLpVEAt_ZzRrqxBY) ![gambar 2](https://private-user-images.githubusercontent.com/44569953/271762074-75c9ffb2-7ab2-47d7-985f-d50a92407f02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjAwMTIsIm5iZiI6MTcwNjA1OTcxMiwicGF0aCI6Ii80NDU2OTk1My8yNzE3NjIwNzQtNzVjOWZmYjItN2FiMi00N2Q3LTk4NWYtZDUwYTkyNDA3ZjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAxMjgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMDVjMzhlNTI4ZDdlMWY4ZjkzM2VjZmYwMzBhOGI1ZTBjNzhjZDA4NDFjMDk0NGQ5Zjg4N2U4NWVlNjEwNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b4qJ7cEDfqaQvOUz_yroI2CmAjkKWfpsvUxgWmjrdkw)
> 
> **Device**
> 
> * OS: MacOS Ventura 13.6, M1 16GB
> * Browser: Chrome 117.0.5938.92

Utk sementara, silahkan gunakan bebasdns + powertunnel dulu. Jika ada hosts terpasang silahkan dicabut saja.
