### ISSUE TITLE
[BUG] bypass Netflix pake Green Tunnel tetap tidak bisa tapi situs lain bisa  

### ISSUE THREAD

**Issue by muh-alif** [bebasid/bebasid#57]
**Deskripsi mengenai bug**
Sudah memasang Homebrew, NodeJS + NPM, Tmux, dan Green Tunnel secara manual. Karena selalu ga bisa kalo ikutin cara dari sini https://github.com/bebasid/bebasid/blob/master/dev/readme/NETFLIX.md

**Screenshot**
<img width="1440" alt="Screen Shot 2020-04-09 at 19 11 19" src="https://user-images.githubusercontent.com/22170538/78893730-007b8700-7a96-11ea-9550-604dfbf17c34.png">

**Device**
 - OS: MacOS Catalina
 - Browser Chrome

**Comment by indrawp** [comment]
Sementara bisa gunakan openvpn, buat akun & download config OpenVPN Indonesia di tcpvpn.com
