### ISSUE TITLE
[BUG] preview.redd.it

### ISSUE THREAD

**Issue by futag** [bebasid/bebasid#575]
**Deskripsi mengenai bug**
Tdak dapat dikakses, meski sudah mengunakan warp vpn

**Device**
 - OS: Windows 11
 - Browser Edge

**Comment by ryukora** [comment]
Halo,
request anda sudah ditambahkan di commit https://github.com/bebasid/bebasid/commit/4d9cfbabaa5fce00e614ed82356ec99fb76033ff

Silahkan di update hosts anda, sekian terimakasih.
