### ISSUE TITLE
[REQ] proxy.hypixel.net

### ISSUE THREAD

**Issue by rafroad** [bebasid/bebasid#576]
sebagai tambahan karena hypixel.net jika dimasukan di mc client menghasilkan timeout dan proxy.hypixel.net diblokir 
![image](https://github.com/bebasid/bebasid/assets/56687086/ca10141d-4d91-4c4e-abff-3889e7c1978a)

![image](https://github.com/bebasid/bebasid/assets/56687086/732adb5a-6903-4127-a20f-911ad0187baa)

**Comment by RacBallonMC** [comment]
Coba `mc.hypixel.io`

**Comment by rafroad** [comment]
bisa dan tambahan baru dicoba tadi setting dns diubah juga bisa digabungkan dengan bebasid

**Comment by ryukora** [comment]
> bisa dan tambahan baru dicoba tadi setting dns diubah juga bisa digabungkan dengan bebasid

jangan dicampur dengan hosts bebasid.... ketabrak jadinya
pake dengan khusus saja jika ada keperluan...
