### ISSUE TITLE
[BUG] https://i.stack.imgur.com

### ISSUE THREAD

**Issue by dickys11** [bebasid/bebasid#58]
**Deskripsi mengenai bug**
Buka i.stack.imgur.com masih terkendala internet baik menggunakan telkomsel

**Screenshot**
![image](https://user-images.githubusercontent.com/44948974/78899912-49d0d400-7aa0-11ea-8676-3475dcf52e87.png)

**Device**
 - OS: Windows 10
 - Browser: Microsoft Edge Beta

**Comment by indrawp** [comment]
Maaf sebelumnya terlewat, bisa dicoba lagi? @dickys11

**Comment by dickys11** [comment]
> Maaf sebelumnya terlewat, bisa dicoba lagi? @dickys11

sudah bisa, thanks
