### ISSUE TITLE
[BUG] nyaa.si

### ISSUE THREAD

**Issue by raeka21** [bebasid/bebasid#580]
Entah ini bug atau apa, tapi nyaa.si selalu "The service you've requested couldn't be identified" dari DDos-Guard

saya sudah matikan dns cloudflare yang saya pakai, juga udah nyobain bebasdns unfiltered, dan udah update host saya, di test juga di incognito dan udah hard reload. Sejauh ini yang bisa masuk cuman saat pakai Psiphon.

**Device**
 - OS: Windows 10
 - Browser Chrome

**Comment by Username778** [comment]
Ganti jadi 186.2.163.20
langsung flushdns, maka bisa lagi buka nyaa.si

**Comment by raeka21** [comment]
Fixed! Thanks!

**Comment by ryukora** [comment]
https://github.com/bebasid/bebasid/commit/c3756efc46f983850d10ee0e978bec83a01a536c#commitcomment-138541737
Silahkan dibaca ya, kami memberitahukan anda untuk hosts update nya
