### ISSUE TITLE
Rekomendasikan Spoof-DPI daripada PowerTunnel

### ISSUE THREAD

**Issue by ferroson** [bebasid/bebasid#583]
**Deskripsi mengenai bug**
PowerTunnel menggunakan banyak resource, karena berbasis Java. Meskipun aplikasi Java dapat berjalan secara reliabel di berbagai OS, tetapi penggunaan resource yang banyak dapat menurunkan motivasi penggunaan aplikasi: Mengapa perlu mengorbankan penggunaan RAM 150MB untuk sekadar membuka Reddit? Itu tidak jauh berbeda dengan penggunaan VPN

GreenTunnel lebih baik dalam penggunaan resource. Namun, tidak cukup reliabel. Aku menjumpai masalah aplikasinya tidak dapat berjalan setelah update OS (Ada masalah yang terkait dengan npm). Tidak hanya berdampak pada Linux, melainkan juga Windows. Dapat dikonfirmasi melalui laporan bug berikut: https://github.com/SadeghHayeri/GreenTunnel/issues/163

SpoofDPI lebih baik daripada PowerTunnel dalam penggunaan resource, instalasi aplikasinya juga cenderung mudah, dengan diberikannya instruksi dalam laman Git. Sejauh ini juga belum ada laporan not working error, setidaknya pada perangkat x86 atau x86-64, sehingga dapat menjadi opsi yang lebih baik. Konfigurasi dalam baris perintah pun relatif mudah, dengan adanya parameter. Misalkan jika ingin mengatur address dan port: $ spoof-dpi -addr xxxx.x.x.x -port xxxx

**Screenshot**
![Screenshot from 2024-02-08 09-33-13](https://github.com/bebasid/bebasid/assets/108534456/79f94c73-4c70-4815-b101-931169ddff32)

**Device**
 - OS: Linux

**Comment by icaksh** [comment]
cek commit terakhir, sudah saya tambahkan spoofdpi di bebasit

jika merasa cukup bisa di close issue ini, jika tidak bisa tambahkan apa yg kurang

**Comment by gvoze32** [comment]
@ferroson Issue addressed at commit https://github.com/bebasid/bebasid/commit/5a50afaecb4947126b06c803af3acc6884f4e7f1 please kindly check. If you feel it is good you can close this issue, if not you can add what is missing.
