### ISSUE TITLE
[REQ] everia.club

### ISSUE THREAD

**Issue by 0Ha16wA5** [bebasid/bebasid#586]
website model

**Comment by ryukora** [comment]
Pake Provider apa

**Comment by ryukora** [comment]
Halo,
Host sudah kami update, bisa lihat di
https://github.com/bebasid/bebasid/commit/ef56f64feb0a4432ebc694d29410e05c91eb3f2f
Silahkan update host file anda dan clear cache browser 
Jika masih mengalami masalah silahkan re-open & laporkan penyebabnya, terimakasih
