### ISSUE TITLE
[BUG] sankakucomplex.com

### ISSUE THREAD

**Issue by AgusHerculeng** [bebasid/bebasid#589]
idol.sankakucomplex.com sama chan.sankakucomplex.com cuman bisa dibuka pakek vpn di provider XL

**Comment by ryukora** [comment]
Untuk sementara, silahkan pake [BebasDNS](https://github.com/bebasid/bebasdns)/[BebasIT](https://github.com/bebasid/bebasit) jika hosts nya tidak bisa & belum dibenarkan. Jika ISP anda menggunakan DPI, silahkan download [PowerTunnel](https://github.com/krlvm/PowerTunnel), [GreenTunnel](https://github.com/SadeghHayeri/GreenTunnel) atau [Geneva](https://github.com/Kkevsterrr/geneva) dan langkah-langkahnya ada [disini](https://github.com/bebasid/bebasdns/blob/main/dev/readme/tutoraltport.md).
