### ISSUE TITLE
[BUG] animepahe.ru

### ISSUE THREAD

**Issue by Username778** [bebasid/bebasid#591]
Gambar preview videonya tidak nampak untuk ISP Indihome meski sudah pakai host dari sini.
![TYUI](https://github.com/bebasid/bebasid/assets/32461041/155177d6-43f0-4c8b-8f40-de8ceaea1fe8)

**Comment by merdekaid** [comment]
Halo, kami sudah memperbaiki host file kami. Silahkan dicek 

Jika masih ada issue, silahkan buka issue ini kembali. Terimakasih
