### ISSUE TITLE
[REQ] dedomil.net

### ISSUE THREAD

**Issue by ModiFlasher** [bebasid/bebasid#598]
### Domain

dedomil.net

### Alasan

Hanya minta unlock situs game java

### ISP Apa yang anda gunakan

Live On (XL)

### Sistem Operasi (OS)

Windows 11, Android 14

### Validasi

- [X] Saya telah melihat dan memastikan bahwa domain yang saya masukkan tidak ada di dalam daftar domainlist

### Kode Etik

- [X] Saya menyetujui untuk mengikuti Kode Etik proyek ini

**Comment by ryukora** [comment]
Tolong di kabari, jika sudah berfungsi atau tidak.
jika masih belum bisa akses, silahkan menggunakan [bebasdns DoH/DoT](https://github.com/bebasid/bebasdns/) atau VPN (cth: WARP 1.1.1.1).
