### ISSUE TITLE
[BUG] javhub.net

### ISSUE THREAD

**Issue by darkmoonside** [bebasid/bebasid#60]
**Deskripsi mengenai bug**
gambar tidak muncul, video tidak bisa muncul.

**Device**
 - OS: Windows 10
 - Browser : Chrome, Firefox

**Comment by gvoze32** [comment]
http://74.openhub.tv:443
http://kaigaiad.hs.llnwd.net:443
http://74.anyhentai.com:443
http://74.javhucdn.com:443

Sementara gambar akan diupdate, untuk video masih perlu riset lebih lanjut
