### ISSUE TITLE
[BUG] shell method install on macos failed

### ISSUE THREAD

**Issue by bhaskoro-muthohar** [bebasid/bebasid#603]
### Deskripsi mengenai bug

Gagal install bebasid.sh di macos

### Screenshot

```shell
sh Bebasid_v1.1_2022.10.sh
: command not found0.sh: line 2:
'ebasid_v1.1_2022.10.sh: line 3: syntax error near unexpected token `{
'ebasid_v1.1_2022.10.sh: line 3: `bebasid_banner(){
```

```shell
sudo Bebasid_v1.1_2022.10.sh
sudo: Bebasid_v1.1_2022.10.sh: command not found
```

### Sistem Operasi (OS)

MacOS 13.4

### Browser

Chromium

**Comment by icaksh** [comment]
use
```
bash bebasid.sh
```

not 
```
sh bebasid.sh
```

![Screenshot 2024-06-06 at 02 20 19](https://github.com/bebasid/bebasid/assets/19889081/d8176dec-1e2d-4870-8cad-0f2e4b8cd9eb)


![Screenshot 2024-06-06 at 02 21 20](https://github.com/bebasid/bebasid/assets/19889081/c7e57095-4cce-48b6-a7da-b09e09b117aa)
