### ISSUE TITLE
[REQ] termux.net

### ISSUE THREAD

**Issue by ModiFlasher** [bebasid/bebasid#604]
### Domain

termux.net

### Alasan

Terblokir

### ISP Apa yang anda gunakan

Live On (XL)

### Sistem Operasi (OS)

Windows 11, Android 14

### Validasi

- [X] Saya telah melihat dan memastikan bahwa domain yang saya masukkan tidak ada di dalam daftar domainlist

### Kode Etik

- [X] Saya menyetujui untuk mengikuti Kode Etik proyek ini

**Comment by gvoze32** [comment]
Bisa dijelaskan ini situs apa?

**Comment by ryukora** [comment]
![7fFfTvBf62](https://github.com/bebasid/bebasid/assets/30078972/42899d69-06fe-4f88-aec4-7809a6e96328)

**Comment by ryukora** [comment]
Tolong di kabari, jika sudah berfungsi atau tidak.
jika masih belum bisa akses, silahkan menggunakan [bebasdns DoH/DoT](https://github.com/bebasid/bebasdns/) atau VPN (cth: WARP 1.1.1.1).
