### ISSUE TITLE
[BUG] hentainexus.com

### ISSUE THREAD

**Issue by 0Ha16wA5** [bebasid/bebasid#606]
### Domain

hentainexus.com

### Deskripsi mengenai bug

Web tidak dapat diakses, hanya bisa lewat VPN

### Sistem Operasi (OS)

Windows 11

### Browser

Firefox

**Comment by ryukora** [comment]
Bisa sertakan screenshot dulu?

**Comment by ryukora** [comment]
> ### Deskripsi mengenai bug
> Web tidak dapat diakses, hanya bisa lewat VPN
> 
> ### Screenshot
> _No response_
> 
> ### Sistem Operasi (OS)
> Windows 11
> 
> ### Browser
> Firefox

Pake ISP apa?

**Comment by gvoze32** [comment]
Resolved here
https://github.com/bebasid/bebasid/issues/610

**Comment by ryukora** [comment]
Tolong di kabari, jika sudah berfungsi atau tidak.
jika masih belum bisa akses, silahkan menggunakan [bebasdns DoH/DoT](https://github.com/bebasid/bebasdns/) atau VPN (cth: WARP 1.1.1.1).
