### ISSUE TITLE
[BUG] myreadingmanga.info

### ISSUE THREAD

**Issue by nattadasu** [bebasid/bebasid#62]
**Deskripsi mengenai bug**
Gambar gagal memuat pada saat membuka kiriman (*posting*), mungkin CDN MRM masih terblokir. Sudah dicoba dari 3 gawai dengan browser yang berbeda dan os berbeda.
Koneksi Bebasid di iOS menggunakan Personal Hotspot dari PC yang menggunakan Windows 10. [Sample](https://myreadingmanga.info/harusono-syou-sasaki-miyano-eng/)

**Screenshot**
![iOS Safari](https://cdn.discordapp.com/attachments/589128995501637661/698251224755208212/image0.png)
![iOS Edge](https://cdn.discordapp.com/attachments/589128995501637661/698250846521262090/image0.png)
![Windows Edge](https://cdn.discordapp.com/attachments/589128995501637661/698248000388071484/unknown.png)

**Device**
 - OS: iOS 12.4.6, Windows 10 Home (1903), Ubuntu Studio Eoan Ermine.
 - Browser: Apple Safari, Microsoft Edge Chromium, Google Chrome.

**Comment by indrawp** [comment]
Silahkan coba update hosts nya @nattadasu

**Comment by nattadasu** [comment]
Ok sip, sudah works 👀 👌
