### ISSUE TITLE
[BUG] hypixel.net

### ISSUE THREAD

**Issue by towermom9** [bebasid/bebasid#620]
### Domain atau lain

mc.hypixel.net

### Alasan / Deskripsi mengenai bug

Tidak terbuka

### ISP Apa yang anda gunakan

My Republic

### Sistem Operasi (OS)

Windows 11

### Browser

Chrome

**Comment by ryukora** [comment]
hypixel tidak bisa diakses walaupun pake hosts, ISP yang anda pakai kena DPI

**Comment by merdekaid** [comment]
Baik, akan kami cek di host kami, silahkan tunggu 🙏

**Comment by merdekaid** [comment]
Silahkan update host BebasID anda dan coba lagi 🙏
