### ISSUE TITLE
[BUG] DLsite.com

### ISSUE THREAD

**Issue by 0Ha16wA5** [bebasid/bebasid#623]
### Domain atau lain

DLsite.com

### Alasan / Deskripsi mengenai bug

tidak bisa diakses (potential security issue, redirect ke ipo)

### ISP Apa yang anda gunakan

IndiHome

### Sistem Operasi (OS)

Windows 11

### Browser

Chrome

**Comment by ryukora** [comment]
Tolong di kabari, jika sudah berfungsi atau tidak.
jika masih belum bisa akses, silahkan menggunakan [bebasdns DoH/DoT](https://github.com/bebasid/bebasdns/) atau VPN (cth: WARP 1.1.1.1).
