### ISSUE TITLE
[BUG] nhentai.net

### ISSUE THREAD

**Issue by 0Ha16wA5** [bebasid/bebasid#624]
### Domain atau lain

nhentai.net

### Alasan / Deskripsi mengenai bug

gambar tidak selalu keluar

### Screenshot

![20240816_02 50_34 324_%pn_Ys95C6RkIa](https://github.com/user-attachments/assets/9c5bd545-40df-4ce2-a036-d32bff062dad)

### ISP Apa yang anda gunakan

Indihome

### Sistem Operasi (OS)

Windows 11

### Browser

Chrome

**Comment by ryukora** [comment]
Tolong di kabari, jika sudah berfungsi atau tidak.
jika masih belum bisa akses, silahkan menggunakan [bebasdns DoH/DoT](https://github.com/bebasid/bebasdns/) atau VPN (cth: WARP 1.1.1.1).
