### ISSUE TITLE
.exe application cannot open after opening up once

### ISSUE THREAD

**Issue by dabeeduu** [bebasid/bebasid#625]
The .exe application cannot open after installing the profile.
What happened :
1. Downloaded the .exe files
2. Open the .exe files
3. Installed the profile
4. Updated the profile
5. the .exe application suddenly closed
6. Cannot open it again

I have tried : 
1. Redownloading the .exe
2. Restarting the pc

**Comment by dabeeduu** [comment]
After Del

**Comment by galpt** [comment]
If you're using hosts file, it's better to use this since this program is the latest that we've developed.
https://github.com/bebasid/bebasid?tab=readme-ov-file#bebashosts-portable
