### ISSUE TITLE
doesn't work with hostsman

### ISSUE THREAD

**Issue by WNnitro** [bebasid/bebasid#629]
steps to reproduce
1. download https://www.abelhadigital.com/hostsman/
2. install
3. open hostsman
4. add source
![image](https://github.com/user-attachments/assets/3566ce96-1580-4522-bc9c-500f131b4b3d)

**Comment by gvoze32** [comment]
Have you tried using this link? https://raw.githubusercontent.com/bebasid/bebasid/master/releases/hosts

**Comment by WNnitro** [comment]
> Have you tried using this link? https://raw.githubusercontent.com/bebasid/bebasid/master/releases/hosts

i have, i was using that exact link.

**Comment by galpt** [comment]
@WNnitro 
could you provide an example host that works with hostsman? that way BebasID could try to adjust the format based on that example

**Comment by WNnitro** [comment]
sure, this [project](https://github.com/ignaciocastro/a-dove-is-dumb) works with hostman

**Comment by galpt** [comment]
> sure, this [project](https://github.com/ignaciocastro/a-dove-is-dumb) works with hostman

I took a quick look at the project and I guess it's possible to add support for hostman.
Also, I only maintain the portable version [here](https://github.com/bebasid/bebasid?tab=readme-ov-file#bebashosts-portable), so you need to make sure you're using that if you want to get hostman support after I added the feature later.

I'll mention you later after done updating the program.

**Comment by WNnitro** [comment]
> @WNnitro fixed the formatting issue. Use `Host-Generate-Text-File.bat` to generate the .txt file, it's formatted according to `https://a.dove.isdumb.one/`.

thanks! it works—however i was expecting like an url instead of a local file i have to update once in a while, this works though

**Comment by galpt** [comment]
> > @WNnitro fixed the formatting issue. Use `Host-Generate-Text-File.bat` to generate the .txt file, it's formatted according to `https://a.dove.isdumb.one/`.
> 
> thanks! it works—however i was expecting like an url instead of a local file i have to update once in a while, this still works though

Hosts file is kind of old fashioned nowadays. For an always up-to-date list, it's easier to just use DoH.
We can make the program run as a local server, so in Hostman you can use something like `http://localhost:11111/bebashost.txt`, but it's better to adjust the file in https://raw.githubusercontent.com/bebasid/bebasid/master/releases/hosts directly instead of creating a separate application.

I'll see if I can discuss it with the maintainers and will let you know again here

**Comment by gvoze32** [comment]
@galpt Or you can create github actions to do that, format it automatically

**Comment by ryukora** [comment]
This issue will be closed as resolved.
