### ISSUE TITLE
[BUG] gelbooru.com

### ISSUE THREAD

**Issue by rafroad** [bebasid/bebasid#630]
### Domain atau lain

gelbooru.com, img3.gelbooru.com

### Alasan / Deskripsi mengenai bug

gelbooru menyebabkan redirect ke laman aduan atau menyebabkan connection refused jika menggunakan curl dan menggunakan library request di python

### Screenshot

![image](https://github.com/user-attachments/assets/f16a5415-0920-4eff-87e6-60ee99d0df78)

### ISP Apa yang anda gunakan

telkomsel byu

### Sistem Operasi (OS)

Fedora linux

### Browser

CLI

**Comment by ryukora** [comment]
Provider anda telah diblokir dengan DPI/RTBH.

Jika masih tidak bisa menggunakan hosts, untuk sementara gunakan [BebasDNS](https://github.com/bebasid/bebasdns) dan [BebasIT](https://github.com/bebasid/bebasit) & download [PowerTunnel](https://github.com/krlvm/PowerTunnel), [GreenTunnel](https://github.com/SadeghHayeri/GreenTunnel) atau [Geneva](https://github.com/Kkevsterrr/geneva) dan ikuti langkah-langkah yang ada [disini](https://github.com/bebasid/bebasit?tab=readme-ov-file#cara-mengaplikasikan).

Akan segera di update hosts untuk provider yang anda pakai, bisa akses apa tidak.
Sekian, terimakasih.
`- Ryukura`
