### ISSUE TITLE
[REQ] https://hurawatch.art/home

### ISSUE THREAD

**Issue by masato052** [bebasid/bebasid#634]
### Domain

hurawatch.art

### Alasan

SItus streaming movie bioskop

### ISP Apa yang anda gunakan

Indihome

### Sistem Operasi (OS)

Windows 11

### Browser

Firefox

### Validasi

- [X] Saya telah melihat dan memastikan bahwa domain yang saya masukkan tidak ada di dalam daftar domainlist

### Kode Etik

- [X] Saya menyetujui untuk mengikuti Kode Etik proyek ini

**Comment by ryukora** [comment]
Tolong di kabari, jika sudah berfungsi atau tidak.
jika masih belum bisa akses, silahkan menggunakan [bebasdns DoH/DoT](https://github.com/bebasid/bebasdns/) atau VPN (cth: WARP 1.1.1.1).
