### ISSUE TITLE
[REQ] www.erome.com

### ISSUE THREAD

**Issue by abdurqodir1999** [bebasid/bebasid#635]
### Domain

erome.com

### Alasan

tidak bisa load gamabr

### ISP Apa yang anda gunakan

indihome

### Sistem Operasi (OS)

windows 10

### Browser

chrome

### Validasi

- [X] Saya telah melihat dan memastikan bahwa domain yang saya masukkan tidak ada di dalam daftar domainlist

### Kode Etik

- [X] Saya menyetujui untuk mengikuti Kode Etik proyek ini

**Comment by ryukora** [comment]
Tolong di kabari, jika sudah berfungsi atau tidak.
jika masih belum bisa akses, silahkan menggunakan [bebasdns DoH/DoT](https://github.com/bebasid/bebasdns/) atau VPN (cth: WARP 1.1.1.1).
