### ISSUE TITLE
[REQ] Erolabs

### ISSUE THREAD

**Issue by ModiFlasher** [bebasid/bebasid#638]
### Domain

www.ero-labs.com

### Alasan

Terblokir

### Screenshot / Tambah deskripsi

![Screenshot_20241119-081130_Firefox](https://github.com/user-attachments/assets/204cb4c3-1c74-4516-b121-8ce3571ef7d9)

### ISP Apa yang anda gunakan

LiveOn

### Sistem Operasi (OS)

Android 14

### Browser

Firefox

### Validasi

- [X] Saya telah melihat dan memastikan bahwa domain yang saya masukkan tidak ada di dalam daftar domainlist

### Kode Etik

- [X] Saya menyetujui untuk mengikuti Kode Etik proyek ini

**Comment by ryukora** [comment]
Tolong di kabari, jika sudah berfungsi atau tidak.
jika masih belum bisa akses, silahkan menggunakan [bebasdns DoH/DoT](https://github.com/bebasid/bebasdns/) atau VPN (cth: WARP 1.1.1.1).
