### ISSUE TITLE
[BUG] Erolabs

### ISSUE THREAD

**Issue by ModiFlasher** [bebasid/bebasid#639]
### Domain atau lain

ero-labs.com

### Alasan / Deskripsi mengenai bug

Masih gk bisa diakses / terblokir

### Screenshot

![Screenshot_20241120-184023_Firefox](https://github.com/user-attachments/assets/23d3607a-ec9f-4e7c-9266-4410df2388a6)

### ISP Apa yang anda gunakan

LiveOn

### Sistem Operasi (OS)

Android 14

### Browser

Firefox

### Komentar

Padahal udah di update file hosts nya

**Comment by ryukora** [comment]
`curl -v ero-labs.com`
DPI, silahkan menggunakan VPN atau powertunnel

**Comment by ryukora** [comment]
jika masih belum bisa akses, silahkan menggunakan [bebasdns DoH/DoT](https://github.com/bebasid/bebasdns/) atau VPN (cth: WARP 1.1.1.1).
