### ISSUE TITLE
Tambah wiki/readme section tentang "How To Contribute"

### ISSUE THREAD

**Issue by indrawp** [bebasid/bebasid#64]
Sepertinya di readme bisa ditambah section bagaimana cara ikut berkontribusi di Git repo ini.

Contohnya cara menambahkan url yang ingin di-whitelist, kemudian cara menemukan IP nya, cara menemukan sub-domain yang perlu di-whitelist.

Kalau diperbolehkan, saya akan mulai menulis wiki dan mengupdate readme section.

**Comment by gvoze32** [comment]
Silahkan gan, kontributor bebas mengedit hal mengenai hosts, wiki, readme, dsb, kecuali kalau struktur repo mungkin perlu dirundingkan sesama kontributor.

**Comment by indrawp** [comment]
okay, thanks!
