### ISSUE TITLE
[REQ] remywiki.com

### ISSUE THREAD

**Issue by Daff4K** [bebasid/bebasid#643]
### Domain

remywiki.com

### Alasan

Diblokir

### Screenshot / Tambah deskripsi

![image](https://github.com/user-attachments/assets/32f34c5a-9f79-4f6e-bd21-edd42d49c42d)

### ISP Apa yang anda gunakan

IndiHome

### Sistem Operasi (OS)

Windows 10

### Browser

Chrome

### Komentar

Dua situs wiki game musik terkena blokir, yaitu:
remywiki.com (untuk wiki game musik BEMANI)
silentblue.remywiki.com (untuk wiki game musik SEGA, seperti maimai, Chunithm, dan Ongeki)

### Validasi

- [X] Saya telah melihat dan memastikan bahwa domain yang saya masukkan tidak ada di dalam daftar domainlist

### Kode Etik

- [X] Saya menyetujui untuk mengikuti Kode Etik proyek ini

**Comment by ryukora** [comment]
Tolong di kabari, jika sudah berfungsi atau tidak.

**Comment by Daff4K** [comment]
Setelah perbarui host, akhirnya bisa diakses kembali. Thanks ya~

**Comment by ryukora** [comment]
jika masih belum bisa akses, silahkan menggunakan [bebasdns DoH/DoT](https://github.com/bebasid/bebasdns/) atau VPN (cth: WARP 1.1.1.1).

> Setelah perbarui host, akhirnya bisa diakses kembali. Thanks ya~
