### ISSUE TITLE
[BUG] eporner.com

### ISSUE THREAD

**Issue by anaya77** [bebasid/bebasid#645]
### Domain atau lain

eporner.com

### Alasan / Deskripsi mengenai bug

tidak bisa dibuka lewat pc, baik pakai/tanpa vpn.

### ISP Apa yang anda gunakan

telkomsel

### Sistem Operasi (OS)

windows 7

### Browser

firefox

### Komentar

tidak bisa dibuka lewat pc, baik pakai/tanpa vpn. baru bisa dibuka kalau hosts-nya dibalikin default dan pakai vpn.

**Comment by ryukora** [comment]
Tolong di kabari, jika sudah berfungsi atau tidak.
jika masih belum bisa akses, silahkan menggunakan [bebasdns DoH/DoT](https://github.com/bebasid/bebasdns/) atau VPN (cth: WARP 1.1.1.1).
