### ISSUE TITLE
[REQ] aplaybox.com

### ISSUE THREAD

**Issue by rrleanx** [bebasid/bebasid#649]
### Domain

aplaybox.com

### Alasan

tidak bisa mengakses website hampir 1 minggu menggunakan wifi Indihome

### Screenshot / Tambah deskripsi

![image](https://github.com/user-attachments/assets/49b119b1-6773-4719-83bd-41699d684ea9)

### ISP Apa yang anda gunakan

Indihome

### Sistem Operasi (OS)

Windows 10

### Browser

Chrome

### Komentar

saya sudah coba min, pakai DOH sama Host... masih nggak bisa... request ya min... maaf ngerepotin, makasih banyak

### Validasi

- [X] Saya telah melihat dan memastikan bahwa domain yang saya masukkan tidak ada di dalam daftar domainlist

### Kode Etik

- [X] Saya menyetujui untuk mengikuti Kode Etik proyek ini

**Comment by ryukora** [comment]
jika masih belum bisa akses, silahkan menggunakan [bebasdns DoH/DoT](https://github.com/bebasid/bebasdns/) atau VPN (cth: WARP 1.1.1.1).

**Comment by rrleanx** [comment]
Akhirnyaaaaa.... Internet saya Anomali banget sih... Pas di pasang host baru bisa... 
Ini sudah bisa bang... Terima kasih banyak bang 👍

**Comment by rrleanx** [comment]
> Tolong di kabari, jika sudah berfungsi atau tidak. jika masih belum bisa akses, silahkan menggunakan [bebasdns DoH/DoT](https://github.com/bebasid/bebasdns/) atau VPN (cth: WARP 1.1.1.1).

Akhirnyaaaaa.... Internet saya Anomali banget sih... Pas di pasang host baru bisa...
Ini sudah bisa bang... Terima kasih banyak bang 👍

**Comment by ryukora** [comment]
> > Tolong di kabari, jika sudah berfungsi atau tidak. jika masih belum bisa akses, silahkan menggunakan [bebasdns DoH/DoT](https://github.com/bebasid/bebasdns/) atau VPN (cth: WARP 1.1.1.1).
> 
> Akhirnyaaaaa.... Internet saya Anomali banget sih... Pas di pasang host baru bisa... Ini sudah bisa bang... Terima kasih banyak bang 👍

Sama-sama.
jika masih belum bisa akses, silahkan menggunakan [bebasdns DoH/DoT](https://github.com/bebasid/bebasdns/) atau VPN (cth: WARP 1.1.1.1).
