### ISSUE TITLE
Donasi

### ISSUE THREAD

**Issue by ssvs09** [bebasid/bebasid#66]
Mau tanya. Saya sudah pernah donasi sebelumnya (sebelum UI berubah), apakah harus donasi lagi untuk mendapatkan fitur donasi atau gimana? Makasih

**Comment by nxzlem** [comment]
![chrome_1GA6sNQWUr](https://user-images.githubusercontent.com/30078972/79049353-50507e80-7c4d-11ea-97c1-15ea0c1709de.png)

**Comment by nxzlem** [comment]
Tunggu Developer untuk menjawabnya. Terima Kasih.
-NXzLEM

**Comment by gvoze32** [comment]
Pakai UI yang lama dengan user pass sama untuk menggunakan fitur donasi. Fitur donasi yang baru mungkin udah tidak akan ada lagi.
