### ISSUE TITLE
[BUG] javhub.net

### ISSUE THREAD

**Issue by darkmoonside** [bebasid/bebasid#68]
**Deskripsi mengenai bug**
Video tidak muncul

waktu pakai vpn muncul, 
ini hasil link yang didapat ketika coba donlod pakai vpn :
 
https://142.anyhentai.com/FhBaB0RMWH9iQnE=.mp4?st=A3pnYUPA32zo5DfNjw4OEw&e=1586655336

**Comment by nxzlem** [comment]
Halo, darkmoonside.
Tunggu developer untuk fix hosts link nya.
Terima Kasih
-NXzLEM

**Comment by nxzlem** [comment]
Halo, darkmoonside.
Situs ini sudah di perbaiki/tambahkan dari situs [anyhentai.com].
Sekarang coba re-install bebasid dengan secara mengembalikan hosts ke default, situ install bebasid lagi. Sekarang coba buka situs "anyhentai.com", Kalau bisa atau tidak masih bisa.
Terima Kasih.
-NXzLEM
