### ISSUE TITLE
[BUG] Netflix Error

### ISSUE THREAD

**Issue by ntb4world** [bebasid/bebasid#71]
Netflix Error tidak dapat memutar Filmnya. padahal koneksi internet saya baik2 saja ( provider : indih )

![Screen Shot 2020-04-13 at 07 48 24](https://user-images.githubusercontent.com/56048059/79082902-18386100-7d5d-11ea-8ca2-452dad48a7ed.png)

OS : MacOS High Sierra 10.13

**Comment by gvoze32** [comment]
sudah pakai green tunnel?

**Comment by nxzlem** [comment]
Halo, nbt4world.
Coba Re-Install (uninstall and install) dari GreenTunnel. Situ coba buka situs linknya lagi. Kalo bisa atau tidak.
Terima Kasih.
-NXzLEM
