### ISSUE TITLE
[BUG] netflix.com

### ISSUE THREAD

**Issue by axopadyani** [bebasid/bebasid#73]
**Deskripsi mengenai bug**
Buka Netflix masih kena `ERR_PROXY_CONNECTION_FAILED `

**Screenshot**
![image](https://user-images.githubusercontent.com/23306744/79112956-029d5880-7daa-11ea-9da2-042a56213295.png)
![image](https://user-images.githubusercontent.com/23306744/79112898-da155e80-7da9-11ea-96eb-664317091081.png)

**Device**
 - OS: MacOS Catalina 10.15.4
 - Browser: Chrome

**Comment by gvoze32** [comment]
sudah pakai green tunnel?

**Comment by axopadyani** [comment]
Udah, diinstall lewat `bebasid-gt install` trus di run pake `bebasid-gt start` sesuai sama tutorial

![image](https://user-images.githubusercontent.com/23306744/79112956-029d5880-7daa-11ea-9da2-042a56213295.png)

**Comment by icaksh** [comment]
Apakah sudah melakukan FlushDNS mengingat bahwa dnslify diblokir oleh Indihome di region tertentu?

Jika memang setelah flushdns dan sudah menggunakan Green Tunnel tidak terjadi perubahan apapun, bisa gunakan alternatif lain yaitu menggunakan VPN

**Comment by axopadyani** [comment]
FlushDNS gimana caranya ya? Di tutorial nya engga ada step nya

**Comment by icaksh** [comment]
sudo killall -HUP mDNSResponder

kalau mac sudah direstart biasanya sudah terflush dns sendiri
