### ISSUE TITLE
[REQ] zooqle.com/

### ISSUE THREAD

**Issue by mfauzanf** [bebasid/bebasid#74]
**Ketentuan**
zooqle.com untuk unduh torrent. Thank you!

**Comment by nxzlem** [comment]
Terima kasih melaporkan bug anda.
Sekarang coba re-install bebasid dengan secara mengembalikan hosts ke default, itu install bebasid lagi. Sekarang coba buka situs "zooqle.com".
Terima Kasih.
-NXzLEM
