### ISSUE TITLE
http://nites.tv/

### ISSUE THREAD

**Issue by KevinPalowa** [bebasid/bebasid#76]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts

**Comment by nxzlem** [comment]
Halo, KevinPalowa.
Situs ini sudah di perbaiki/tambahkan dari situs [nites.tv].
Sekarang coba re-install bebasid dengan secara mengembalikan hosts ke default, kemudian installkan bebasid lagi. Sekarang coba buka situs "nites.tv", Kalau bisa atau tidak masih bisa.
Terima Kasih.
-NXzLEM

**Comment by nxzlem** [comment]
OS apa yang kamu gunakan? Windows, Linux, atau Android?

**Comment by PKinfairs** [comment]
Hi, mau nanya aja klo aku buka "nites.tv"/"http://nites.tv" pasti kena internet positif. dan klo "https://nites.tv" aman. ini kira" knp ya?

![image](https://user-images.githubusercontent.com/18479920/79559450-f417af80-80cf-11ea-8aef-09008397bba9.png)

**Comment by nxzlem** [comment]
Saya http:// ama https:// bisa koq coba re-install kali.
