### ISSUE TITLE
[BUG] Internet Positive

### ISSUE THREAD

**Issue by Vser404** [bebasid/bebasid#77]
**Deskripsi mengenai bug**
Saya sudah install seperti biasa pas saya buka di internet masih internet positive

**Device**
 - OS: Windows 10
 - Browser Chrome, Firefox

**Comment by nxzlem** [comment]
Halo, Vser404.
Apakah sudah di re-install "bebasid" dengan secara mendefaultkan ke hosts, kemudian di-install lagi?

**Comment by Vser404** [comment]
sudah saya re install bang sudah saya flush juga.

Pada tanggal Jum, 17 Apr 2020 15:54, NX-LEM <notifications@github.com>
menulis:

**Comment by nxzlem** [comment]
OS apa yang kamu gunain di komputer kamu?

**Comment by nxzlem** [comment]
Halo, Vser404.
Tunggu dulu untuk developer meresponkan Issue (#77).
Terima Kasih.
-NXzLEM

**Comment by PKinfairs** [comment]
bisa dicoba copy file hosts ke C:\Windows\System32\drivers\etc secara manual

**Comment by Vser404** [comment]
caranya gimana bang? Maaf saya kurang tahu

Pada tanggal Jum, 17 Apr 2020 21:03, Erwin Winata <notifications@github.com>
menulis:

**Comment by icaksh** [comment]
Bisa buka https://github.com/bebasid/bebasid/blob/master/dev/readme/FAQ.md

Kalau masih ada trouble, coba buka dengan Chrome, dugaan kuat Edge mengabaikan file hosts seperti Safari

**Comment by nauj42** [comment]
sudah coba buka website yg terblokir dengan https dibelakangnya?

**Comment by Vser404** [comment]
belum bang, saya coba sebentar

Pada tanggal Sab, 18 Apr 2020 09:19, nauj42 <notifications@github.com>
menulis:

**Comment by Vser404** [comment]
sudah saya tambah https fan berhasil bang, makasih banyak informasinya bang
