### ISSUE TITLE
[BUG] Netflix

### ISSUE THREAD

**Issue by cukadapur** [bebasid/bebasid#80]
Halo, sudah seminggu yang lalu saya memakai bebasid dan goodbyedpi. Awalnya baik-baik saja, saya bisa play video di netflix. Tapi, kemarin saya tidak bisa play video di netflix dengan notice

"You seem to be using an unblocker or proxy. Please turn off any of these services and try again"

Saya juga sudah melalukan reinstall bebas id dan goodbyedpi nya. Saat ini saya sudah mencoba berbagai alternatif lain seperti openvpn dan wireguard. namun, tetap tidak bisa play video di netflixnya. Mohon bantuannya. Terima kasih.

Device
 - OS: Windows 10
 - Browser : Firefox
 - Provider: Indihm

**Comment by icaksh** [comment]
1. VPN & Proxy terblacklist oleh Netflix, gunakan VPN / Proxy dari penyedia lainnya
2. Untuk urusan GoodbyeDPI, menunggu yang menggunakan windows untuk menjawab

Thanks
