### ISSUE TITLE
[REQ] kimochi.info

### ISSUE THREAD

**Issue by somnus180** [bebasid/bebasid#81]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts

**Comment by nxzlem** [comment]
Halo, somnus180.
Situs ini sudah di perbaiki/tambahkan dari situs [kimocchi.info].
Sekarang coba re-install bebasid dengan secara mengembalikan hosts ke default, kemudian installkan bebasid lagi. Sekarang coba buka situs "kimochi.info", Kalau bisa atau tidak masih bisa.
Kalau ada yg masalah dengan bebasid, liat di FAQ. https://github.com/bebasid/bebasid/blob/master/dev/readme/FAQ.md
Terima Kasih.
-NXzLEM
