### ISSUE TITLE
[BUG] onlyfans.com

### ISSUE THREAD

**Issue by bhaskoro-muthohar** [bebasid/bebasid#85]
**Deskripsi mengenai bug**
Raised an error 'This site can't be reached, onlyfans.com took too long to respond.'

**Device**
 - OS: [cth. Windows 10]
 - Browser [cth. Chrome, Firefox, Edge]

**Comment by nxzlem** [comment]
Halo, bhaskoro-muthohar.
Situs "OnlyFans.com" IP sdh ganti 54.175.88.73 ke 35.153.48.222, skrg coba re-install bebasid lg selanjutnya buka situs lagi kalau bisa atau tdk.
Terima Kasih.
-NXzLEM
