### ISSUE TITLE
[REQ] javlibrary.com sekarang berubah jadi javlib.com

### ISSUE THREAD

**Issue by adhiyasa-putra-permana** [bebasid/bebasid#86]
![Screenshot (1)](https://user-images.githubusercontent.com/61222935/80050670-7d9c0700-8540-11ea-9f0c-eb3fe147021e.png)

**Comment by adhiyasa-putra-permana** [comment]
gan kalo sudah tolong di delete ya issue nya.. akun saya pake nama lengkap

**Comment by nxzlem** [comment]
Halo, adhiyasa-putra-permana.
situs "javlib.com" sdh di pindahin/perbaiki, coba re-install bebasid lagi selanjutnya buka situs lagi terima kasih
-NXzLEM

**Comment by adhiyasa-putra-permana** [comment]
gan issuenya bisa dihapus?

**Comment by nxzlem** [comment]
ok saya di hapusin y

**Comment by adhiyasa-putra-permana** [comment]
situsnya masih belum bisa gan, jadi javlibrary.com & javlib.com sama2 diperlukan.

terus ini kok gak dihapus2 -_-

**Comment by nxzlem** [comment]
pake windows atau mac?

**Comment by andraantariksa** [comment]
Yang bisa ngehapus issue cuma admin organisasi, kemaren sih udah gw bilangin buat ngehapus... yah nanti gw coba bilang lagi abis issuenya solved

> To delete an issue in a repository owned by an organization:
> 
> An organization owner must first enable deleting an issue for the organization's repositories.
> You must have admin privileges in the repository or be an organization owner.

https://webapps.stackexchange.com/questions/124031/how-can-i-delete-my-posted-issue-on-github

**Comment by adhiyasa-putra-permana** [comment]
pake windows gan

javlibrary kalau dibuka kedirect ke javlib terus balik lagi ke javlibrary.. cobain deh


oke ditunggu penghapusannya wkwk

**Comment by nxzlem** [comment]
kan aq bilang buka bebasid, pilih default host idnya, selanjutnya buka lagi bebasidnya trus install lagi

**Comment by adhiyasa-putra-permana** [comment]
sip bisa gan

**Comment by andraantariksa** [comment]
@gvoze32 ini issuenya dihide kalo bisa atau dihapus

**Comment by nxzlem** [comment]
> @gvoze32 ini issuenya dihide kalo bisa atau dihapus

Gk dihubungi gvoze32 ke discord?

**Comment by andraantariksa** [comment]
xd cuma ada FBnya
