### ISSUE TITLE
hanime.tv

### ISSUE THREAD

**Issue by wrlrdgmng** [bebasid/bebasid#87]
tolong diperbaiki dong yang hanime.tv tidak bisa play video. terima kasih

**Comment by nxzlem** [comment]
Halo wrldgmng,
situsnya sdh di perbaiki oleh NXzLEM.
skrg kamu hrs reinstall bebasid contoh langkah2nya:
1. buka bebasid
2. pilih default host (tunggu sampai install done)
3. buka bebasid lagi
4. installin bebasid (sampai installnya done)
