### ISSUE TITLE
microsoft.ace.oledb.12.0

### ISSUE THREAD

**Issue by johnremboh** [bebasid/bebasid#876]
![Untitled](https://user-images.githubusercontent.com/39485828/73604250-fd5caa00-45bf-11ea-89aa-b7e0a5f1218d.jpg)

gagal login terus om hiks...

bebas v. 7.9.0.0

win10 1903
last make unblockhostid v. 6.6.0.0 masih bisa.
apa karena ganti msoffice om? baru up ke ms 2019...

**Comment by gvoze32** [comment]
Coba baca note bro, terima kasih

https://github.com/bebasid/bebasid#donate

**Comment by johnremboh** [comment]
my bad om, makasih banyak sebelumnya...
