### ISSUE TITLE
[BUG] Access Denied

### ISSUE THREAD

**Issue by handhikadsa** [bebasid/bebasid#881]
**Deskripsi mengenai bug**
Ketika ingin install Access to the path "C:\Windows\System32\drivers\etc\hosts" is denied. lalu klik continue dan tidak terjadi apa2, webiste yang diblokir kominfo tetap tidak bisa dibuka

**Screenshot**
![Screenshot_1](https://user-images.githubusercontent.com/59341485/73758331-0ce51a00-479d-11ea-8382-585f1d9b00ef.jpg)

**Device**
 - OS: Windows 10 Pro
 - Browser : Chrome

**Comment by gvoze32** [comment]
Run program as administrator
