### ISSUE TITLE
[FAQ] Cara uninstall bebasid di MacOS

### ISSUE THREAD

**Issue by iqbalsetiawan** [bebasid/bebasid#91]
Hallo, bagaimana cara apabila ingin melakukan uninstall / remove bebasid, khususnya mac?

**Comment by andraantariksa** [comment]
Apa sebelumnya pernah backup isi file hostsnya?

**Comment by iqbalsetiawan** [comment]
Belum kok, saya hanya install bebasid, lgsg bisa semua (termasuk netflix), tanpa perlu installl ekstensi yg lain.

**Comment by andraantariksa** [comment]
Oke, berarti kita asumsikan file hostsnya belum pernah diotak-atik ya sebelumnya.

Untuk cara uninstallnya bisa cek link ini https://www.vtravel.info/how-to-restore-the-original-default-etchosts-file-in-mac-os-x
