### ISSUE TITLE
[REQ] nijicollage.xyz

### ISSUE THREAD

**Issue by Theiamilis** [bebasid/bebasid#92]
**Ketentuan**
Pastikan website yang akan direquest belum tersedia di hosts

**Comment by nxzlem** [comment]
Halo, Theiamillis.
Situs "nijicollage.xyz" sudah ditambahkan oleh 'kucinghitam13' dan Lupa di tambahkan website e.g. "www." dari Situs "nijicollage.xyz" dari 'NXzLEM'.
Nah sekarang, kalau mau buka situs "nijicollage.xyz" bisa lagi, re-install bebasid dengan cara :
1. Buka program "bebasid.bat".
2. Pilih default host "ketik (W) terus enter" (Tunggu sampai Installnya selesai).
3. Buka program "bebasid.bat" lagi.
4. Pilih Installin bebasid "ketik (Y) terus enter" (Tunggu sampai installnya selesai).

Terima Kasih untuk menrequestkan situs anda.
-NXzLEM
