### ISSUE TITLE
[BUG] hgamecg.com

### ISSUE THREAD

**Issue by Theiamilis** [bebasid/bebasid#93]
**Deskripsi mengenai bug**
gambar tidak muncul

**Screenshot**
![Screenshot (647)](https://user-images.githubusercontent.com/54315757/80309468-77877e00-87ff-11ea-9f3c-9fa89c9f69e7.png)

**Device**
 - OS: Windows 10
 - Browser Firefox

**Comment by nxzlem** [comment]
Halo, Theiamills
Situs "hgamecg.com"nya sudah di perbaiki sama gvoze32 yang situsnya "thumbnail.hgamecg.com" sudah di tambahkan dari hosts, dari (Merge Request #94).
Nah sekarang, kalau mau buka situs bisa lagi, re-install bebasid dengan cara :
1. Buka program "bebasid.bat".
2. Pilih default host "ketik (W) terus enter" (Tunggu sampai Installnya selesai).
3. Buka program "bebasid.bat" lagi.
4. Pilih Installin bebasid "ketik (Y) terus enter" (Tunggu sampai installnya selesai)
Terima Kasih.
-NX-LEM
