### ISSUE TITLE
[REQ] rapidporngator.com

### ISSUE THREAD

**Issue by anaya77** [bebasid/bebasid#95]
request web rapidporngator.com

**Comment by nxzlem** [comment]
Halo, anaya77.
Situs "rapidporngator.com" sudah ditambahkan (dari NXzLEM) di hosts.
Kalau mau buka situs "rapidporngator.com" bisa lagi, re-install bebasid dengan cara :

Buka program "bebasid.bat".
Pilih default host "ketik (W) terus enter" (Tunggu sampai Installnya selesai).
Buka program "bebasid.bat" lagi.
Pilih Installin bebasid "ketik (Y) terus enter" (Tunggu sampai installnya selesai).
Terima Kasih untuk menrequestkan situs anda.
-NXzLEM
